### ISSUE TITLE
Proposal: make spec.platforms[].files optional

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#135]
If no `files` field specified, we may consider assuming:

```
files
- from: '*'
  to: '.'
```

then developers can just point to the entrypoint within the extracted archive through `bin:` field.

This already started to become a common pattern in several plugins.

**Comment by lbb** [comment]
I like the idea.
It reduces the amount of text a plugin maintainer needs to process.
It also helps newcomers to understand the plugin manifest concepts quicker.

I'm not sure if this is implicit behavior, which can lead to confusion.

**Comment by ahmetb** [comment]
/cc @corneliusweig 
thoughts on this?

**Comment by corneliusweig** [comment]
To me this sounds like a sane default.
The only downside I see is that plugin authors may inadvertently install more files than necessary. For example, if the archive contains go binaries for all platforms, this will copy over all, even though only one is needed. If plugin authors use the simplest working solution, this will happen and that kind of issue is not easy to spot in manifest reviews.

**Comment by ahmetb** [comment]
I think it’s just good for bash script plugins, or those that aren’t packaging all platform binaries into one archive file. We can survey the plugins we have today to measure people’s tendencies.  
/priority awaiting-more-evidence

**Comment by corneliusweig** [comment]
I just went through the existing plugins. Among the go plugins the by far predominant method is to create separate tar archives for each platform.

Given that, it looks safe to go ahead with this proposal. However, we should make a note in the documentation that plugin authors become aware of this potential issue.
