### ISSUE TITLE
Move to k8s.io/cli-runtime

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#144]
https://github.com/kubernetes/cli-runtime

Since krew is already a plugin today, using `cli-runtime` can help us standardize some cmdline flags (esp. useful for `list` cmd probably). (I don't know what else we'd get out of it right away.)

/cc @juanvallejo

**Comment by ahmetb** [comment]
No prow here, also can't assign without adding you to org or transferring repo. 🤷‍♂️

**Comment by ahmetb** [comment]
What would we get out of cli-runtime if we migrated today (other than standardized flags)?

**Comment by juanvallejo** [comment]
> What would we get out of cli-runtime if we migrated today (other than standardized flags)?

Mainly those. Which we could then use to obtain a "restclient config" we could then use to talk to the kube api using `k8s.io/client-go`. We'd get printing and other cli helpers as well. Not really sure to what extent Krew needs all of these today though.

**Comment by ahmetb** [comment]
Makes sense. We don't connect to API so we don't need the restclient.

The only part that could've been useful is `--output` flag for `kubectl krew list`, and even in that case it would be severity/P2. We'll hold off on this.

**Comment by ahmetb** [comment]
/close
For now krew doesn't need any of the packages offered by cli-runtime.
