### ISSUE TITLE
Proposal: deprecate "head" field

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#152]
Given now `--manifest` and `--archive` can be provided to `krew install` command to ease installing plugins locally for development, `head:` no longer provides a good value:

- it makes plugin versioning and upgrade model harder to reason about
- homebrew also recently deprecated `head` field
- provides no real value at this point

**Comment by corneliusweig** [comment]
+1
As far as I know, additional fields in manifests are simply ignored, so that the `head` field can be removed altogether.

**Comment by ahmetb** [comment]
> additional fields in manifests are simply ignored

I think we disabled unknown field check at some point to enable some migration in early days that introduced a new field, but it makes sense to keep this check disabled (as the index schema may move faster than the local krew version).

**Comment by corneliusweig** [comment]
Yes, I saw that line commented out :)
