### ISSUE TITLE
Krew installation fails on Windows 10

### ISSUE THREAD

**Issue by juv** [kubernetes-sigs/krew#156]
I followed the instructions in the readme to install Krew on Windows.
I get the following error: 

```
PS >  .\krew-windows_amd64.exe install --manifest=..\krew.yaml --archive=..\krew
.zip

Installing plugin: krew
W0228 10:58:55.052380  158104 install.go:132] failed to install plugin "krew": failed to create a symlink form "C:\\Users\\my-user\\.krew\\bin" to "C:\\Users\\my-user\\.krew\\bin\\kubectl-krew.exe":
symlink C:\Users\my-user\.krew\store\krew\57788e8c7af1b5b000954455aa9ca2e4a18a50a020faf54d18a3ccf79ad04049\krew.exe C:\Users\my-user\.krew\bin\kubectl-krew.exe:
A required privilege is not held by the client.
F0228 10:58:55.182669  158104 root.go:52] failed to install some plugins: [krew]
``` 

I also tried with `.\krew-windows_amd64.exe install --manifest="C:\Development\K8s\krew\krew.yaml" --archive="C:\Development\K8s\krew\krew.zip"`, same error. 

Is there anything I'm missing?

**Comment by ahmetb** [comment]
Not a known issue. But if you search for “A required privilege is not held by the client.“ it seems like it’s a machine issue. Perhaps something like a policy is preventing you.

**Comment by juv** [comment]
@ahmetb it looks like creating y symlink is requiring special permissions on the machine (https://github.com/golang/dep/issues/773 is similar). I do not have those. Is it possible to have a switch to copy the files instead of creating a symlink? 

Can I solve this manually? What do I need to copy where?

**Comment by ahmetb** [comment]
> creating a symlink is requiring special permissions on the machine

I think we tried this on windows and it was working. Do you have any data points on `os.Symlink` go function generally not working on most windows machines?

> What do I need to copy where?

The error shows you the two paths you need to copy. Copy the one in .krew\store\... to .krew\bin\... path that's listed in the error.

**Comment by juv** [comment]
@ahmetb  Which is the second path are you referring to?

I have copied 
`C:\Users\my-user\.krew\store\krew\57788e8c7af1b5b000954455aa9ca2e4a18a50a020faf54d18a3ccf79ad04049\krew.exe`
to: `C:\Users\my-user\.krew\bin\kubectl-krew.exe`

I added the folder `%USERPROFILE%\.krew\bin` to my path. 

kubectl plugin list shows no plugins though: 
`PS C:\Development\Git> kubectl plugin list
error: no plugins installed.`

**Comment by ahmetb** [comment]
Try installing any kubectl plugin **without** krew and see if that works.

Right now you're potentially reporting a kubectl bug (issues with the plugin mechanism) and this is not the correct repo for that.

**Comment by rnarayana** [comment]
Is it manifest= or source= ? The installation instructions (https://github.com/GoogleContainerTools/krew/blob/v0.2.1/README.md) specifies 'source' but it fails on windows with the error "F0304 20:06:42.638733    1884 root.go:52]unknown flag: --source"

**Comment by ahmetb** [comment]
Should be --manifest. I think the readme was wrong so it’s changed post-v0.2.1.

**Comment by ahmetb** [comment]
@jon-walton thanks for detailing these out. I think this is a legit bug. I'm surprised Go's os.Symlink code did not work on native Windows execution. 

In your case I'm seeing the installation error is actually different:

> `failed to install plugin "krew": failed to dowload and move during installation: could not rename file from "/tmp/krew-temp-move493619428" to "/home/jon/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a": rename /tmp/krew-temp-move493619428 /home/jon/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a: permission denied`

**Comment by ahmetb** [comment]
@jon-walton thanks for detailing these out. I think this is a legit bug. I'm surprised Go's os.Symlink code did not work on native Windows execution. 

In your case I'm seeing the installation error is actually different:

> `failed to install plugin "krew": failed to dowload and move during installation: could not rename file from "/tmp/krew-temp-move493619428" to "/home/jon/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a": rename /tmp/krew-temp-move493619428 /home/jon/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a: permission denied`

Similarly, the `cannot allocate memory` error is very puzzling to me. From the strace, it looks like you are actually running `krew-linux-amd64` binary on WSL, which should work. This sounds like it might be a Golang on WSL memory corruption issue.

Can you provide strace for `kubectl krew update` as well? 

-----

I'm gonna keep this open for tracking. I have no idea on where to start, or a windows machine to try things right now. Any contributions/help welcome.

**Comment by jon-walton** [comment]
@ahmetb There's not much to talk about with `kubectl krew update`

```text
newfstatat(AT_FDCWD, "/home/jon/.krew/bin/kubectl-krew", {st_mode=S_IFREG|0755, st_size=10490849, ...}, 0) = 0
execve("/home/jon/.krew/bin/kubectl-krew", ["/home/jon/.krew/bin/kubectl-krew", "update"], 0xc000144750 /* 17 vars */) = -1 ENOMEM (Cannot allocate memory)
write(2</dev/tty1>, "cannot allocate memory\n", 23) = 23
exit_group(1)                           = ?
```

What's interesting, is this seems to be intermittent? but once the ```cannot allocate memory``` error appears for a particular command, I have to restart WSL to clear it (I've not seen it recover without restarting WSL)

```text
~$ k krew help
cannot allocate memory
~$ k krew update
cannot allocate memory
~$ k krew info
F0306 10:27:43.144134     734 root.go:52] requires at least 1 arg(s), only received 0
~$ k krew info
F0306 10:27:45.033008     747 root.go:52] requires at least 1 arg(s), only received 0
~$ k krew list
cannot allocate memory
~$ k krew info
cannot allocate memory
```

Here's a strace of it working, I've split it into 2 for brevity

```text
newfstatat(AT_FDCWD, "/home/jon/.krew/bin/kubectl-krew", {st_mode=S_IFREG|0755, st_size=10490849, ...}, 0) = 0
execve("/home/jon/.krew/bin/kubectl-krew", ["/home/jon/.krew/bin/kubectl-krew", "list"], 0xc00012bcb0 /* 17 vars */) = 0
arch_prctl(ARCH_SET_FS, 0xd07ef0)       = 0
sched_getaffinity(0, 8192, [0, 1, 2, 3]) = 64
mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af7230000
mmap(0xc000000000, 67108864, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xc000000000
mmap(0xc000000000, 67108864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xc000000000
mmap(NULL, 33554432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af5230000
mmap(NULL, 2162688, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af5020000
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af5010000
clock_gettime(CLOCK_MONOTONIC, {tv_sec=16, tv_nsec=670926800}) = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af5000000

.....

newfstatat(AT_FDCWD, "/home/jon/.krew", {st_mode=S_IFDIR|0755, st_size=512, ...}, 0) = 0
newfstatat(AT_FDCWD, "/tmp/krew-downloads", {st_mode=S_IFDIR|0755, st_size=512, ...}, 0) = 0
newfstatat(AT_FDCWD, "/home/jon/.krew/store", {st_mode=S_IFDIR|0755, st_size=512, ...}, 0) = 0
newfstatat(AT_FDCWD, "/home/jon/.krew/bin", {st_mode=S_IFDIR|0755, st_size=512, ...}, 0) = 0
newfstatat(AT_FDCWD, "/home/jon/.krew/index/.git", 0xc0001826b8, 0) = -1 ENOENT (No such file or directory)
clock_gettime(CLOCK_REALTIME, {tv_sec=1551839442, tv_nsec=2159600}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=16, tv_nsec=725053800}) = 0
openat(AT_FDCWD, "/etc//localtime", O_RDONLY) = 3</etc/localtime>
read(3</etc/localtime>, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0"..., 4096) = 127
read(3</etc/localtime>, "", 4096)       = 0
close(3</etc/localtime>)                = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1551839442, tv_nsec=3956800}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=16, tv_nsec=726913800}) = 0
write(2</dev/tty1>, "F0306 10:30:42.002159      18 ro"..., 113) = 113
```

the `write()` was

```F0306 10:30:42.002159      18 root.go:52] krew local plugin index is not initialized (run "kubectl krew update")```

If I run `kubectl krew list` for a second time, I get ```cannot allocate memory```


as for running on Windows directly...

- I copied krew-windows_amd64.exe to my PATH
- renamed krew-windows_amd64.exe to kubectl-krew.exe
- kubectl plugin list
The following kubectl-compatible plugins are available:

c:\tools\kubectl-krew.exe

- try it out...

k version --client
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"windows/amd64"}


PS C:\Users\jonwa> k krew --help
not supported by windows
PS C:\Users\jonwa> k krew help
not supported by windows
PS C:\Users\jonwa> k krew list
not supported by windows
PS C:\Users\jonwa> k krew install
not supported by windows


😕

**Comment by rnarayana** [comment]
Ditto for me on WSL ubuntu and on win 10.

**Comment by jon-walton** [comment]
A quick follow up.

If I run krew-install in an administrative powershell prompt, it installs but I get the same ```not supported by windows``` error

```text
krew-windows_amd64.exe install --manifest krew.yaml --archive krew.zip
Installing plugin: krew
CAVEATS:
\
 |  krew is now installed! To start using kubectl plugins, you need to add
 |  krew's installation directory to your PATH:
 |
 |    * macOS/Linux:
 |      - Add the following to your ~/.bashrc or ~/.zshrc:
 |          export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
 |      - Restart your shell.
 |
 |    * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable
 |
 |  Run "kubectl krew" to list krew commands and get help.
 |  You can find documentation at https://github.com/GoogleContainerTools/krew.
/
Installed plugin: krew
```

```text
k krew help
not supported by windows
```

**Comment by jon-walton** [comment]
I don't think the ```cannot allocate memory``` is related to krew

installing https://github.com/jordanwilson230/kubectl-plugins
```text
$ k plugin list
The following kubectl-compatible plugins are available:

/home/jon/.krew/bin/kubectl-krew
/home/jon/.kube/plugins/jordanwilson230/kubectl-image
/home/jon/.kube/plugins/jordanwilson230/kubectl-ip
/home/jon/.kube/plugins/jordanwilson230/kubectl-prompt
/home/jon/.kube/plugins/jordanwilson230/kubectl-ssh
/home/jon/.kube/plugins/jordanwilson230/kubectl-switch
/home/jon/.kube/plugins/jordanwilson230/kubectl-uptime

$ k uptime
cannot allocate memory
```


@juv I also received the error ```A required privilege is not held by the client.``` when trying to install directly in Windows. Have you tried again using an administrative powershell prompt?

**Comment by jon-walton** [comment]
this seems to definitely be a kubectl issue?

```text
$ ll ~/.krew/bin
total 0
drwxr-xr-x 1 jon jon 512 Mar  6 11:20 ./
drwxr-xr-x 1 jon jon 512 Mar  6 11:18 ../
lrwxrwxrwx 1 jon jon 104 Mar  6 11:20 kubectl-krew -> /home/jon/.krew/store/krew/dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a/kubectl-krew*

$ kubectl-krew update
Updated the local copy of plugin index.

$ kubectl-krew list
PLUGIN VERSION
krew   dc2f2e1ec8a0acb6f3e23580d4a8b38c44823e948c40342e13ff6e8e12edb15a

$ kubectl-krew search
NAME                           DESCRIPTION                                        STATUS
access-matrix                  Show an access matrix for all resources            available
bulk-action                    Do bulk actions on Kubernetes resources.           available
ca-cert                        Print the PEM CA certificate of the current clu... available
change-ns                      View or change the current namespace via kubectl.  available
cssh                           SSH into Kubernetes nodes                          available
debug-shell                    Create pod with interactive kube-shell.            available
exec-all                       Execute a command in all of the containers in a... available
exec-as                        Like kubectl exec, but offers a `user` flag to ... available
get-all                        Like 'kubectl get all', but _really_ everything    available
gke-credentials                Fetch credentials for GKE clusters                 available
krew                           Package manager for kubectl plugins.               installed
kubesec-scan                   Scan Kubernetes resources with kubesec.io.         available
match-name                     Match names of pods and other API objects          available
mtail                          Tail logs from multiple pods matching label sel... available
node-admin                     List nodes and run privileged pod with chroot      available
open-svc                       Open the Kubernetes URL(s) for the specified se... available
pod-logs                       Display a list of pods to get logs from            available
pod-shell                      Display a list of pods to execute a shell in       available
prompt                         Prompts for user confirmation when executing co... available
rbac-lookup                    Reverse lookup for RBAC                            available
rbac-view                      A tool to visualize your RBAC permissions.         available
resource-capacity              Provides an overview of resource requests, limi... available
restart                        Restarts a pod with the given name                 available
rm-standalone-pods             Remove all pods without owner references           available
sniff                          easly start a remote packet capture on kubernet... available
ssh-jump                       A kubectl plugin to SSH into Kubernetes nodes u... available
sudo                           Run Kubernetes commands impersonated as group s... available
view-secret                    Decode secrets                                     available
view-serviceaccount-kubeconfig Show a kubeconfig setting to access the apiserv... available
view-utilization               Shows cluster cpu and memory utilization           available
warp                           Sync and execute local files in Pod                available

$ kubectl-krew install sniff
Updated the local copy of plugin index.
Installing plugin: sniff
CAVEATS:
\
 |  This plugin needs the following programs:
 |  * wireshark (optional, used for live capture)
/
Installed plugin: sniff

$ kubectl-sniff
Usage:
  sniff pod [-n namespace] [-c container] [-f filter] [-o output-file] [-l local-tcpdump-path] [-r remote-tcpdump-path] [flags]

Examples:
kubectl sniff hello-minikube-7c77b68cff-qbvsd -c hello-minikube

Flags:
  -c, --container string             container (optional)
  -f, --filter string                filter (optional)
  -h, --help                         help for sniff
  -l, --local-tcpdump-path string    local static tcpdump binary path (optional)
  -n, --namespace string             namespace (optional) (default "default")
  -o, --output-file string           output file path, tcpdump output will be redirect to this file instead of wireshark (optional)
  -r, --remote-tcpdump-path string   remote static tcpdump binary path (optional) (default "/tmp/static-tcpdump")
  -v, --verbose                      if specified, ksniff output will include debug information (optional)
Error: not enough arguments

$ ~/.krew/bin/kubectl-sniff my-pod -n my-ns
INFO[0000] using tcpdump path at: '/home/jon/.krew/store/sniff/6250c1cf8fcf70fa4a946ca9ff70c74b8372f1c744d9bef214a5567970e7e7d4/static-tcpdump'
INFO[0000] no container specified, taking first container we found in pod.
INFO[0000] selected container: 'my-container'
INFO[0000] sniffing on pod: 'my-pod' [namespace: 'my-ns', container: 'my-container', filter: '']
INFO[0000] checking for static tcpdump binary on: '/tmp/static-tcpdump'
INFO[0002] couldn't find static tcpdump binary on: '/tmp/static-tcpdump', starting to upload
INFO[0006] verifying tcpdump uploaded successfully
INFO[0008] static-tcpdump found: '-rwxr-xr-x    1 root     root       2642872 Jan  1  1970 /tmp/static-tcpdump
'
INFO[0008] tcpdump uploaded successfully
INFO[0008] spawning wireshark!
```

**Comment by ahmetb** [comment]
@jon-walton do you mind opening an issue to https://github.com/kubernetes/kubectl with a minimal repro with one of those plugins (ideally without mentioning krew, since it's not a krew issue).

**Comment by jon-walton** [comment]
opened https://github.com/kubernetes/kubectl/issues/603 . it also repros with the example foo plugin

**Comment by ahmetb** [comment]
/close
since it's being tracked on kubectl repo.
