### ISSUE TITLE
Transfer krew and krew-index projects to github.com/kubernetes-sigs

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#160]
After discussions made in the Kubernetes SIG CLI group (and SIG Architecture, SIG Apps was informed as well), it's decided that the SIG CLI will adopt Krew (and its index) as a sub-project.

As a result repositories https://github.com/GoogleContainerTools/krew/ and https://github.com/GoogleContainerTools/krew-index will be transferred to `github.com/kubernetes-sigs` the organization.

You can find more discussion in the:

- [SIG CLI meeting notes](https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.himo1st0tqyy) (March 13, 2019) 
- [kubernetes-sig-cli Google Groups e-mail thread](https://groups.google.com/d/msg/kubernetes-sig-cli/9fWm_aZ-AC8/RkFUFR_JBQAJ).

As current maintainers of krew, we appreciate help and direction of the Kubernetes SIG CLI group. 🙌

**Comment by superbrothers** [comment]
@lbb @ahmetb Great thanks for starting this awssome project! I'll continue to contribute to Krew!

**Comment by ahmetb** [comment]
@superbrothers thanks for your contributions, I hope stick with us for what's ahead. 😃
