### ISSUE TITLE
Store the installed plugin receipt for deletion/info commands

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#163]
Right now we rely on the fact that the plugin name has a corresponding manifest file in `.krew/index/plugins/$NAME.yaml` path.

This is problematic for two reasons:

1. If a plugin is installed, but removed from the centralized repo, the commands like `krew uninstall` or `krew info` do not work.
2. If a plugin is installed `krew info` shows info of the manifest that's in the local copy of index; not the one that's installed. This causes issues like description/caveats may not be applicable to the version that's installed.

Ideally we should store the manifest of an installed plugin in a place so we know how to uninstall it properly without relying on the local copy of the plugin index.

**Comment by corneliusweig** [comment]
Has anybody started working on this? If not, I'd like to do this.
