### ISSUE TITLE
Proposal: Use semver to determine plugin versions and upgrades

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#166]
As of writing the `version` field in plugin spec is purely for documentation.

We should consider enforcing and using this field (as a [semver](https://semver.org) value) so that we could rely on this value to determine if a plugin has a "newer" version or not.

Right now we rely on sha256 sum of the installed `spec.platforms` value (and compare it to the one on the local copy of the manifest) to determine if the version of the plugin we installed is the same or not (no notion of newer/older).

This would mean:

- Potentially **breaking** change to enforce all plugins to use `version` field. (Can be done in a non-breaking way if we keep the existing code path intact.)
- Add tests to `krew-index` repo's CI and check every plugin manifest update increments the `version` value.
- Refactor the plugin "upgrade" path:
  - compare the currently installed version (this can be encoded to the install directory name and/or to an "install receipt" #163) WITH the version field of the plugin in the local copy of the index,
  - determine if an upgrade can be made.

**Comment by corneliusweig** [comment]
- I'm in favor of the breaking change here. Keeping the old code path will mean a lot more maintenance effort in the future. Besides, the upgrade behavior for versioned and unversioned plugins will be different, but users won't know why. The currently affected plugins are
  ```
  ca-cert.yaml
  mtail.yaml
  rm-standalone-pods.yaml
  view-secret.yaml
  ```
  So I think for those few we can as well add a dummy version like `v0.0.1-krew`.

- I'm not convinced that krew should forbid downgrading. Imagine that somebody bumps his major version number but finds out that it has design flaws/ users are upset/ suffers from a security vulnerability. In those cases it should be possible to revert to a known good version.

If nobody objects, I'd like to take this up when #195 is done.

**Comment by ahmetb** [comment]
> If nobody objects, I'd like to take this up when 195 is done.

Sounds good.

(inline replies to the following are appreciated)

I'm trying to understand I said earlier "this is potentially a breaking change".
I think if we go ahead and update all plugins with missing `version` field to v0.0.0 like you said, it should be fine. Newer versions of krew will know what to do with the version numbers.

I think we need to decide if we wanna use the version number in the `store/{name}/{version}` instead of `store/{name}/{sha256}`. (Currently we look if the installed sha256 matches, if not, we upgrade.) So perhaps we can keep the directory naming the same?

When we'll have a version receipt with #195, we can just compare the versions in the receipt VS index, and determine if it should be upgraded.


> * I'm not convinced that krew should forbid downgrading

This deserves a separate discussion. This _really_ simplifies a lot of stuff. (We can't solve everything for everyone. It's still possible to install/use plugins outside krew.) Logistics-wise, it's unclear how to get "older" versions of a plugin index –but let's discuss this in a separate thread.

**Comment by corneliusweig** [comment]
> I think if we go ahead and update all plugins with missing `version` field to v0.0.0 like you said, it should be fine.

To be precise, the version is not missing in any manifest. However, the ones listed above all have the version set to "master", which is an invalid semver.

> So perhaps we can keep the directory naming the same?

That should be feasible. The downside is again increased maintenance effort, and it's not pretty (because it's useless). However, this can be taken up in a separate PR, if we feel this is necessary. For now, let's not change the directory structure.

----

> This _really_ simplifies a lot of stuff.

Just to clarify: do you mean _skipping the downgrade test_ simplifies a lot. Or rather _not having downgrades_  simplifies a lot? If you meant the latter, then I don't understand the problem there.

**Comment by ahmetb** [comment]
Latter. Feel free to open a separate issue and we can discuss. Finding old versions of a manifest wouldn't be trivial.
