### ISSUE TITLE
Update apiGroup in plugin manifest

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#168]
Right now we use `apiVersion: krew.googlecontainertools.github.com/v1alpha2`, this should be changed to a more appropriate value.

/kind proposal
/priority important-soon

**Comment by corneliusweig** [comment]
This makes absolute sense.

I was looking into how this could be done. I do think however, that we should not rush things here.
1. this needs to be coordinated with `krew-index`
2. given that krew needs to be able to self-update, the `apiVersion` of the krew manifest in `krew-index` cannot be updated without risking manual re-installs for many krew users.
3. krew should have a proper `apiVersion` which should be bumped with schema updates. This has not happened with the addition of the `homepage` field, which I find questionable.

**Comment by ahmetb** [comment]
I think a larger discussion we should have is whether we should stick to Kubernetes API format as we have nothing to do with apiserver. `kustomize` has opted in to this, but it makes more sense there as they play with Kubernetes API objects.

For now, the apiGroup field is pretty noop. It’s there for cosmetic purposes.

**Comment by corneliusweig** [comment]
I think it makes sense if we plan to evolve the manifest schema. It would need some version info, then why not take the k8s standard.
After all, maybe we want to store plugin manifests in etcd at some point and then they need to adhere to the api-resource schema.

Bottom line is: I think we should keep it as is.

----

Now should we still change the cosmetic apiVersion? The more I think about this, the less I like it. It all comes down to a bad user experience when the new apiVersion is introduced in `krew-index`, but the user is still running old `krew`.
