### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by aparamon** [kubernetes-sigs/krew#170]
[Chocolatey](https://chocolatey.org) is extremely useful software package manager for Windows. It provides packages for [kubectl](https://chocolatey.org/packages/kubernetes-cli) and many other programs.

It is proposed that Krew gets Chocolatey package.

**Comment by ahmetb** [comment]
Krew is a kubectl plugin that’s distributed via Krew.
We currently don’t package krew for any other package manager as it reduces the maintenance work and helps us dogfood Krew.

**Comment by aparamon** [comment]
@ahmetb  Thanks for your prompt feedback!
Linux/macOS install instructions are much simple and boil down to copy-paste-execute. It looked to me that Windows installation procedure described in https://github.com/kubernetes-sigs/krew calls for some automation, for which Chocolatey package is the perfect tool.

**Comment by ahmetb** [comment]
I suspect there’s room for a PowerShell script windows users can copy paste here, too. I just don’t know how it would look like. If you’re familiar with PS, consider contributing.

**Comment by RMcD** [comment]
I've done some work on a chocolatey wrapper here:
https://github.com/RMcD/chocolatey-krew/blob/master/krew/tools/chocolateyinstall.ps1

**Comment by corneliusweig** [comment]
@RMcD cool stuff. Can you detail a little about what is working and where more work is needed? Currently none of the `krew` maintainers actively works on Windows, so we cannot test your work ourselves. But we can think about linking to your repo as a community contribution. It would need some more documentation though :wink:
