### ISSUE TITLE
Trouble with bash 3.x

### ISSUE THREAD

**Issue by axklim** [kubernetes-sigs/krew#172]
I have some trouble with OSX 10.14.4 because there is bash 3.x by default and has not built in command mapfile. https://github.com/bminor/bash/blob/bash-4.0/CHANGES#L573
I repaired it with `brew install bash` :)

https://github.com/kubernetes-sigs/krew/pull/171

**Comment by ahmetb** [comment]
```
(
  set -x; cd "$(mktemp -d)" &&
  curl -fsSLO "https://storage.googleapis.com/krew/v0.2.1/krew.{tar.gz,yaml}" &&
  tar zxvf krew.tar.gz &&
  ./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install \
    --manifest=krew.yaml --archive=krew.tar.gz
)
```

this command doesn't have mapfile.

Where did you come across it?

**Comment by axklim** [comment]
Ohh sorry, it's my mistake. I said about plugin view-secrets: https://github.com/ahmetb/kubectl-extras/blob/master/view-secret/view-secret.sh#L28
Should I move the ticket to view-secret repository ?

**Comment by ahmetb** [comment]
Yes please. It doesn’t say view-secret  in your issue. 
/close
