### ISSUE TITLE
Validate correct license boilerplate header

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#173]
There are a few files that still have licence  _Copyright 2018 Google LLC_, where it should say _Copyright 2019 The Kubernetes Authors_.

There should be a test which asserts that every file has the correct copyright notice. And every file should have one.

**Comment by ahmetb** [comment]
/kind cleanup

> There should be a test which asserts that every file has the correct copyright notice. And every file should have one.

Some other Kubernetes repos have a script that checks for the correct license header in their respective `hack/` directories. I think the current solution is to copy the script. Not sure if any better solutions exist.
