### ISSUE TITLE
Switch linter to golangci-lint

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#174]
Krew currently uses gometalinter. Gometalinter has been deprecated by his author in favor of `golangci-lint`, therefore krew should switch to the better linter.

**Comment by ahmetb** [comment]
SGTM. This decision predates the project being accepted into kubernetes-sigs. If there's anything that prow or other test-infra components offer here, happy to accept.

I don't think we actually caught anything with gometalinter’s linters so far.
