### ISSUE TITLE
Install example for fish shell

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes-sigs/krew#179]
Currently there is only an example for bash and zsh. There should be an example for fish shell as well.

**Comment by mmelcot** [comment]
See: https://github.com/vorburger/krew/blob/patch-1/site/content/docs/user-guide/setup/install.md#fish-shell-fish

**Comment by ahmetb** [comment]
@mmelcot can you explain what we're seeing there after 3 years of silence on this thread? If there are any problems or a better way to do this, I appreciate it you open a new patch or issue.
