### ISSUE TITLE
Compile with vanilla `gc` instead of `gox`

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#180]
Maybe I'm wrong, but it seems that the cross-compiler `gox` is used for historical reasons. I think this was necessary, because initial builds were done with `CGO_ENABLED=1`, but this has been disabled in #86.

To simplify the toolchain, I propose to switch to the vanilla `gc` compiler. This is usually done with a Makefile instead of shell scripts. I'd volunteer to write one :)

Using this opportunity, we could also bump the go version to 1.12.

**Comment by ahmetb** [comment]
I think there's nothing inherently wrong with gox, it just makes it easy to compile for multiple platforms with a good naming scheme without worrying about writing a Makefile.

If you have time, feel free to prototype something.

**Comment by ahmetb** [comment]
For the record this is what gox does (minus the proper quoting since this is `ps aux` output):

```
go build -gcflags  -ldflags -w -X sigs.k8s.io/krew/pkg/version.gitCommit=80b6485     -X sigs.k8s.io/krew/pkg/version.gitTag=v0.2.1-23-g80b6485 -asmflags  -tags netgo -o /Users/ahmetb/workspace/gopath-sigs-k8s-io-krew/src/sigs.k8s.io/krew/out/bin/krew-windows_amd64.exe sigs.k8s.io/krew/cmd/krew
go build -gcflags  -ldflags -w -X sigs.k8s.io/krew/pkg/version.gitCommit=80b6485     -X sigs.k8s.io/krew/pkg/version.gitTag=v0.2.1-23-g80b6485 -asmflags  -tags netgo -o /Users/ahmetb/workspace/gopath-sigs-k8s-io-krew/src/sigs.k8s.io/krew/out/bin/krew-linux_arm sigs.k8s.io/krew/cmd/krew
go build -gcflags  -ldflags -w -X sigs.k8s.io/krew/pkg/version.gitCommit=80b6485     -X sigs.k8s.io/krew/pkg/version.gitTag=v0.2.1-23-g80b6485 -asmflags  -tags netgo -o /Users/ahmetb/workspace/gopath-sigs-k8s-io-krew/src/sigs.k8s.io/krew/out/bin/krew-darwin_amd64 sigs.k8s.io/krew/cmd/krew
```

and as you can see in the script we call it with `CGO_ENABLED=0` so there's that.

I don't think there's any magic in this, we could potentially eliminate the dependency and add these flags ourselves in a for loop.

But `gox` actually effectively uses multiple CPU cores to parallelize builds, a capability that we’d lose in a bash script.

**Comment by corneliusweig** [comment]
> But `gox` actually effectively uses multiple CPU cores to parallelize builds, a capability that we’d lose in a bash script.

That's why I would write a Makefile instead of a shell script

**Comment by ahmetb** [comment]
Interesting, I didn't know Makefiles could do parallelization.
We might just take a leap and move to Bazel as well. I'm not sure how would it fare.

**Comment by corneliusweig** [comment]
> Interesting, I didn't know Makefiles could do parallelization.

You need to specify how many cores though (`make -j8`).

I haven't used bazel, so I don't know either. Another tool frequently used is goreleaser. Would that be an option too?

**Comment by ahmetb** [comment]
Truth is, we don't really need a tool right now, as in nothing is broken or unidiomatic. `gox` is fairly widely used as it has stuff like automatically determining the number of cores and inserting the idiomatic static linking flags.

I'm tempted to think we don't really need to do anything for now, our established scripts have been doing the releases just fine.

**Comment by corneliusweig** [comment]
After seeing `gox` in action, I agree that it works just fine.
