### ISSUE TITLE
Useing helm install nginx-ingress krew can not find the deployment nginx-ingress-controller

### ISSUE THREAD

**Issue by wanghkkk** [kubernetes-sigs/krew#184]
Useing helm install nginx-ingress krew can not find the deployment nginx-ingress-controller

nginx-ingress-controller install as a daemonset.

[root@k8s01 ~]# kubectl -n kube-system get po 
NAME                                                              READY   STATUS    RESTARTS   AGE
dev-nginx-ingress-controller-2824d            1/1     Running   39         10d
dev-nginx-ingress-controller-lfpsh            1/1     Running   37         10d
dev-nginx-ingress-default-backend-846b9wqvv   1/1     Running   0          10d

[root@k8s01 ~]# kubectl -n kube-system get deploy
NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
dev-nginx-ingress-default-backend   1/1     1            1           10d

[root@k8s01 ~]# kubectl -n kube-system get ds
NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                    AGE
dev-nginx-ingress-controller   2         2         2       2            2           dev.example.cn/runingress=run   10d

[root@k8s01 ~]# kubectl ingress-nginx backends
No pods for deployment nginx-ingress-controller found in namespace default
[root@k8s01 ~]# kubectl ingress-nginx backends -n kube-system
No pods for deployment nginx-ingress-controller found in namespace kube-system

Versions:
krew 0.2.1
kubernetes v1.13.5

How to fix this,thanks!

**Comment by aledbf** [comment]
@wanghkkk please check https://kubernetes.github.io/ingress-nginx/kubectl-plugin/#common-flags
`--deployment dev-nginx-ingress-controller` is required because you are using a custom name

**Comment by ahmetb** [comment]
Please file this issue at the ingress-nginx repo, it’s not related to krew but to a specific plugin.
