### ISSUE TITLE
No error but krew not working: MacOS Mojave

### ISSUE THREAD

**Issue by shahnewazrifat** [kubernetes-sigs/krew#185]
My Krew installation succeeded on terminal (no error and says it was successful)

However, when I run
`kubectl plugin list`
`error: no plugins installed.`

As you can guess, none of the krew commands work either.
**OS: `MacOS Mojave`**
**git version 2.17.2 (Apple Git-113)**

Kubectl Version:
```Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.9", GitCommit:"3fb1aafdafa3d33bc698930095db1e56c0f76452", GitTreeState:"clean", BuildDate:"2018-03-12T16:20:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by corneliusweig** [comment]
Hi @shahnewazrifat, thanks for reporting this. This seems to be an installation problem. Can you explain a bit more, how you installed `krew`? In particular, could you also show the content of your $PATH variable?

**Comment by shahnewazrifat** [comment]
Hi @corneliusweig !
Thanks for the reply.

Here's the content of my $PATH variable

`/Users/shah/.krew/bin:/Users/shah/Library/Application Support/DevSpaces:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/opt/node@8/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

I installed using the command:
`(
  set -x; cd "$(mktemp -d)" &&
  curl -fsSLO "https://storage.googleapis.com/krew/v0.2.1/krew.{tar.gz,yaml}" &&
  tar zxvf krew.tar.gz &&
  ./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install \
    --manifest=krew.yaml --archive=krew.tar.gz
)`

Thanks!

**Comment by corneliusweig** [comment]
@shahnewazrifat could you also show your `kubectl` client version? This should also be reported when doing `kubectl version`. It has to be >=1.12.

**Comment by nammn** [comment]
@shahnewazrifat do you have a `~/$HOME/.krew` folder?

**Comment by ZeroDeth** [comment]
`export PATH="$HOME/.krew/bin:$PATH"`

**Comment by ahmetb** [comment]
Can you do these:

- kubectl plugin list
- where kubectl-krew
- tree $HOME/.krew

And send their outputs?
