### ISSUE TITLE
Proposal: Rename "krew remove" to "krew uninstall"

### ISSUE THREAD

**Issue by superbrothers** [kubernetes-sigs/krew#188]
krew has `install` command for installing a plugin. On the other hand, for uninstalling a plugin, krew has `remove` command, not `uninstall` command. This is not intuitive and I often get confused.

Therefore I propose that `krew remove` is renamed to `krew uninstall`. 

```
$ kubectl krew uninstall -h
Uninstall one or more plugins.

Example:
  kubectl krew uninstall NAME [NAME...]

Remarks:
  Failure to uninstall a plugin will result in an error and exit immediately.

Usage:
  krew uninstall [flags]
```

We can also keep `krew remove` as an alias to `krew uninstall`.

FYI: In Helm 3, `helm delete` command has been renamed to `helm uninstall` command.

**Comment by corneliusweig** [comment]
+1 if we keep the alias

**Comment by ahmetb** [comment]
Yeah, we can rename and make "remove" an alias instead.

**Comment by superbrothers** [comment]
Thank you for your comments. So I’ll create a PR.
