### ISSUE TITLE
Show stargazers count for plugins hosted on github

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#192]
The number of stars on GitHub shows how many people found a plugin useful. It certainly is no fully adequate measure of quality, but it does have its value.

I would find it quite useful to see the number of github stars for those plugins hosted on github. There are also nice go bindings for the github api so it will not be complicated to set up. The only downside is that the number of unauthenticated api requests is limited to 50 per hour. So it should not be added to the `krew search` output, which potentially shows many plugins. On the other hand the `krew info <plugin>` command should be safe.

WDYT? Is that useful?

**Comment by ahmetb** [comment]
I am currently -1. Stars isn’t a good metric. 

Do you think users would install and try “top starred” plugins as opposed to what they actually need?

**Comment by corneliusweig** [comment]
Well I think it's not easy to tell from a short description if a command will be really useful. If a project has a lot of stars it's at least a hint that a lot of other people not only tried that plugin, but even thought it was good.

I certainly don't think that stars is a perfect solution. But it's a hint which we could provide. Or what is your major concern against stars?

**Comment by ahmetb** [comment]
Posting to reddit, or HN can get you 1000 stars easily. It doesn't necessarily mean the plugins are vetted, or they're actively kept up-to-date. Even freshness is not a good metric (nothing wrong with a plugin that's not updated for 2 years as long as it does the job). 

Moreover, people can host multiple plugins in the same repo (we don't have anything blocking that) (and I have the kubectl-extras repo myself), so that wouldn't be the appropriate representation of all plugins in that repo either.

**Comment by corneliusweig** [comment]
Yeah, maybe not such a good idea after all.

Nevertheless, let's keep this issue open for a while in case other people want to tune in.

**Comment by ahmetb** [comment]
I've sort of always wanted to a semi-automatically generated page on krew-index repo (that's in markdown) that shows the plugins as a table (name + shortDescription). If we had a tiny script to generate a plugins.md file for krew-index repository, we could use https://shields.io to embed star counts.

**Comment by corneliusweig** [comment]
That's a fabulous idea! That way we keep `krew` simple and slim :+1:

I'll go ahead and open an issue in `krew-index`.
