### ISSUE TITLE
Krew info for multiple plugins is hard to read

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#196]
When calling `krew info` for multiple plugins, the info for all plugins is concatenated without any separators. This makes the output hard to read, for example
```
krew info konfig konfig
```

I see two options:
- forbid passing multiple plugin names and expect exactly one plugin name
- separate the info yamls with "\n---\n" which is more or less k8s standard.

Besides, repeating a plugin prints the info twice. Should that be allowed? This is an absolute edge-case and maybe not worth any extra logic.

**Comment by ahmetb** [comment]
I wasn’t aware it accepted multiple arguments. Feel free to remove the support for multiple args.
