### ISSUE TITLE
hack/run-in-docker.sh: build krew outside the container and mount

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#205]
re: #201 
This way we don't have to replicate `go build` command inside the dockerfile, which could unintentionally diverge from how we build things with `hack/make-binaries.sh`.

Then we'd -v mount the krew binary inside the container.

Also I can easily run `hack/make-binaries.sh` outside the container and refresh the binary inside the container without having to re-run `hack/run-in-docker.sh` which rebuilds the image (takes time, disk space, loses shell history, container state etc.).

**Comment by corneliusweig** [comment]
/close
Fixed by #206
