### ISSUE TITLE
Remove obsolete TODO items

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#213]
The code contains quite a few open TODO items. I think it would be worth going through that list and remove stale or completed items. Where appropriate, other items should IMHO be moved into github issues for better visibility.

That should ideally be done by @lbb or @ahmetb who know more about those TODO items.

----

Examples with probably pointless TODO items: `pkg/index/types.go`, `pkg/index/validate.go`

**Comment by corneliusweig** [comment]
@ahmetb There are 6 todo items remaining. Would you agree if I opened issues for those instead of todo comments?

@lbb can you answer the question in `pkg/installation/upgrade.go:109`:

> TODO(ahmetb,lbb) is this part implemented???

**Comment by ahmetb** [comment]
I don't think so, it seems to be a dead code. :|
Hopefully actually using the receipts will help us track down these pieces more.

I wouldn't focus on closing the TODOs, I think most of them are left in the code as a potential future improvement that isn't critical atm.
