### ISSUE TITLE
hack/verify-code-patterns.sh: fails locally

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#217]
When I run `hack/verify-code-patterns.sh` from the root (at d6629aa) it fails with exitcode=1 without any output. This looks bad in `hack/run-tests.sh`.

Throwing a `set -x` shows some stuff:

```
hack/verify-code-patterns.sh
++ find . -name '*_test.go' -not -path './vendor/*' -print0
++ xargs -0 grep -En 'ioutil\.TempDir'
++ [[ 1 == 123 ]]
+ out=
```

So it looks like for some reason on my shell, exitcode is 1, and not 123.

Although, when I run it on zsh directly, it works.

```
$ find . -name '*_test.go' -not -path './vendor/*' -print0 | xargs -0 grep -En 'ioutil\.TempDir' || [[ $? == 123 ]]; echo $?
0
```

I think we need a cleaner solution that doesn't do `[[ $? == 123 ]]`.

**Comment by ahmetb** [comment]
Oh also this script should use `${SCRIPTDIR}/..` to specify the source directory to `find`.

**Comment by ahmetb** [comment]
this returns 123 in zsh and 1 in bash:

```
find . -name '*_test.go' -not -path './vendor/*' -print0 | xargs -0 grep -En 'ioutil\.TempDir' || echo $?
```

weird.

**Comment by corneliusweig** [comment]
We had some discussion about how to implement this in https://github.com/kubernetes-sigs/krew/pull/191#discussion_r289179478 . Given that the current solution is not reliable on all platforms, let's use your suggested solution from there.
