### ISSUE TITLE
Custom messages after index upgrade

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#219]
It would be really nice to have a way to distribute important or useful information after index updates. For example, we could
- recommend `krew upgrade` if some krew internals changed (like install receipts)
- advise to upgrade plugins with critical fixes
- give additional migration instructions if it should be necessary
- highlight new `krew` features

I imagine something similar to the post-push hook in github which presents a link to create a PR from the pushed branch.

---

One way to achieve this would be to maintain an additional `MESSAGES` file in the `krew-index` repo which is fetched behind the scenes and dumped to stdout on exit.

WDYT?

**Comment by ahmetb** [comment]
Good idea in theory, but this proposal sounds like 2-3 features mashed up together.

I would currently treat this as a nice-to-have some point down the line and focus on getting the core machinery right and addressing the needs in the plugin ecosystem first.

/priority awaiting-more-evidence


> * recommend `krew upgrade` if some krew internals changed (like install receipts)

this is likely a special implementation where pluginName == "krew".

> * advise to upgrade plugins with critical fixes

this definitely needs a separate design (what's critical, and how to specify it)

> * highlight new `krew` features

again, a special case where pluginName == "krew"

**Comment by corneliusweig** [comment]
First, you are of course right that there are other important features for krew. However, if we have such a mechanism, we can highlight those new features for existing users and thus promote the overall adoption of krew. If krew is feature-complete there's no longer any point in implementing such a highlight mechanism :)

I think it's a good idea to have plugin-specific important messages. Maybe the plugin manifest is the right place for such messages. There could be a section with messages that are shown depending on the installed plugin version. That way, it would also be clear that such messages are the responsibility of plugin authors.

**Comment by ahmetb** [comment]
Looking at the list again, I don't think almost any of these aren't done in any package managers at all. So they would be definitely cutting edge stuff. But they increase the code complexity (and package maintenance) a bit too. We can revisit later.
/kind feature

**Comment by corneliusweig** [comment]
/remove-lifecycle stale
I think this will gain some more relevance with multi-repo.

**Comment by corneliusweig** [comment]
After re-thinking this, I'm no longer convinced this is such a great idea.

If every plugin gets to show post-install messages, this will simply invite (too) frequent use, so that users would not read those messages anyway.

So let's not consider this for now.
