### ISSUE TITLE
hack/run-integration-tests: runs all tests

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#224]
hack/run-integration-tests.sh hsa `go test -v ./...`, that's why it's running all  tests.

This must use `${SCRIPTDIR}/../test`. And ideally we should rename `./test` to `/.integration_tests`.

**Comment by corneliusweig** [comment]
Go caches test results, so that every re-executed test should be fast. Or are you worried more about duplicated test results in the CI output?

**Comment by ahmetb** [comment]
I mean the script's filename says one thing, it does another thing. :) That's the main problem.
