### ISSUE TITLE
test: rename dirs/files to make integration tests clear

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#229]
/kind cleanup 

Right now we have paths like:

- test/
  - ./krew.go &larr; unclear what it contains
  - ./krew_test.go &larr; unclear what it contains

which don't indicate that they're integration tests. I'd prefer we have something like this where we have a clear separation:

- test/
  - testutil.go
  - integration_tests/
    - install_test.go
    - info_test.go
    - uninstall_test.go
    - version_test.go

so that we can more clearly do:

    go test ./test/integration_tests/...

we can also directly call the root folder `./integration_tests` and put all the files there.

**Comment by corneliusweig** [comment]
:+1: from me. I'd prefer if the root test folder be called `integration_test`, so it is clear to everybody what's in there. And I would prefer a nested structure, though flat is also fine.

**Comment by corneliusweig** [comment]
/reopen
Because we still need to split the test file into smaller bits.
