### ISSUE TITLE
Migrate krew home to add install receipts for installed plugins

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#232]
After #195, `krew` adds install receipts when installing new plugins. After that, the subcommands `list`, `uninstall`, and `upgrade` should make use of the install receipts instead of scanning the `$KREW_ROOT/bin` folder.

This issue is to discuss the logic how the migration can be done.

---

This could work:

1. Detect if the krew home was migrated before. This can be done by 
    - _not_ creating the `$KREW_ROOT/receipt` folder by default and see if it exists
    - look for a special file in `$KREW_ROOT/layout_version` or similar
2. If the krew home was migrated before, do nothing.
    If the krew home has not been migrated, print a warning to run `krew upgrade` and quit.
3. When `krew upgrade` is run, upgrade all plugins. For plugins that don't need upgrade, save the manifest in `$KREW_ROOT/receipt`.

After that, the receipt folder will be up to date.

The command `krew upgrade` is necessary, as it is impossible to find out the plugin manifest when the installed version lags behind the current manifest version. This as a big downside: the logic for `krew upgrade` cannot be migrated to work with install receipts anytime soon. Or at least `krew upgrade` needs to preserve the scanning mode for some time.

WDYT?

**Comment by ahmetb** [comment]
I'll think about this for a bit. I'm erring on the side of "breaking everything" for now since:

1. We're pre-1.0  (breaking is ok) and we don't have a lot of users (I wish we had data)
2. We have to break everything for multi-index support anyway, and we could use this chance to implement and ship that, too, so that we break users less often.
3. We haven't made any releases for a while so I think it's acceptable to break.
4. "Migration code" is usually nasty: It's hard to test, it gets forgotten and rots over time, and there are usually many edge cases.

**Comment by corneliusweig** [comment]
I do agree about 2 and 4. But I don't agree at all on 1 and 3 for one reason: we have no way to notify our users that they need to reinstall/migrate krew. (or do we?)
If we break, many users will think `krew` is buggy (rightfully so) and may discontinue using it.

We should not take that lightly.

**Comment by ahmetb** [comment]
In that case, I'll recommend the following:

1. assume we have a method `F` for detecting whether the migration has happened or not. (TODO)
2. somewhere on initializing krew (all commands), we use `F()` to detect migration has happened.
    - if yes: continue.
    - if not, tell user a message telling them how to upgrade<br/> `you need to perform a migration to continue using krew. run: "krew system receipts-upgrade"`
3. implement a hidden command to perform migration: In this case, most likely this is like:
    - find list of installed plugins (without using krew cmd)
    - uninstall these plugins (without using krew cmd, somehow)
    - shell out to `krew install` to install plugins (figure out a way to bypass the migration check introduced Step 2 above)
4. after 3 months or so, delete the code changes in Step 2 and Step 3.

**Comment by corneliusweig** [comment]
Sounds like a good plan. But I would keep the migration code around for basically as long as it does not cause extra maintenance effort.

Maybe one thing that we should keep in mind: many plugins are quite large (>20MB). For people with many plugins on slow connections the migration will take very long. We should therefore print progress messages, so that users don't abort the migration process.

**Comment by ahmetb** [comment]
Honestly I still think breaking everyone is ok due to low user count. 
However this time when we break, we’ll be leaving it in a bad state that they cannot install plugins as they’re already actually installed.

**Comment by corneliusweig** [comment]
Well if we break the `krew` home, then let's also clean up the store layout. For example, for `konfig` the plugin is currently stored at
`store/konfig/c86a33e9ba2c8f739d96aa19c94d14f10b15e1c6424f693ec2e475aed3161b0a/konfig-krew`

But with plugin receipts we can switch to semantic versioning and store the plugin at
`store/konfig/v0.2.1/konfig-krew`
instead. This will be more natural for users and will also correct a superseded design decision.

WDYT?

**Comment by corneliusweig** [comment]
Btw, does https://storage.googleapis.com/krew/ offer download counts? I know that github does for release assets. That might give some idea about the user basis.

**Comment by corneliusweig** [comment]
I think there's even a better option. We can look at the download the clone statistics for `krew-index` like so (https://developer.github.com/v3/repos/traffic/#clones):

```bash
curl -sSLH 'Accept: application/vnd.github.v3+json' \
   "https://api.github.com/repos/kubernetes-sigs/krew-index/traffic/clones"
```

This will show us an indicator about the number of active krew users. The only problem is that we need a user with push access for `krew-index`.

**Comment by ahmetb** [comment]
> Btw, does [storage.googleapis.com/krew](https://storage.googleapis.com/krew/) offer download counts? I know that github does for release assets. That might give some idea about the user basis.

Unfortunately we didn't enable telemetry pipeline for this, as the red tape was way too much.

Current [clone graph](https://github.com/kubernetes-sigs/krew/graphs/traffic) shows ~300 clones/day which I don't think is accurate (probably some tooling clones it + travis CI). We get ~100 visitors/day to the repo, and it's unlikely all of them are installing it:

![image](https://user-images.githubusercontent.com/159209/60830504-376de680-a16c-11e9-9e35-eb173b92cd6c.png)

**Comment by ahmetb** [comment]
> Well if we break the `krew` home, then let's also clean up the store layout.

Yes. We should implement forced semver first (#166), then.

I wonder we should even introduce the multi-index mode, too. This might be a few too many things for v0.3 (we didn't have a release since forever).

Multi-index effort will change the `index/` and `store/` directory hierarchy. If you have time, let's take a stab at either #166 or my recommendation above https://github.com/kubernetes-sigs/krew/issues/232#issuecomment-507481767 for a migration command.

**Comment by corneliusweig** [comment]
I'm going to take a stab at the krew-home migration. What do you think would be a good method to determine if the krew home needs a migration?
My original idea was to not create `$KREW_HOME/receipts` by default and to take this as a sign for an outdated repository. This will work ok-ish, but new users will have to run the migration as their very first action, resulting in a pretty bad UX. Any thoughts about a better approach?

**Comment by ahmetb** [comment]
I see you already did a PR. Too quick! :)
Let's finalize the proposal here first.

> My original idea was to not create `$KREW_HOME/receipts` by default and to take this as a sign for an outdated repository.

This is suboptimal for me. It creates separate code path for migration, which we like to avoid.

> What do you think would be a good method to determine if the krew home needs a migration?

I think a good indicator is this: there are directories inside `store/` but there are no yamls inside `receipts/`.

That said, maybe we should implement "support for multiple indexes" before #249 since that will also change the directory structure _drastically_.
