### ISSUE TITLE
Krew upgrade needs integration test

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#233]
Krew upgrade is currently not covered by integration tests, because it requires a more advanced test setup. What the integration test should do:

- Install an old plugin version
- Verify that the old version is installed
- Run `krew upgrade`
- Verify that the new version is installed

The tricky part is to reliably get two plugin versions in the test. One way to do this, could be to install a fixture version with the `--manifest` option. To verify that the original version and the eventual version are actually different, one could take the hash of a file that must change during upgrade.

**Comment by ahmetb** [comment]
Yeah, we'd need `--manifest` because `krew upgrade` calls `krew update` internally, which would undo if you were overwriting the manifest file in the index.

We'd just need to vendor the old file into testdata/ and keep it up-to-date (compliant with the current version).
