### ISSUE TITLE
Migrate to go modules

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#234]
Now that kubernetes client-go actually supports Go modules, it should be possible and it can simplify the dependency management (i.e. adding new deps) just a little bit.

That said, it complicates the Travis CI builds, as travis still sets GOPATH and requires us to update our build command to make sure it uses vgo.

/kind cleanup

**Comment by corneliusweig** [comment]
I looked into this a while back. It's not just switching to go modules, but also switching away from gox, which is still stuck on go 1.10 and has no modules. So maybe tackle this after #180.

**Comment by ahmetb** [comment]
🤔 🤔
I use go modules and `gox` together in https://github.com/grpc-ecosystem/grpc-health-probe . Are you sure?

**Comment by corneliusweig** [comment]
:bulb: It seems I had a completely wrong picture of how gox works. Apparently, it is just a nice wrapper around whatever go compiler is installed. And it forwards the `-mod` flag, so modules just work. Thanks for this enlightenment :)

**Comment by ahmetb** [comment]
/assign
I'll take a look at this.
Currently I have a working prototype, but `go get [...]/gox` causes `go.mod` to be modified, and hence the build env contaminates, the binary is stamped as `...-dirty`. I asked on: https://stackoverflow.com/questions/56842385/using-go-get-to-download-binaries-without-adding-them-to-go-mod
