### ISSUE TITLE
Proposal: create a tool for easily bumping up plugin versions in manifest files

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#239]
/kind proposal

I assume many plugin authors today go through the following steps if they have a new plugin today:

1. `git pull`
2. `git checkout -b BRANCH`
3. open $plugin.yaml for editing
4. bump `version:` field
5. foreach platform:
   a. update the `url` property
   b. update the `sha256sum` property
6. (optionally) `krew install --manifest $plugin.yaml`
7. `git commit`
8. make a PR

It's cumbersome, given it's pretty much `url`/`sha256sum`/`version` fields updating most of the time.

I think we can update Steps 3-6 with a separately distributed tool, called something like `krew_bump_plugin_version`.

## Strawman design

- Devs can install it and just specify which plugin they want to update.
- The tool detects the github repo from the url
- The tool finds the latest stable release (would be good if we enforced semver #166)
- The tool updates `version` field of the manifest (using regexp, to save formatting?)
- The tool updates the `url` field of each platform (using regexp, to save formatting?) by matching to occurrences of the version and replacing them.
- The tool computes the `sha256sum` of each new url and replaces those accordingly too (unclear to me how we can determine which sha256sum belongs to which `url`, maybe we can figure out by parsing and matching `{checksum,url`} pairs ahead of time).
- (optional) Test installation for all platforms in a temp dir, by configuring `KREW_ROOT`, like `validate_krew_manifest` tool does (maybe just invoke that).

## Conclusion

Homebrew has this tooling `brew bump-formula-pr`.

I think it would be a good starter project for a new contributor, and I think our developer ecosystem could vastly benefit from that.

**Comment by marccampbell** [comment]
@ahmetb I like this idea a lot and have a couple of follow up questions from the strawman design:

1. This assumes github.com and using releases to distribute. A quick scan shows that this is currently accurate for most current krew plugins. But nothing in the manifest seems to require this -- what about folks using Gitlab or someone who is uploading a .tar.gz to S3? I'm not sure if the S3 option is even in the scope of this tool

2. Do you think this is best as a completely separate tool or a subcommand of krew? If it's a separate tool completely, would it make sense to use krew as the package manage for this tool, to allow easy distribution and updates across various operating systems?

3. The semver issue is closed. But GitHub API has a /releases/latest method which returns the latest by date. I think this would be sufficient?

**Comment by ahmetb** [comment]
> * This assumes github.com and using releases to distribute. A quick scan shows that this is currently accurate for most current krew plugins. But nothing in the manifest seems to require this -- what about folks using Gitlab or someone who is uploading a .tar.gz to S3? I'm not sure if the S3 option is even in the scope of this tool

Yeah krew doesn't know anything about GitHub, but since most plugins use GitHub, this new tool would recognize GitHub for ease of use.



> 2. Do you think this is best as a completely separate tool or a subcommand of krew?

Separate sub-command would be ideal. It can even be a separate repo. We can also distribute this as a kubectl plugin through krew (that only developers would need to install).

> 3. The semver issue is closed. But GitHub API has a /releases/latest method which returns the latest by date. I think this would be sufficient?

Yes, semver issue is fixed (although we have not made a release with it, yet). Now all krew plugins must use semver version fields which is required.

This tool would use the GitHub API you mentioned to find the newest _stable_ releases.

**Comment by marccampbell** [comment]
This makes sense to me, and those decisions feel like they limit the scope enough to get a first version created without a lot of effort. What do you think the next steps are to get started on this?

**Comment by ahmetb** [comment]
You can start creating a prototype in your repo as a hidden krew subcommand.

Alternatively, you can open an issue to sketch a design (flags, behavior, usage etc) and we can iterate on it before you start coding as well.

**Comment by grzesuav** [comment]
Hi, there is a general purpose tool for that, which is pretty extensible : https://github.com/renovatebot/renovate/ 
I would suggest to try to extend it. I do not know in details how it work, but generally there are two parts to write :
* provider - some source of artifacts and versions
* detector - part which scans for file patterns (like `plugin` files) and is able to extract version used here

Having those two, renovate compares the version and proposes a PR to update once newer version is found. It is mature tool and used across many companies and os projects

**Comment by ahmetb** [comment]
Relevant discussion also at https://github.com/kubernetes-sigs/krew-index/issues/270 let's continue there.

**Comment by ahmetb** [comment]
I think we're significantly solving this problem with https://github.com/rajatjindal/krew-release-bot. Plugin authors just need to install a GitHub action that pings an endpoint, which uses a bot account to make a PR on behalf of the plugin owner, with the plugin manifest template checked in to the repo.

**Comment by ahmetb** [comment]
I think this is pretty solved at this point with `krew-release-bot` linked above. Thanks @RajatJindal for his continued work and support in this area.
/close
