### ISSUE TITLE
Status column in `krew search` is hard to read

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#250]
`krew search` gives a list of all plugins and adds a status column, which reads for me:
```
access-matrix    Show an access matrix for server resources         installed
bulk-action      Do bulk actions on Kubernetes resources.           available     
ca-cert          Print the PEM CA certificate of the current clu... installed
change-ns        View or change the current namespace via kubectl.  available
config-cleanup   Automatically clean up your kubeconfig             available     
cssh             SSH into Kubernetes nodes                          available
```
Although there's nothing wrong with the last column, it's still rather hard to read/parse because the status `available` and `installed` have the same length.

Can we find a better pair of status descriptions, so that it becomes easier to discern? Probably the unicode characters :heavy_check_mark: :x: are no option because they do not print well on all terminals.

**Comment by ahmetb** [comment]
Agreed. We kept the text because icons alone are harder to understand. For example, would ❌ mean `unavailable` or `not installed`? (To me it looks like "unavailable".)

If we can find 3 non-emoji characters that are good for {unavailable, available, installed} statuses, I'm ok with augmenting the STATUS with icons.

**Comment by corneliusweig** [comment]
I also don't think that we can find appropriate symbols to convey this specific meaning. My issue is mainly that `available` and `installed` have the same length and are hard to discern.

On the other hand, I would argue that `unavailable` is also not a good status, because it does not say why. Besides, who cares if a plugin is available for another platform, so why show that at all? Maybe we should skip unavailable plugins altogether. And then, we could think about re-labeling the last column to `INSTALLED` and use `yes`/`no` for the status instead (or the symbols, but that is another question).

**Comment by ahmetb** [comment]
> Besides, who cares if a plugin is available for another platform, so why show that at all?

This is not a good idea for plugin discoverability. This would convey to a Windows user that there are very few plugins available, whereas if they switch to a WSL shell they can actually install Linux plugins. 

We can reword this like `unavailable on $GOOS` and still show on the INSTALLED column.

**Comment by corneliusweig** [comment]
That sounds good.
