### ISSUE TITLE
Installation for windows says --source, it should be --manifest

### ISSUE THREAD

**Issue by lehno** [kubernetes-sigs/krew#254]
The docs for windows installation is telling users to use --source, it should be --manifest.
Also users must runs with admin privileges

**Comment by ahmetb** [comment]
Thanks for reporting. Do you mind making a PR for the doc issue?
Also why do you think it requires admin privileges? I can’t seem to understand myself why that would be required. 
/kind bug

**Comment by ahmetb** [comment]
Can you please link to the page you saw? I just grepped the entire repo, there's no reference to any `--source` occurrence.

**Comment by lehno** [comment]
I cant find it anymore, I wonder I was reading a fork readme that looks exactly like here with wrong info. You can close this ticket. Thanks
