### ISSUE TITLE
Consider updating official kubectl plugins doc with krew

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#256]
Now that Krew is officially under kubernetes-sigs umbrella, it might be worthy of our time to update the Kubectl Plugins documentation at https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/ so that developers creating plugins know an easy way to package and distribute them.

/kind documentation
/priority P2

**Comment by corneliusweig** [comment]
Yes, we should definitely do that! :100:

Do you already have an idea what you want to write? Otherwise I could give it a try.

**Comment by ahmetb** [comment]
I think I'll discuss it in the SIG CLI meeting first and get the SIG's blessing this week (on Wednesday) first.

**Comment by ahmetb** [comment]
I have a PR about this at https://github.com/kubernetes/website/pull/16322.

**Comment by corneliusweig** [comment]
This can be closed now, I believe?

**Comment by ferhatelmas** [comment]
Ping to close?

**Comment by ahmetb** [comment]
/close
thanks!
