### ISSUE TITLE
Use plugin description in search command

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#26]
`kubectl plugin search certificate` is not bringing up ca-cert which has the word in its description.

/priority P2
/priority backlog

**Comment by ahmetb** [comment]
@orthros is taking a stab at this.

**Comment by nammn** [comment]
If its still free, i would like to take a look at this @ahmetb

**Comment by ahmetb** [comment]
@nammn Feel free to work on a patch.

**Comment by nammn** [comment]
great, i'll work on this patch 👍

**Comment by fabiand** [comment]
Any update on this one?

The new virt plugin is also affected by this (not found if searched for kubevirt).

**Comment by ahmetb** [comment]
/remove-lifecycle rotten

We'll probably get to it at some point. It's not a super high priority since most users probably find plugins through some github repo so they know its installation command.

**Comment by fabiand** [comment]
Ok. Would you be open to a PR?

**Comment by ahmetb** [comment]
We already had #150 but happy to give it another try. This might require some experimentation. Text search isn't a simple problem, and we might need to sanitize the input a little bit (e.g. to remove line breaks, figure out how to treat urls in descriptions and so on).

**Comment by danielpacak** [comment]
The same applies to the `who-can` plugin which does some reverse lookup in RBAC permissions. It won't show up when I type `kubectl krew search rbac`.

Did you consider adding the `keywords` property to the manifest spec? Something similar to what npmers are doing? https://docs.npmjs.com/files/package.json#keywords

```yaml
name: "who-can"
keywords: ["rbac", "authorization"]
```

**Comment by corneliusweig** [comment]
I'm unsure what to do with this issue. On the one hand #150 was closed long ago, but a search in `description` seems to be something that many users miss.
So I'd like to gather more input as to how an improved search functionality would be used. Let's put the technical details aside and just create a wish-list of workflows.
