### ISSUE TITLE
minor: duplicate test object cleanup

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#270]
Looks like both pkg/receipt/receipt_test.go and pkg/info/info_test.go have this in-memory plugin + pluginName definition.

It would be good to dedupe this in a testdata/sampleplugin_test.go (exported identifier) and import here, I think.

/kind cleanup

**Comment by corneliusweig** [comment]
Note: there are two todo items labeled with the issue number that should be addressed in this PR.
