### ISSUE TITLE
meta: create numeric priority labels in this repo

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#272]
It seems like https://github.com/kubernetes/kubectl has priority labels like
P0..P3. I need them very frequently and other options we have (backlog,
important-soon, important-longterm, critical-urgent, awaiting-more-evidence)
are not rankable (though they're still useful to indicate status).

We should consider taking a look at how kubectl repo gets them for better
project management.

**Comment by cblecker** [comment]
labels can be added via test-infra: https://github.com/kubernetes/test-infra/blob/7aef384140833379d3e72f33bc0bb9d10770aefe/label_sync/labels.yaml#L844-L852

**Comment by ahmetb** [comment]
Thanks @cblecker, I didn't know you were watching this repo, too! :) I'll add labels there.

Any ideas how the http://git.k8s.io/kubectl repo got the labels (like `priority/P0`) that are not defined in this repo? Do you think there was a manual process at some point.

**Comment by cblecker** [comment]
Yeah, likely manual. the label sync won't clobber labels it doesn't know about.

**Comment by scottilee** [comment]
@ahmetb I can take this. Are there any labels you want defined other than priority/P{0-3}? Also let me know if you have color preferences.

**Comment by ahmetb** [comment]
@scottilee thanks P0..3 is good. You can pick red..orange range of colors from https://flatuicolors.com or something similar.

**Comment by ahmetb** [comment]
/close
Thanks!
