### ISSUE TITLE
integration_test: test output checks rely on stderr

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#274]
I currently get this output from `krew search krew` command executed via `TestKrewSearchOne` test:

```
out/bin/krew-darwin_amd64 search krew
E0717 11:41:34.781625    2721 scanner.go:57] failed to load file "ingress-nginx", err: failed to parse plugin version: version string "0.24.0" not starting with 'v'
E0717 11:41:34.798655    2721 scanner.go:57] failed to load file "ssh-jump", err: failed to parse plugin version: version string "0.1.0" not starting with 'v'
NAME  DESCRIPTION                           INSTALLED
krew  Package manager for kubectl plugins.  yes
```

technically the cmd succeeds (but it prints some warnings to stderr) via `glog.Errorf`.

however these messages in stderr are picked up in the test and therefore fails the test.

ideally any time we check output lines, we should only take stdout into action, as we might use `stderr` for warnings like deprecation notices or other random things.

/kind cleanup

**Comment by corneliusweig** [comment]
But that also means we lose the chance to find unexpected warnings early-on by the CI. So I'm currently -1 on this.

**Comment by ahmetb** [comment]
I don't think warnings are functionality that can be relied upon, though.
We can make this low priority to see if we hit it again.
/priority awaiting-more-evidence

**Comment by AndrewSav** [comment]
There are a few other scenarios when information messages on stderr is unexpected:

- When using krew in a TeamCity build `krew info` is being put to stderr which causes the TeamCity build fail
- When using krew as part of a PowerShell script, with redirected stderr, when PowerShell process stderr output from a command (this processing does not happen by default on console hosts, but in redirection scenarios and where there is no host) it also treat command that logs to stderr as a failure.

Both of the above are possible to workaround, but is a pain. I was wondering if there are scenarios actually seen in the wild, where this behaviour is actually desirable.

>But that also means we lose the chance to find unexpected warnings early-on by the CI.

Is not that putting tool developer needs before tool user needs? I think that should be the other way around ;)

**Comment by ahmetb** [comment]
> * When using krew in a TeamCity build `krew info` is being put to stderr which causes the TeamCity build fail

Hmm, these commands area meant to be used by humans, not CI systems to parse it.

If you are parsing command outputs in a headless environment, you need structured output format (like yaml, json), `krew info` is guaranteed to break. Please open an issue if you want to work with it.

**Comment by corneliusweig** [comment]
Besides, the point of this issue is not to print everything that is currently printed on stderr to stdout instead. The point was to ignore the output on stderr in integration tests.

**Comment by AndrewSav** [comment]
@corneliusweig, if you are saying this to clarify that for me, then thank you for the clarification ;)
