### ISSUE TITLE
Refactor all commands to determine they use plugin receipts

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#277]
I don't think we fully made a migration to fully rely on plugin receipts.

Last PR (#195) introduced "saving" plugin receipts during install/upgrade and cleaning them up during uninstall/remove. I'm not sure if other commands were covered.

This is a tracking item for making a pass on the code to make sure all commands (like info, list, upgrade, install, uninstall/remove) are using receipts. We should verify how these commands work under the covers by also reading the verbose output.

/priority backlog
/priority important-soon

**Comment by ahmetb** [comment]
@corneliusweig I think this is now completed?

**Comment by corneliusweig** [comment]
Yes, I just had another look and it looks all good. I even checked the log output.
There were a number of PRs regarding this migration: #195, #276, #278
/close
