### ISSUE TITLE
docs: Create "Plugin development best practices" guide

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#289]
I think it would be good to have a short list of plugin development best
practices that would make plugin developers' lives easier while developing
plugins for kubectl to be distributed on krew.

Some points this doc can talk about:

- use github for source hosting, releases
  - familiarize with semver.org
- use Go or another cross- & statically-compiled language for multi-platform
  support
- follow kubectl in terms of CLI design
  - show help messages when no args provided, and -h/--help.
  - consider including example usages in help message.
  - re-use functionality in k8s.io/cli-runtime printers, options in kubectl code
- naming best practices (link to naming-guide.md)

/kind proposal
/kind documentation
/priority P3
/area docs

**Comment by corneliusweig** [comment]
As far as I can tell, there is https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/ and https://krew.sigs.k8s.io/docs/developer-guide/develop/naming-guide/ which  cover everything apart from 

> - use github for source hosting, releases
>   - familiarize with semver.org

This section would also fit nicely into the "best practices" section.

**Comment by ahmetb** [comment]
Kubectl plugin development best practices is now documented at:
https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/
/close
