### ISSUE TITLE
Hide internal packages from external users

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#291]
https://godoc.org/sigs.k8s.io/krew shows that pretty much all our packages
are available for public consumption, despite we only use them in Krew. Perhaps
pkg/index and pkg/constants are exempt from this.

If there's a way to hide these, through something like "internal" go packages,
I'd be in favor of implementing it.

/kind cleanup
/priority P3

**Comment by corneliusweig** [comment]
We are doing what any other go project is doing. Why should we invest so much in hiding things? If somebody can find use in any of our packages, that's fine.

**Comment by ahmetb** [comment]
We're not investing so much, necessarily. It's definitely a good-to-have.

It's also not really the norm or best practice. You can see Go itself following the convention on nearly all CLI tools they distribute, marking most packages except APIs `internal`: https://godoc.org/cmd, https://godoc.org/cmd/compile ,... It's just not actively followed in kubernetes space.

> If somebody can find use in any of our packages, that's fine.

This is a bit like saying we should make all methods Exported. :) If something isn't part of your API, ideally you should not allow others to use it (for both their own good, and our own good). Most of our internal methods are very specific to us, and cannot be relied upon between releases.

**Comment by ferhatelmas** [comment]
Is it ok to move all packages into `internal` except `pkg/index` and `pkg/constants`? Are there any other packages good to keep as it is?
