### ISSUE TITLE
Configure linter for unused methods

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#292]
Every now and then, we do major refactoring that leaves unused methods behind.

It would be great to have a linter that can notify us about unused methods,
variables, constants. I suspect this is probably easier to configure with "unexported" methods,
variables etc. However, if there's a way to do this with "exported" methods,
variables etc, we should do it because now anything in this repository (sigs.k8s.io/krew/...)
is expected to be used in this repository. So if something is not referenced,
ideally it should be cleaned up.

/label good-first-issue
/priority P3
/kind cleanup

**Comment by corneliusweig** [comment]
Hmm.. I just tried configuring the `unused` linter for `golangci-lint` with
```patch
diff --git a/.golangci.yml b/.golangci.yml
index ff0bbe9..3a53d8c 100644
--- a/.golangci.yml
+++ b/.golangci.yml
@@ -5,6 +5,9 @@ linters-settings:
     # it's a comma-separated list of prefixes
     local-prefixes: sigs.k8s.io/krew
 
+  unused:
+    check-exported: false
+
 # options for analysis running
 run:
   # which dirs to skip: they won't be analyzed;
```

That setting reports a lot of false positives, which makes it impossible to use in the CI. Btw, the `unused` linter is active by default. However, it does not consider functions as unused, if they are used in tests. So if all tests are deleted, the unused function from #290 is correctly reported. So it seems that our current meta-linter cannot handle this as desired.

**Comment by ahmetb** [comment]
> So if all tests are deleted,

haha that's a bummer. :D They should totally have a flag to ignore usage in tests.

**Comment by ferhatelmas** [comment]
For a quick win, how about enabling `deadcode` and `varcheck` with `tests` flag?

**Comment by ferhatelmas** [comment]
Not very useful at the moment but there might be beneficial cases.

**Comment by ferhatelmas** [comment]
https://github.com/kubernetes-sigs/krew/issues/291 would be useful because packages under internal can only be used in the same repo. Otherwise, they are exported, linter won't complain to prevent false positive.
