### ISSUE TITLE
Consider adding a field to show notes when upgrading a plugin

### ISSUE THREAD

**Issue by marccampbell** [kubernetes-sigs/krew#305]
Currently, krew shows the caveats field on a new install. For users who already have the plugin installed, when they `krew upgrade` they see some information about the version and if the upgrade was available/failed/successful. Would krew be open to having a manifest field that shows a changelog or notes post-upgrade?

Ideally, upgrades would show a different notes than a new install because a new install shows docs and how to use. After upgrading, I would like to be able to show some notes about what's new in the newly installed version.

**Comment by ahmetb** [comment]
Thanks for bringing this up. I'm currently -1.

I'd say showing the changelog of packages is something even fully-fledged package managers avoid doing. If you follow pull requests on `krew-index` repository, most of them are stuff that don't ship major changes.

This primarily because plugins are supposed to do something very clearly and improve over time, and ideally not break the behavior for a long time (and must introduce breaking changes with deprecation notices shown in the CLI for a long time), just like kubectl does.

I think introducing such a changelog/notices flag would cause notices to remain in place as people would forget to remove them, and not to mention, version updates don't happen one at a time.

**Comment by corneliusweig** [comment]
Issue #219 is also related to this proposal.

Even though I raised #219, I'm no longer convinced this is a good idea. I can understand your desire to advertise new features. But this user-info introduces quite a bit of complexity in krew which only a few plugins would ever make use of.

@marccampbell have you thought about adding an upgrade note to your plugin itself? That way, you can show whatever is important, and you don't have to rely on krew for that.

**Comment by marccampbell** [comment]
We could add them to the plugin. That's a good idea, thanks.

I believe that Krew shows the caveats when installing, but nothing when updating, correct? I might be mistaken here. But I'm wondering about scenarios where my requirements have changed.  We can handle this in our own code, but then every plugin in the index will have a slightly different implementation.

I completely understand @ahmetb concerns and points. Based on that feedback, I'm wondering if a much simpler solution of including a version URL in the manifest is useful and more palatable? If a user upgrades a plugin, the krew plugin could complete the upgrade and show a Version Info: URL if one was specified?

The other approach is that this falls into the responsibility of plugin authors, not the package manager.

**Comment by corneliusweig** [comment]
We already offer the `homepage` field in manifests (although the current `krew` version does not display it yet). I think any user interested in the release notes will find its way from there.

Also, I may not understand your plan with the realease notes link yet. How would you solve the problem when a user has skipped a version?

**Comment by marccampbell** [comment]
I'm not looking for krew to provide any functionality around what happens when a user upgrades from 1.0.1 to 1.0.3, skipping a version in the middle. Having a URL that's displayed for a changelog would be nice addition.

A quick scan of the krew index, most packages set the Homepage to the git repo home (I do this too). My request here is to explore the willingness to add a Changelog URL to a package also. (This has evolved in this issue, but that feels like a good solution)

**Comment by ahmetb** [comment]
I recommend creating a new issue as "Introduce a changelogURL field in plugin manifest".

I still find this quite a bit redundant.For example, when you upgrade grep on your machine, do you read the changelog? As a plugin developer, it may seem tempting to you to create a changelog for people to read, but most users shouldn't be needing it. Think of this: How many times you’ve read the kubectl changelog?

**Comment by marccampbell** [comment]
Thanks @ahmetb. I'll close this one and do that.
