### ISSUE TITLE
Add a link to sample cli plugin repo

### ISSUE THREAD

**Issue by ferhatelmas** [kubernetes-sigs/krew#328]
As suggested at https://github.com/kubernetes-sigs/krew/pull/323#pullrequestreview-282335218

/kind documentation

**Comment by corneliusweig** [comment]
:+1: Somewhere in the vicinity of `docs/DEVELOPER_GUIDE.md` line 32 would fit nicely.

**Comment by chriskim06** [comment]
I can take care of this if its still needed

/assign
