### ISSUE TITLE
Consider enabling a shell formatter

### ISSUE THREAD

**Issue by ferhatelmas** [kubernetes-sigs/krew#329]
It seems more and more scripts are being added for different tasks.

Similar to having consistency in go, a formatter for shell could ensure it in scripts such as https://github.com/mvdan/sh

/kind cleanup
/kind proposal

**Comment by ahmetb** [comment]
Is that what intellij uses?

We informally use shellcheck. Also we’re pretty good at formatting already. When I run the shell formatter in IntelliJ, it made little to no changes.

**Comment by ferhatelmas** [comment]
> Is that what intellij uses?

I don't know but might be since quite popular.

> We informally use shellcheck

shellcheck is good but it does static analysis. shfmt is just a formatter like prettier vs eslint.

> When I run the shell formatter in IntelliJ, it made little to no changes.

That's good so if we integrate it, diff will be small(or zero). However, not having it enforced, anybody can easily introduce some code churn. 

I believe, it's better not to let it happen.

**Comment by ahmetb** [comment]
I'm supportive. If we can show the contributor nicely which part is failing or what's the diff after formatting, along with the command for them to reformat locally, that would work.

**Comment by ferhatelmas** [comment]
Sounds good then, I will try to integrate it at earliest.

**Comment by ahmetb** [comment]
It seems like 2-space indentation creates the minimum amount of diff.

`shfmt -w -i=2 hack/` seems to be working well, though it so far only improves spacing. I hope this doesn't become a hassle for new contributors.
