### ISSUE TITLE
ARM support for krew

### ISSUE THREAD

**Issue by giant-atomic-monster** [kubernetes-sigs/krew#330]
I'd like to build an ARM version so I can run it in my ARM cluster, and it looks like the releases on GH are x86 builds.

Thanks!

**Comment by ahmetb** [comment]
We can start supporting ARM. Currently I don't think neither plugins nor krew itself are allowed to be arm.

Can you please paste results for these commands:

- go env GOOS
- go env GOARCH

Maybe we can do a limited support for a particular platform not to over-extend support.

/kind feature

**Comment by unixorn** [comment]
Adding this from my personal GitHub because I mistakenly created this issue using my work account.

```
$ go env GOOS
linux
$ go env GOARCH
arm
```

This is identical on both my ODROID HC2 and my Raspberry Pi 4.

**Comment by ahmetb** [comment]
You need a 32-bit build, right? I assume GOARCH=amd64 won’t work for you?
Also I am not sure what we should be setting the GOARM value to (are you on ARM v5, v6, v7 or v8?).

**Comment by unixorn** [comment]
I'm on v7

On the Raspberry Pi 4:
```
$ uname -a
Linux cthulhu.unixorn.net 4.19.58-v7l+ #1245 SMP Fri Jul 12 17:31:45 BST 2019 armv7l GNU/Linux
```

On the HC2
```
uname -a
Linux gammera.unixorn.net 4.14.94+ #1 SMP PREEMPT Sat Jan 26 12:33:11 UTC 2019 armv7l GNU/Linux
```

**Comment by unixorn** [comment]
I'm still interested in an rPi build

**Comment by ahmetb** [comment]
We can do it but I think you won’t find any plugins supporting it. Nearly all plugins are compiled for amd64. Only bash based plugins would work.

**Comment by mhausenblas** [comment]
@ahmetb seems we already have an issue for it, great! As pointed out in https://github.com/kubernetes-sigs/krew-index/pull/407 I'm interested to make this happen.

> Only bash based plugins would work.

I think that pretty much all Go-based plugins at least theoretically count as well? At least with GoReleaser it's pretty straightforward.

**Comment by ahmetb** [comment]
Yeah sounds doable. 
For starters, we can enable this in manifest validator, then maybe release krew also for arm64.
Do arm executables work on arm64, typically?

**Comment by mhausenblas** [comment]
> Yeah sounds doable.

Cool!

> Do arm executables work on arm64, typically?

In general, yes (there are exception, etc.)

**Comment by ahmetb** [comment]
In that case, we might allow arm64 plugins, but not release krew itself for arm64, perhaps (since you reported krew compiled for `arm` works on `arm64`).

**Comment by mhausenblas** [comment]
> In that case, we might allow arm64 plugins, but not release krew itself for arm64,

That sounds like an excellent plan, let's take small steps and see if we witness an uptake.

**Comment by ahmetb** [comment]
I'm closing this since we already have a linux/arm distribution for krew.
/close
