### ISSUE TITLE
Dry install snippets in scripts

### ISSUE THREAD

**Issue by ferhatelmas** [kubernetes-sigs/krew#332]
Under `hack` folder, there are scripts to ensure code quality. 

In general, there is a script for validation to generate a diff between current code and expected, and there is another script to apply the diff.

Both of the scripts need to install the tool that does heavy lifting. That's why install snippet (ex: `install_shfmt` function in `hack/run-lint.sh` and `hack/format-scripts.sh`) is repeated. 

Extract repeated snippet(s) into its own script and call it where relevant to reduce duplication.

/kind cleanup

**Comment by ahmetb** [comment]
> and there is another script to apply the diff.

there shouldn't be such scripts IMO.

when build fails, it should tell user to run a command (ideally directly) like:

- gofmt -w -s ./...
- errcheck ...

let's not over engineer and try to eliminate "formatting scripts" that update files (E.g. hack/format-scripts.sh)

**Comment by corneliusweig** [comment]
Yes, the reformat script should probably go away, however the `go get` install function with a temporary `GOROOT` is still repeated in several places. I think it would make sense to extract that into a helper.

**Comment by ahmetb** [comment]
Yeah that sounds good. We can even use an external tool that does that. 
But writing a helper function that can be sourced sounds better.

**Comment by ferhatelmas** [comment]
Wow, time is flying.

**Comment by corneliusweig** [comment]
To clarify, this issue is about the code duplication between the following shell functions:

```
hack/install-gox.sh:install_gox()
hack/run-lint.sh:install_impi()
hack/run-lint.sh:install_shfmt()
hack/make-release-notes.sh:install_release_notes()
```

/help-wanted
/remove-lifecycle stale

**Comment by ahmetb** [comment]
Honestly I'm not 100% sure this is worth pursuing unless someone has time. :)
