### ISSUE TITLE
Stop releasing krew as .zip

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#338]
History here: Initially, krew only had .zip support for archives, but we added
.tar.gz in v0.2. This is why we're distributing krew itself (as a plugin) in
both extensions.

Currently we have a single file containing all release binaries in both
archieve formats (we might consider splitting in the future), however right now
there's no need for us to have both (.tar.gz and .zip).

Especially for analytics (download counts tracking via GitHub releases API),
having both files is just making it harder.

For v0.3.0, I'm hoping to get rid of .zip format. The only **downside** I can
think of: If a windows user needs the krew.exe, they need to install an extra
tool to extract it out of .tar.gz file.

Thoughts?

/kind proposal
/kind cleanup
/assign

**Comment by ahmetb** [comment]
Actually it seems like since krew needs to be installed via krew for the first time, windows users will need either a `krew.exe` or `krew.zip`. Otherwise, they have to download something extra like 7-ZIP to be able to get the krew.exe out.

What if we distributed these:
- krew.tar.gz{,.sha256}
- krew.exe{,.sha256}

**Comment by corneliusweig** [comment]
Sounds good to me.

**Comment by ahmetb** [comment]
Fixed with #339.
