### ISSUE TITLE
Create release download analytics

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#340]
Since we now distribute krew binaries on GitHub releases which has an API
that exposes total downloads per asset, we need an analytics solution to
find out growth over time (day, month, year) and per-tag.

/assign

**Comment by ahmetb** [comment]
I've prototyped something using Zapier+Google Sheets.

Here's a publicly accessible sheet: https://docs.google.com/spreadsheets/d/1Xxgcsjc01bVP67GMqouc9HaUQi5fy-KKwG4dJr0bHac/edit#gid=0 after collecting some more data, hopefully we can start drawing some charts around it.

**Comment by ahmetb** [comment]
/assign @corneliusweig 
I think the solution you're building around tracking Github release asset downloads over time will solve this (not only for Krew, but also the other plugins that distribute the same way using GitHub release assets).

**Comment by corneliusweig** [comment]
So what I've built is a little tool that retrieves github download counts via the github API and stores this in BigQuery: https://github.com/corneliusweig/krew-index-tracker

Currently, it creates one datapoint per day. Let's wait a few days and see if we can work with that data.

**Comment by ahmetb** [comment]
This is mostly now resolved at https://stats.krew.dev which we're running on Data Studio as beta. We should probably document it once it's more mature.

**Comment by ahmetb** [comment]
I'll close this.
Plugin analytics can now be found at: https://krew.sigs.k8s.io/docs/developer-guide/plugin-stats/ which redirects to `stats.krew.dev`.
/close
