### ISSUE TITLE
a repo with wishlist of plugins

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes-sigs/krew#352]
Hey Ahmet,

Do you think it may make sense to have a repo with wishlist of krew/kubectl plugins. 

this weekend I implemented 3, and I am sure there are other ppl who want to contribute new plugins, and need ideas.

( i searched for kubectl bugs in kubernetes repo with kind/feature, and implemented from there).

Thanks
Rajat Jindal

**Comment by ahmetb** [comment]
I am supportive you doing it but I don’t think it falls on our project cheer and i don’t think we have bandwidth to maintain such a repo. I recommend you create a repo on your personal account.
/close
