### ISSUE TITLE
plugin manifest validation error

### ISSUE THREAD

**Issue by mykhailoguk** [kubernetes-sigs/krew#355]
Hello, 
I'm trying to install nginx-ingress plugin, version 0.24.0
krew version:
`+ kubectl krew version
OPTION        VALUE
GitTag        v0.3.1
GitCommit     c241a35
`

I'm getting next error :
`F1024 18:08:06.537584   26054 root.go:58] plugin manifest validation error: failed to parse plugin version: version string "0.24.0" not starting with 'v'`

Trying to execute next command:
`(
    set -x; cd "$(mktemp -d)" &&
    curl -fsSLO "https://github.com/kubernetes/ingress-nginx/releases/download/nginx-0.24.0/{ingress-nginx.yaml,kubectl-ingress_nginx-$(uname | tr '[:upper:]' '[:lower:]')-amd64.tar.gz}" &&
    kubectl krew install \
    --manifest=ingress-nginx.yaml --archive=kubectl-ingress_nginx-$(uname | tr '[:upper:]' '[:lower:]')-amd64.tar.gz
)`

Can someone please suggest what I'm missing?

**Comment by ahmetb** [comment]
Looks like 0.25.0 has a v prefix
https://github.com/kubernetes-sigs/krew-index/blob/master/plugins/ingress-nginx.yaml

Can you try updating your local index: krew update
Then try re-running the command.

**Comment by mykhailoguk** [comment]
updating your local index didn't help, I added **v** to the ingress-nginx yaml.
