### ISSUE TITLE
Proposal: add structured output formats to krew list

### ISSUE THREAD

**Issue by JJJJJones** [kubernetes-sigs/krew#356]
Discussed previously in https://github.com/kubernetes-sigs/krew/pull/354.

`krew list` can be improved with structured (and custom) output formats.

The code to implement it can come mostly from [genericclioptions](https://github.com/kubernetes/cli-runtime/tree/master/pkg/genericclioptions).

**Comment by JJJJJones** [comment]
I've taken a stab at adding structured output using genericclioptions as @ahmetb suggested and can't do it without unnecessary bloat.

JSONPrinter's PrintObj() expects the runtime.Object to have an API group, which would bloat `krew list` with useless and potentially misleading information.

**Comment by ahmetb** [comment]
@JJJJJones makes sense. In that case, we can simply start with imitating -o/--output flags and supporting only 'json' and 'yaml'. What do you think?

**Comment by JJJJJones** [comment]
My apologies. I misspoke with that comment and tried to delete it; there was an unrelated culprit behind my problems getting PrintObj() to work correctly.

I've got JSON and YAML printing working using genericclioptions's JSONYamlPrintFlags.

**Comment by JJJJJones** [comment]
I've pushed my code: https://github.com/JJJJJones/krew/tree/356

Testing it now

**Comment by JJJJJones** [comment]
Fixed some linting issues, pushed latest.

**Comment by ahmetb** [comment]
You wanna send a PR for review?
If there's too much complexity involved we don't have to use genericclioptions.

Similarly, people will ask and have been asking for --output flag on `krew info` which is not a List response (but rather a single object). We need to make sure the approach can work with that too.

**Comment by JJJJJones** [comment]
>  If there's too much complexity involved we don't have to use genericclioptions.

I wouldn't say there is too much but we'll have a better idea with the PR.

> Similarly, people will ask and have been asking for --output flag on krew info which is not a List response (but rather a single object). We need to make sure the approach can work with that too.

It should slot in quite easily. Either a new runtime.Object can be created to handle all the fields of `krew info` (URI, SHA256, homepage, description) or the runtime.Object that list.go uses can be expanded with those fields but have the JSON/YAML directives to not print those fields when empty.

**Comment by ahmetb** [comment]
/priority P1
since multiple users are trying to rely on this.

**Comment by JJJJJones** [comment]
@ahmetb i'll get started on a design doc
