### ISSUE TITLE
even with --archive option, krew still insists on validating sha256

### ISSUE THREAD

**Issue by starpit** [kubernetes-sigs/krew#358]
krew nicely lets me override the manifest with a `--archive` command line option. however, if my manifest specifies a sha256, the krew installation will fail, because the manifest specifies a sha256 that will surely not match the archive given on the command line. maybe i'm missing something?

as a closely related issue, the error reporting in this case could perhaps use some improvement.

if i invoke krew with
```sh
kubectl krew install --manifest=kubeui.yaml --archive=./dist/electron/Kui-darwin-x64.tar.gz 
```

i get this error, which is a sha256 validation error, but the `uri` string is misleading, as it does not match the `--archive=` option. also it took me a while to parse this out. i first read "failed to download and extract", and only with more careful parsing (and ignoring the misleading uri string) did i finally parse this out as a sha256 mismatch error

> failed to install plugin "kubeui": install failed: failed to download and extract: failed to download and verify file: failed to get the uri "https://github.com/kui-shell/plugin-kubeui/releases/download/v1.0.0/kubectl-kubeui_darwin_amd64.zip": checksum does not match, want: f6f2509fc58607030659b90424fabf96a25981652a162fccbd195158bdf3dca0, got 162dd81efcd806a94346535c87724cf06125d9c64677d2c61294304bddeedfb0

**Comment by ahmetb** [comment]
I recall there was a time we skipped checksum verification for local --archive files. Maybe there's a bug that prevents that.

You're right, it would be be better if the URL mentioned the local file and not the URL in the manifest (despite not actually downloading).

**Comment by ahmetb** [comment]
/cc @ferhatelmas
/cc @corneliusweig 
can one of you please investigate?

**Comment by corneliusweig** [comment]
Thanks for reporting this. Indeed, the error message is a bit misleading here, so that should be improved.

On the other hand, I do believe that it is the better behavior to enable shaSum validation for `--manifest`+`--archive`. This is the only way for plugin authors to check if their manifest is valid without first uploading the archive to a hosting platform. Thus, the shaSum check should also fail hard when installing locally.

**Comment by ahmetb** [comment]
> This is the only way for plugin authors to check if their manifest is valid without first uploading the archive to a hosting platform.

Yeah, I started to recall that this is why we enabled checksum check with `--manifest` again. Do you know what uses the noopVerifier today?

**Comment by starpit** [comment]
thanks for the consideration. i guess i found it a bit tedious to have to modify the file every time i rebuilt my test archive.

**Comment by corneliusweig** [comment]
> Do you know what uses the noopVerifier today?

AFAICT the `falseVerifier` and `trueVerifier` are only used in tests. Thus, they should probably be removed from the business logic.

**Comment by corneliusweig** [comment]
/close
I think this has been clarified as intentional behavior. Please re-open if you feel that the discussion was not over.
