### ISSUE TITLE
Problems running tests in MacOS Mojave

### ISSUE THREAD

**Issue by JJJJJones** [kubernetes-sigs/krew#364]
hack/run-tests.sh breaks because the Mac grep implementation doesn't behave like GNU. I [wrote some code](https://github.com/JJJJJones/krew/blob/db1ee4d7d1b542060dd72badfef7ab23dd1542e1/hack/verify-code-patterns.sh#L19) which can solve it.
```
➜  krew git:(356) ✗ hack/run-tests.sh
...
Running linter
Check code patterns
grep: warning: recursive search of stdin
```

hack/run-integration-tests.sh breaks because readlink won't handle non-symbolic links. From `man readlink`:

```
     When invoked as readlink, only the target of the symbolic link is printed.  If the given argument is
     not a symbolic link, readlink will print nothing and exit with an error.
```

To solve this I replace [this line](https://github.com/kubernetes-sigs/krew/blob/master/hack/run-integration-tests.sh#L41) with below.

```bash
if [[ $(uname) == "Darwin" ]]; then
  krew_binary_realpath="$(stat -f "%N" "${KREW_BINARY}")"
else
  krew_binary_realpath="$(readlink -f "${KREW_BINARY}")"
fi
```

**Comment by ahmetb** [comment]
Since as developers of Krew we rely on GNU grep (even on macOS), I wish there was an easier solution here (smh).

Is there a chance "stat -f" does exactly that on linux, too? It would be really good to have 1 way of doing things.

/priority P3

**Comment by JJJJJones** [comment]
> Since as developers of Krew we rely on GNU grep (even on macOS), I wish there was an easier solution here (smh).

Then GNU grep (ggrep) is a requirement for Mac users.

> Is there a chance "stat -f" does exactly that on linux, too? It would be really good to have 1 way of doing things.

Unfortunately no. Macs uses `-f` and `--format` isn't an accepted flag. [Linux](https://linux.die.net/man/1/stat) uses `--format` and `-f` is a separate flag. Both can use the same `"%N"` for formatting though.

**Comment by ahmetb** [comment]
So here's normally what we do in krew repo when we encounter a situation like this:

We implement this "readlink" functionality in one place. Then we update `verify-code-patterns.sh` to make sure nobody can use `readlink`/`stat` anywhere else but that particular file.

Otherwise, we'll see other scripts running making the same mistake and this issue repeating itself. If you want to go that route, that's the best, otherwise I recommend we leave it as-is (and maybe make a note that gstat is the one that's needed).

**Comment by JJJJJones** [comment]
> Otherwise, we'll see other scripts running making the same mistake and this issue repeating itself. If you want to go that route, that's the best

That sounds fine with me if i'm understanding correctly, though i'm not sure how it would be implemented.

**Comment by ahmetb** [comment]
implementation:
```
# hack/resolvelink.sh

function resolvelink {
   if darwin else ...
}
```

usage:
```
# hack/some-script.sh
source "${SCRIPTDIR}/resolvelink.sh"

foo="$(resolvelink "$x")"
```

preventation (https://github.com/kubernetes-sigs/krew/blob/master/hack/verify-code-patterns.sh):

```
1. scan hack/ (except hack/resolvelink.sh) to find references to "stat -f" and "readlink"
2. if references found, fail and tell people to use resolvelink (krew impl)
```

I know it's very cumbersome but actually helps.
We use this to straight out prevent usages of certain Go methods etc in the codebase.

**Comment by corneliusweig** [comment]
Like other kubernetes project, krew uses standard GNU tools to run scripts. See https://github.com/kubernetes-sigs/krew/pull/482#issuecomment-579997341 to see how this can be set up

/close
