### ISSUE TITLE
receiptsmigration detection on windows is faulty if krew itself fails to install

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#374]
If I try to install krew on windows and fail halfway and receipts/krew.yaml is not written, krew will end up in a situation that requires `kubectl krew system receipts-upgrade`.

This happens because we look at `store/` dir which is not empty. But in this case of a bug (like #357) `store/krew/` is actually an empty dir.

https://github.com/kubernetes-sigs/krew/blob/7bd396984863b9379d76b2bc020da78756bd7a54/pkg/receiptsmigration/migration.go#L42-L63

What if we instead looked at entries under `bin/` directory?

/area platform/windows
/priority P2

**Comment by corneliusweig** [comment]
Yes, that should indeed be more stable. Let's check if there is at least one symlink starting with `kubectl-`.

**Comment by ahmetb** [comment]
SGTM. That would ensure a plugin installed with krew exists (incl krew itself) so it would ensure krew is installed at least :)
