### ISSUE TITLE
Figure out why Administrator user is needed on windows for creating symlinks

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#378]
/area platform/windows
/priority P2
/kind bug

Right now Windows user (1) installing krew, or (2) installing plugins with Krew needs to be in a "Run as Administrator" shell (cmd, or powershell). Otherwise they'll get an error like:

> W1031 07:54:50.430335   11588 install.go:127] failed to install plugin "krew": install failed: failed to link installed plugin: failed to create a symlink form "C:\\Users\\z\\.krew\\bin" to "C:\\Users\\z\\.krew\\bin\\kubectl-krew.exe": symlink C:\Users\z\.krew\store\krew\v0.3.1\krew.exe C:\Users\z\.krew\bin\kubectl-krew.exe: **A required privilege is not held by the client.**

This is bad for user experience as:

- makes it harder to install krew (first-time/one-time experience)
- makes it harder to install plugins on krew (frequent experience)

**Need help** from someone to look into this and see if we can do this without needing Administrator privileges.

Some quick search reveals this might be possible **as of Windows 10 Insiders build 14972**:

- https://www.wintellect.com/non-admin-users-can-now-create-symlinks-windows-10/
- https://security.stackexchange.com/questions/10194/why-do-you-have-to-be-an-admin-to-create-a-symlink-in-windows
- https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/
- https://developer.amazon.com/docs/fire-app-builder/configure-windows-symlinks-no-admin-priv.html

Maybe I was trying on an older build (will check this later), in this case, we need confirmation if we need to do something to use this functionality.

**Comment by ahmetb** [comment]
It appears like Go actually has support for the SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE flag out of the box in os.Symlink. https://golang.org/src/os/file_windows.go#L386

![image](https://user-images.githubusercontent.com/159209/68629919-6093e000-049a-11ea-8e71-886e2cc0a098.png)

Sounded promising, right? Here comes the dumbest part: SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE [only works if Developer Mode is enabled](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10), so, for anyone distributing client software (like krew), it's useless.

**Comment by corneliusweig** [comment]
:face_with_head_bandage:

**Comment by ahmetb** [comment]
Not much we can do here, I am afraid. 

We can maybe detect symlinking capabilities and warn. I am not sure if that’s the way to go.

**Comment by webmutation** [comment]
Hello, I am on a win10 corporate laptop and do not have admin rights.

As a workaround to this symlink issue is it possible to use a different path where I have those rights?

As a workaround I tried to copy the file and rename it, but when I try to start it it returns the following

> You need to perform a migration to continue using krew.
Please run `kubectl krew system receipts-upgrade`
F0518 16:17:06.817816   36196 root.go:77] krew home outdated

is there a way to run Krew without using symlinks? I copy manually the file, but after I get the 
following

> kubectl krew
not supported by windows

I would really appreciate if anyone has some pointers on how to run krew without admin rights on windows.
