### ISSUE TITLE
Simplify move operations

### ISSUE THREAD

**Issue by ferhatelmas** [kubernetes-sigs/krew#379]
Target is `pkg/installation/move.go`.

The context it's coming from https://github.com/kubernetes-sigs/krew/pull/375#issuecomment-552661715

As @ahmetb writes:

> The naming of the methods makes the hierarchy unclear:

```
* moveToInstallDir (extractDir → storeDir)
  * moveAllFiles (extractDir → tmp)
    * moveFiles
      * findMoveTargets
        * getDirectMove
          * isMoveAllowed
        * isMoveAllowed
      * renameOrCopy
  * renameOrCopy (tmp → storeDir)
```

> For example, I'm not sure why is "getDirectMove" is a special case. There's already a filepath.Glob code in that method. Could that be already handling single file moves?

We're also [open to a dependency](https://github.com/kubernetes-sigs/krew/pull/375#issuecomment-552663320) that handles most of it out of the box.

/kind cleanup
/priority P3

**Comment by ahmetb** [comment]
@robertvolkmann ping, or you can /unassign yourself if you are not working on this.

**Comment by ferhatelmas** [comment]
I believe this is still relevant and we don't want to close.

**Comment by corneliusweig** [comment]
/remove-lifecycle rotten
Yes, let's give this some more thought.
