### ISSUE TITLE
mkdir redundancy during installation

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#383]
/kind cleanup
/priority P3
/good-first-issue

`moveOrCopyDir` always deletes the target directory:

https://github.com/kubernetes-sigs/krew/blob/555b305979fa7b58b6a77c637f1eca025196869f/pkg/installation/move.go#L185-L197

and it's only called from `moveToInstallDir` which creates this directory (only to be removed later on):

https://github.com/kubernetes-sigs/krew/blob/555b305979fa7b58b6a77c637f1eca025196869f/pkg/installation/move.go#L155-L159

We should probably to eliminate this mkdir.

That's why in logs we see stuff like

> I1113 15:44:02.815815   27900 move.go:192] There's already a directory at move target "/Users/ahmetb/.krew/store/get-all/v1.2.0". deleting.
> I1113 15:44:02.815850   27900 move.go:196] Move target directory "/Users/ahmetb/.krew/store/get-all/v1.2.0" cleaned up

which ideally wouldn't occur most of the time (unless maybe there was a leftover from last time). So we should keep this os.RemoveAll to be defensive against leftovers from a previous incomplete installations (or incomplete uninstallations).

**Comment by corneliusweig** [comment]
Sounds good! Thanks for this detailed analysis.

**Comment by chriskim06** [comment]
I know that this is an older issue and some changes have been made, but I just wanted to clarify something.

It seems like the directory created by `os.MkdirAll(installDir, 0755)` is where the binary gets installed: `$KREW_ROOT/store/<plugin>/<version>`, then the call to `os.RemoveAll` will just remove the `.../<version>` directory. I think the `.../<plugin>` part of the  `installDir` needs to exist for `os.Rename` to not return a file/directory not found error. If so, then would it be enough to change the call to `os.MkdirAll` to just be passed `$KREW_ROOT/store/<plugin>` (not sure yet what the best way to do that would be, but just checking first if this seems acceptable)? This would get rid of the removing of the directory after its created, but I don't think the full mkdir can be removed.

Let me know if I've misunderstood something!

**Comment by ahmetb** [comment]
I am having trouble following, that's confusing. :) 
Maybe make a small PR and see if it fixes the issue.
