### ISSUE TITLE
Drop GOPROXY default

### ISSUE THREAD

**Issue by ferhatelmas** [kubernetes-sigs/krew#388]
/kind cleanup

Since their explicitly set values are reitaration of defaults.

https://golang.org/doc/go1.13#modules

`GO111MODULE`:
> The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src.

`GOPROXY`:
> The GOPROXY environment variable may now be set to a comma-separated list of proxy URLs or the special token direct, and its default value is now https://proxy.golang.org,direct.

**Comment by ferhatelmas** [comment]
If you think this is a good thing to do (still can prefer being explicit), I will send a PR.

**Comment by ahmetb** [comment]
I think we retain GO111MODULE explicitly because travis sets GOPATH and therefore tries to use the old ways. 

GOPROXY can be removed.

**Comment by ferhatelmas** [comment]
OK, let me drop proxy in one PR and we can discuss module separately because there are multiple references to it.

**Comment by corneliusweig** [comment]
@ferhatelmas Can this be closed now?

**Comment by ferhatelmas** [comment]
I think no because according to the first sentence of release notes, it doesn't matter if source under GOPATH or not. 
 
> The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src.

That's why I think we should drop it too but since it's referenced more, I wanted to split PRs. What do you think?

**Comment by corneliusweig** [comment]
@ferhatelmas Let's try it out :)

**Comment by ahmetb** [comment]
It seems like Travis now sets GO111MODULE=auto and also set GOPATH.
https://docs.travis-ci.com/user/languages/go/

This is weird and I'm not sure why it's assuming =off , because GOPATH is not supposed to be set for =on.

**Comment by corneliusweig** [comment]
Am I the only one who is confused here? I'm beginning to think that it is more apparent and obvious if we re-state the default settings for `GO111MODULE` and `GOPROXY`.
That seems to leave the smallest room for interpretation.
