### ISSUE TITLE
Installation cannot be done in fish

### ISSUE THREAD

**Issue by Aracki** [kubernetes-sigs/krew#392]
I'm following the [installation guide for fish](https://github.com/kubernetes-sigs/krew#fish) but all I'm getting is the `env` output. Even when I paste the command the `./$KREWNAME` is red, so something is wrong with either the syntax or my fish shell.
![image](https://user-images.githubusercontent.com/6129986/68997797-a7bf0e00-08aa-11ea-83cd-28f8f39e317a.png)

**Comment by ahmetb** [comment]
You can type bash and install it using bash then use in fish. We aren’t actively maintaining fish instructions.

**Comment by corneliusweig** [comment]
Hi @Aracki, if you can provide a fix this would be awesome! Otherwise it would make more sense to remove the fish instructions altogether, if they are buggy.

**Comment by Aracki** [comment]
Hi @corneliusweig thanks for reminding me of this one. I've made a #441.

**Comment by Aracki** [comment]
Even the `./$KREWNAME` is read and the command outputs a lot of ENVs variables, it will throw the WARNING but will successfully install the krew. 

If something is broken for you, remove the `~/.krew` and paste this command again.
