### ISSUE TITLE
sample-cli-plugin doesn't talk about krew

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#399]
https://github.com/kubernetes/sample-cli-plugin

Ideally this repository should at least have a `Distributing` section that talks about how to package up and distribute using Krew, which is a widely accepted tool using and distributing kubectl plugins.

Maciej (@.soltysh) also mentioned we should have a sample Krew manifest in that repository. Maybe as a stretch goal we can do that, as well.

**Comment by corneliusweig** [comment]
A few months back, I made this PR: https://github.com/kubernetes/kubernetes/pull/82039

Maybe we continue the discussion there?

**Comment by ahmetb** [comment]
I totally forgot about that PR. Thanks.
Let's keep this opening from our side for tracking.
