### ISSUE TITLE
Bash alias

### ISSUE THREAD

**Issue by esin** [kubernetes-sigs/krew#401]
Hi
I'm developer of https://github.com/esin/kubectlsafe and have question about installing plugin

Due that plugin will be useful only when add them into alias bash commands as mentioned in README: https://github.com/esin/kubectlsafe/blob/master/README.md
What is the best way to add alias to .bashrc with krew or maybe give this option to user?

Thank you

**Comment by ahmetb** [comment]
Maybe users can add this to their bashrc:

 > source <(kubectl krew safe —script)

We also have a similar plugin called “prompt”. It instructs users through  the caveats section to show a post-install message.
