### ISSUE TITLE
krew returns an error when flags are given

### ISSUE THREAD

**Issue by oke-py** [kubernetes-sigs/krew#409]
I'm looking into https://github.com/kubernetes/kubectl/issues/727 and I found that krew returns an error when flags are given.

```
$ kubectl krew list --context minikube
F1130 21:35:35.907312   14667 root.go:58] unknown flag: --context

$ ~/.krew/bin/kubectl-krew --context=minikube list
F1130 21:31:38.408483   14471 root.go:58] unknown flag: --context
```

Is this an expected behavior?

**Comment by ahmetb** [comment]
Plugins don’t inherit kubectl flags. 
I am not sure why you expect —context to work on krew. It doesn’t have a notion of context.
