### ISSUE TITLE
Use small shell-based plugin for integration tests instead of `konfig`

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#410]
The integration tests in krew need to install a real plugin from the krew index. This needs to be small, so that the tests do not need to download large blobs for each run.

Currently, `krew` uses `konfig` for that. However, `konfig` creates a dedicated dist archive for distribution and does not use the repo tarball which is created automatically for github releases. This is ok, but github keeps track of download counts for release assets. As we run our tests often, this distorts the download numbers of `konfig` quite a bit. It would be better to switch to a small plugin which is distributed purely as repo tarball, for example `ctx`.

**Comment by chriskim06** [comment]
I'd like to work on this!

/assign

**Comment by corneliusweig** [comment]
Great! If you have questions, you can also reach out on slack or post here.
