### ISSUE TITLE
Prevent files without .yaml extension to be parsed as plugins in index

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#412]
As seen in #411 we accidentally merged a file with .yml instead of .yaml
into the krew-index, which broke clients updating to the latest version of the
index repo.

It seems like parsing goes like this (search -v=10):

	I1130 17:04:39.795261   43833 scanner.go:72] Reading plugin "debug-shell"
	I1130 17:04:39.795446   43833 scanner.go:72] Reading plugin "debug"
	I1130 17:04:39.795698   43833 scanner.go:72] Reading plugin "df-pv"
	E1130 17:04:39.795734   43833 scanner.go:56] failed to load file "df-pv", err: open /Users/ahmetb/.krew/index/plugins/df-pv.yaml: no such file or directory

So we're clearly picking up on this file without .yaml extension, but then
trying to read it further.

/kind bug
/priority P0

**Comment by corneliusweig** [comment]
We could also be more lenient about file endings. After all, `.yaml` and `.yml` both seem to be used a lot.

**Comment by ahmetb** [comment]
Let’s start restrictive. We can be more lenient if there’s need/demand. But we can’t do the opposite as it would break.
