### ISSUE TITLE
Consider go1.13 errors package

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#414]
Go has introduced new error wrapping primitives. Especially the errors.Is check can be useful to krew in certain few locations that we rely on error type (ENOENT etc). 

https://golang.org/doc/go1.13#error_wrapping

**Comment by corneliusweig** [comment]
Recommended read before doing this: https://blog.golang.org/go1.13-errors

Also, https://github.com/fatih/errwrap might be helpful.

**Comment by erain** [comment]
For reference, the blog post @corneliusweig mentioned is https://blog.golang.org/go1.13-errors

**Comment by ahmetb** [comment]
Thanks. It would be good to see if we get Stack Traces like the current err pkg when run with -v 5 etc

**Comment by corneliusweig** [comment]
Thanks @erain. I got confused and thought that the link from @.ahmetb was the same :man_facepalming:

**Comment by ferhatelmas** [comment]
> Also, fatih/errwrap might be helpful.

I [offered help](https://github.com/fatih/errwrap/issues/2#issuecomment-561347099)  to integrate errwrap into golangci-lint. It have it locally, will push upstream accordingly.

**Comment by corneliusweig** [comment]
@ferhatelmas would that make sense? My understanding is that it should be a deliberate choice to wrap or not to wrap (see blog.golang.org/go1.13-errors). A linter would simply report any such occurrence.

**Comment by ferhatelmas** [comment]
I think yes because even if it's decided to wrap, people are error-prone and might forget putting `%w` and might use `%s` or `%q`.

Also, it helps in transition with `--fix` flag of golangci-lint to automatically refactor codebase.

**Comment by ferhatelmas** [comment]
Yes. Here is a reply to it from the famous [blog post](https://blog.golang.org/go1.13-errors#TOC_3.4.).

> When adding additional context to an error, either with fmt.Errorf or by implementing a custom type, you need to decide whether the new error should wrap the original. There is no single answer to this question; it depends on the context in which the new error is created.

That's why it should be opt-in linter, false by default.

**Comment by ahmetb** [comment]
Here's the criteria I expect from this new errors mechanism:

- ability to wrap errors (to add more context/reason) without having to implement a custom type
- preserves syntax while printing the wrapped error messages (`reason: reason: root cause`)
- preserves ability to print errors normally (as above) or with stack trace when `-v`≥1 specified (currently achieved wit %+v)
- ability to assess if one of the errors in the wrapped chain is of a certain `error` instance (e.g. `io.EOF`) or can be evaluated with methods like `os.IsNotExist()`

**Comment by ahmetb** [comment]
Promising new library: https://github.com/rotisserie/eris not sure if compatible with go1.13 errors but seems to have the same capabilities and nearly identical interface.

**Comment by erain** [comment]
/unassign @erain 

I am really sorry but I don't have the bandwidth for working on this now.

**Comment by corneliusweig** [comment]
ping @robertvolkmann. You expressed some interest in this a while back, I think.
