### ISSUE TITLE
Dead link in v0.3.3 release

### ISSUE THREAD

**Issue by JJJJJones** [kubernetes-sigs/krew#418]
[v0.3.3 release page](https://github.com/kubernetes-sigs/krew/releases/tag/v0.3.3)

The [installation instructions](https://github.com/kubernetes-sigs/krew/blob/v0.3.3/README.md@v0.3.3) is a dead link.

**Comment by ahmetb** [comment]
Manually fixed, have no idea that got in there.

The link was:

https://github.com/kubernetes-sigs/krew/blob/v0.3.0/README.md@v0.3.0

I'm assuming I was copy/pasting something from the browser to release notes.

Thanks for reporting.

/close
