### ISSUE TITLE
Fresh install of krew complains about local plugin index

### ISSUE THREAD

**Issue by tony-yang** [kubernetes-sigs/krew#419]
I followed the installation guide and installed v0.3.3 on a new Mac. After adding krew to path, the first use complains about krew local plugin index not initialized.

```
F1203 10:07:07.784437   15575 root.go:58] krew local plugin index is not initialized (run "kubectl krew update")
```

Had to run `kubectl krew update` to initialize the local plugin index. Expected this to be done as part of the installation process so a new user can start using the plugin immediately.

**Comment by ahmetb** [comment]
This is actually by design (Similar to apt). But you bring up a good point, this delays plugin installation.

Since we’re trying to add support for multiple plugin indexes, it might be a good idea to retain this behavior. Maybe all we need is to add another cmd to installation?

**Comment by corneliusweig** [comment]
Yes, I think this would good. If somebody does a fresh install, we can safely assume that she also wants to install plugins :)

**Comment by chriskim06** [comment]
Is this just suggesting updating the README install instructions with something like `./$KREWNAME update`?

**Comment by tony-yang** [comment]
I was originally thinking the update step could be part of `./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install` but to ahmetb's point, updating the README to include an extra line of instruction would also do.

If people think this approach works, I'm happy to send in a PR to the README.

**Comment by ahmetb** [comment]
yeah I think that's a good approach.
we can do `$KREW=./krew-"$(uname | tr '[:upper:]')` and `"$KREW" install && "$KREW" update"`.
