### ISSUE TITLE
Design a logo for Krew

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#437]
Krew is approaching a point where it needs a proper logo. Opening this to community discussion and ideas (inspired from how [kubeflow](https://github.com/kubeflow/kubeflow/issues/187) did this).

I'm thinking it should be not too far from the [kubectl logo/theme](https://twitter.com/brandonphilips/status/1110308895635832832).

If you have any logo ideas, explain them here, maybe someone else can turn it into a design. Or sketch your idea on a piece of paper and post it here. We can work from there and get a logo designer to finish the work.

/kind proposal
/priority important-soon

**Comment by corneliusweig** [comment]
My favorite would be something like an octopus holding various tools in its tentacles. :octopus:

**Comment by ahmetb** [comment]
I was thinking of cuttlefish (a crew) lifting or carrying a package. It could be one, holding up a package with its tentacles, as well.

**Comment by corneliusweig** [comment]
I like the idea with the package. Maybe the cuttlefish doesn't really have to carry it, and just _cuddle_ the package is enough?

**Comment by caiobegotti** [comment]
I saw some cuttlefishes on https://www.flaticon.com with attribution-based licensing that would look great as a white-on-blue heptagon!

**Comment by ahmetb** [comment]
@caiobegotti thanks for the suggestion. Indeed there are some really cool designs there that we can probably put together.

**Comment by ahmetb** [comment]
Here’s an idea:

![FDBACB3B-FA4A-41AB-924E-C9065A675CF3](https://user-images.githubusercontent.com/159209/70955393-93933b80-2025-11ea-9020-f0efcf9d9f8c.png)

Put together two icons:

https://www.flaticon.com/free-icon/cuttlefish_447808
https://www.flaticon.com/free-icon/crate_1554455

**Comment by ahmetb** [comment]
Here’s the same idea but different cuttlefish and crate icons:

![439E703C-FD11-404E-A9FB-50E9FCCA8FCA](https://user-images.githubusercontent.com/159209/70955982-75c6d600-2027-11ea-9002-afbfeccbadb9.png)

https://www.flaticon.com/premium-icon/crate_2188114 
https://www.flaticon.com/free-icon/cuttlefish_1137925

**Comment by corneliusweig** [comment]
Here is another draft. I used a blue package instead of the crate, which fits better IMHO

![krew](https://user-images.githubusercontent.com/22861411/71041095-7d21d880-2128-11ea-963f-6db61d9a1d77.png)


<div>Icons made by <a href="https://www.flaticon.com/authors/srip" title="srip">srip</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
<div>Icons made by <a href="https://www.flaticon.com/authors/smashicons" title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

**Comment by caiobegotti** [comment]
> Here is another draft. I used a blue package instead of the crate, which fits better IMHO

Wow, that's pretty! Personally I'd go with no bubbles to make it simpler and perhaps rotate the cuttlefish so it lays horizontally over the crate, but that's just me 😄

**Comment by corneliusweig** [comment]
Like so?

![krew-2](https://user-images.githubusercontent.com/22861411/71042582-6a110780-212c-11ea-92b4-70541911ae74.png)

I thought the tilt would look a bit like cuddling (similar to kubectl logo). But I'm no designer (^_^);;

**Comment by eisraeli** [comment]
Just wondering, what does "krew" stands for ? Does it have any meaning relating to Kubernetes ?

**Comment by corneliusweig** [comment]
@eisraeli The name was inspired by `brew`, but for kubernetes hence the 'k'. But I also like that it sounds like `crew`, which could stand for the k8s community. Quite fitting, given that `krew` is a tool for the community of plugin authors.

**Comment by GraysonNull** [comment]
Hi all, I've been playing around with some ideas and landed on this one that I thought was kind of interesting. Wanted to get everyone's thoughts on it. 
<img width="597" alt="Screen Shot 2019-12-19 at 5 24 57 PM" src="https://user-images.githubusercontent.com/4110866/71217861-d43cc000-2284-11ea-87a0-448239639275.png">

**Comment by ahmetb** [comment]
That's a pretty good idea as well, thanks @GraysonNull. I wonder if it needs the Kubernetes logo.

**Comment by GraysonNull** [comment]
@ahmetb Yeah I can for sure do a version without it. I was also thinking of a version where the crate was actually the heptagon shape. Are you thinking a cuttlefish should definitely be a part of the logo?

**Comment by ahmetb** [comment]
I think we're open to anything now as long as it's not too complicated. Imagine it being used on repo homepage, a docs site, and printed on enamel (lapel) pins. :) That's why a mini Kubernetes logo in the middle doesn't make a lot of sense.

**Comment by GraysonNull** [comment]
Yeah totally makes sense! Ok well I'll work on a few other ideas that are in a little different direction as well. The thread thus far was really leaning heavy into the cuttlefish angle and I wasn't sure if it was definitively heading that direction. I'll post some things here when I can. Availability is limited heading into the holiday season. 

Thanks for the feedback!

**Comment by corneliusweig** [comment]
@GraysonNull That's a really cool idea, I like it a lot! What would you think if the octopus would peek over one of the sides of the crate?

**Comment by eisraeli** [comment]
@corneliusweig corneliusweig
> But I also like that it sounds like crew, which could stand for the k8s community. Quite fitting, given that krew is a tool for the community of plugin authors.

I really like this explanation much better. :) 

[As for the logo, maybe a parrot instead of Octopus ?](https://previews.123rf.com/images/sababa66/sababa661902/sababa66190200014/117370723-beautiful-parrot-in-a-pirate-hat-sitting-on-the-wheel-of-the-ship-vector.jpg)

(* I'm not the creator of the image)

**Comment by ahmetb** [comment]
The question would be: why the parrot? :)

**Comment by eisraeli** [comment]
@ahmetb An Octopus reminds me of a [Kraken](https://en.wikipedia.org/wiki/Kraken), which usually cause ships to sink.
Why parrot? I guess I've watched too many pirates movies, in which there are always a captain, crew and a [parrot](https://www.shutterstock.com/image-vector/illustration-cartoon-pirate-parrot-ships-wheel-1059270599).  :D

**Comment by iboonox** [comment]
Some suggestions

![alt text](https://ibb.co/8rNNS6Z)

**Comment by iboonox** [comment]
![GitHub Logo](https://i.ibb.co/Dwq1tZW/krew2.jpg)

**Comment by corneliusweig** [comment]
Wow, these look awesome! It would be hard to improve that theme :)

My only worry is that the logo revolves mainly around the letter `K`, which is very non-unique in the kubernetes universe (think kustomize, kubernetes, kubectl, kube-ps1, kubectx, kubeval, kube-hunter, kube*). Your study shows that you were also experimenting with a box (and it's still in there), but I wish it were more visible in the final version. For example, very right mid&bottom in your study grid is more accessible, I think.

**Comment by ahmetb** [comment]
Thanks a lot for many options @iboonox, these are very valuable.

I like the brand design you did in https://github.com/kubernetes-sigs/krew/issues/437#issuecomment-568528688 comment. But like Cornelius, I see several issues:

- the color palette is nice, but it's also very similar to CNCF logo
- the logo almost looks and feels like Kubeflow
- doesn't have any reference to package management or kubectl
- in other words, it feels pretty generic, also given 'K' is very common in the ecosystem.

Among other designs I really like this one:
> ![image](https://user-images.githubusercontent.com/159209/71450215-2f056a00-2712-11ea-8a23-b3f7cc3392a2.png)

It's minimal, and has reference to package management and nautical theme. That's definitely in line with our earlier nautical, cuttlefish theme.

However, it doesn't kubectl or kubernetes hints (should it have?), other than the tentacles (which is 2-levels indirection: tentacle &rarr; cuttlefish &rarr; kubectl &rarr; kubernetes).

But it's definitely original. If there's consensus around one of the designs, we should iterate on that.

I'm looking to have a design that is memorable, and myself and others can wear as an enamel pin on my backpack or jacket proudly. :)

**Comment by iboonox** [comment]
Thank you @ahmetb and @corneliusweig for your feedback. 

I agree that the blue color and the letter k are very common in the cloud native ecosystem. Personally I prefer simple and abstract logos but i think that the idea of ​​integrating a cuttlefish/tentacle is original.

I will try to make another ideas/proposals in this direction

**Comment by ahmetb** [comment]
Yeah, I agree. I think we should lean into simplicity. Tentacles theme is definitely not required.

**Comment by iboonox** [comment]
What about this ?

![alt text](https://i.ibb.co/WKF8PsN/Screenshot-2019-12-26-at-16-58-36.png)
![alt text](https://i.ibb.co/gjbfgB1/Screenshot-2019-12-26-at-17-03-15.png)

more sober

![alt text](https://i.ibb.co/sW2BXb7/Screenshot-2019-12-27-at-18-54-50.png)

**Comment by iboonox** [comment]
More sober

![alt text](https://i.ibb.co/sW2BXb7/Screenshot-2019-12-27-at-18-54-50.png)

**Comment by caiobegotti** [comment]
I really liked these last two sober ones! Suggestions for eventual iterations:

- no text in the logo: simplicity
- dump the gradient blue background
- shape the two packages as heptagons with the Kubernetes blue instead
- make the cephalopod black instead of maybe cuttlefish-like in color with the packages in the Kubernetes blue
- tint the cephalopod with the very same blue of the Kubernetes logo (keeping the packages golden yellow like today)
- if you must for clarity due to the removal of the background, maybe make the waves a single thin line somehow?

Again, these look super cool! It looks friendly and not menacing, it "embraces" both the packages of Krew as well the marine motif of Kubernetes, it's simple 🎉

**Comment by ahmetb** [comment]
So far I'm liking https://github.com/kubernetes-sigs/krew/issues/437#issuecomment-569321022 one. I have some tweak suggestions, like:

- move lively/[flat](https://flatuicolors.com/) colors, instead of cold/pastel ones
  - agreed with Caio, color palettes in initial logos are more alive
- what if we tilted body little bit more horizontal?
- what if we made tentacles wrap around the boxes and appear in the front like in "more sober" design?
- reduce gradients (+1 to Caio)

**Comment by n3wscott** [comment]
I wonder if there is a boat rowing logo idea like https://t.co/KaR5BULfjk

It plays off of crew and team and boats, etc

**Comment by corneliusweig** [comment]
That's also a nice idea. However, I wonder how much longer we should collect ideas before we close this thread and start selecting the favorite draft.

**Comment by ahmetb** [comment]
I know @iboonox has more designs to share here so I vote for no need to rush.

**Comment by ahmetb** [comment]
I know @iboonox has more designs to share here so I vote for no need to rush.

**Comment by iboonox** [comment]
I think that the proposal with the whole cuttlefish looks more like an illustration difficult to integrate on different media ( print, stcikers ... ), agree with @ahmetb, the logo must be minimalist, easy to remember ...

So as suggested let's iterate on 

![logo](https://user-images.githubusercontent.com/159209/71450215-2f056a00-2712-11ea-8a23-b3f7cc3392a2.png)


![logo](https://i.ibb.co/8N1V9Rt/1.jpg)

Highlighting more the box/package 

![logo](https://i.ibb.co/g6RX8wk/2.jpg)


![logo](https://i.ibb.co/cC1DR2Y/3.jpg)

**Comment by ahmetb** [comment]
These are really good @iboonox, thanks a lot. I'm converging on the simplistic design with a small unique/differentiating feature –like a tentacle.

I think mainly the problem with [this design](https://user-images.githubusercontent.com/159209/72276786-96159080-35e5-11ea-9def-d50e2393a151.png) is that I can't tell it's a package (it just seems to be a hexagon). What if we added some rectangles inside [like this one](https://user-images.githubusercontent.com/159209/72276851-b2b1c880-35e5-11ea-9ad4-5d55465566a7.png) to make it more obvious it's a box?

**Comment by iboonox** [comment]
Highlighting the box :

![logo](https://i.ibb.co/7Wsqh0F/Screenshot-2020-01-16-at-22-24-27.png)

**Comment by ahmetb** [comment]
I vote towards nr.3 above.

**Comment by corneliusweig** [comment]
My favorite is nr.5! I like how the tentacles really look like it's grabbing the thing. Slightly lighter colors (like nr.3) could also look nice.

I guess indicating some sucker cups would make the logo too noisy, right?

**Comment by iboonox** [comment]
@corneliusweig I think there are already a lot of details in the logo.

To move forward I suggest that we restrict the vote between ?

![logo](https://i.ibb.co/K9k5FYC/krew2.png)

**Comment by corneliusweig** [comment]
@iboonox You clearly have a much better understanding of how logos work. So if you say sucker cups are too much, then I believe you :).

Has anyone had success with voting on a GH issue? I think it's easiest to post both versions separately and vote with :+1: on the posts. WDYT?

**Comment by iboonox** [comment]
Version 1

![version1](https://i.ibb.co/yPSLx5y/version1.png)

**Comment by iboonox** [comment]
Version 2
![version 2](https://i.ibb.co/PY6pTMF/version2.png)

**Comment by ahmetb** [comment]
According to voting results so far Version 1 is overwhelmingly liked more.
I'll work with @iboonox on getting several versions of this logo and sort out licensing and close this.

**Comment by corneliusweig** [comment]
Apparently, I'm the only one with bad taste :rofl:

Thanks @iboonox for such creative work, this is awesome!

**Comment by soltysh** [comment]
:+1: for version 1 - it's simpler :wink:

**Comment by ahmetb** [comment]
@iboonox was kind enough to provide different color schemes for the selected design and I ran a Twitter poll for them.

![0331B0A1-AE0E-4E5A-985E-BE003E4A4364](https://user-images.githubusercontent.com/159209/73614740-adc5b080-45b6-11ea-8f09-1276219706e6.jpeg)

It looks like we’ll go with the dark colors. Awaiting the PR for svg/png files at this point. Thanks all for participating.

**Comment by iboonox** [comment]
PR created.
#499

**Comment by ahmetb** [comment]
For future reference: 
https://github.com/kubernetes-sigs/krew/blob/master/docs/KREW_LOGO.md
