### ISSUE TITLE
"kubectl krew search" too verbose

### ISSUE THREAD

**Issue by eisraeli** [kubernetes-sigs/krew#440]
For ex. :
`$ kubectl krew search kube`
______________________________
`E1219 15:03:34.989829   20429 scanner.go:57] failed to load file "capture", err: platform ({Head: URI:https://github.com/sysdiglabs/kubectl-capture/releases/download/v0.1.0/kubectl-capture.v0.1.0.tar.gz Sha256:86c947a9fa9acb73eeb179e29ede20755a426a4fb96aa82375246a356f3a804f Selector:&LabelSelector{MatchLabels:map[string]string{},MatchExpressions:[{os In [darwin linux]}],} Files:[] Bin:kubectl-capture}) is badly constructed: can't have a plugin without specifying file operations`

`E1219 15:03:34.991535   20429 scanner.go:57] failed to load file "debug", err: platform ({Head: URI:https://github.com/verb/kubectl-debug/releases/download/v0.1.2/kubectl-debug_darwin_amd64.tar.gz Sha256:e8c6ce28b0eaec9aff17dc3b4c569ef3e731cad00673423d82524bd4d5c829ab Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:./kubectl-debug}) is badly constructed: can't have a plugin without specifying file operations`

`E1219 15:03:34.992459   20429 scanner.go:57] failed to load file "evict-pod", err: platform ({Head: URI:https://github.com/rajatjindal/kubectl-evict-pod/releases/download/v0.0.4/darwin-amd64-v0.0.4.tar.gz Sha256:129edec609f5be480bef5894034b61cde16e50aa92abf41965dd05f53d7bf891 Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:kubectl-evict-pod}) is badly constructed: can't have a plugin without specifying file operations`

`E1219 15:03:34.998955   20429 scanner.go:57] failed to load file "passman", err: failed to read the plugin manifest: json: cannot unmarshal number into Go struct field LabelSelector.matchLabels of type string`

`E1219 15:03:35.002841   20429 scanner.go:57] failed to load file "ssm-secret", err: platform ({Head: URI:https://github.com/pr8kerl/kubectl-ssm-secret/releases/download/v1.2.2/kubectl-ssm-secret_1.2.2_darwin_x86_64.tar.gz Sha256:9b381c9d456a4036c72520a94905605c278f869071b3924517d026d0f281cc6c Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:kubectl-ssm_secret}) is badly constructed: can't have a plugin without specifying file operations`

`E1219 15:03:35.003758   20429 scanner.go:57] failed to load file "view-allocations", err: platform ({Head: URI:https://github.com/davidB/kubectl-view-allocations/releases/download/0.6.0/kubectl-view-allocations_0.6.0-x86_64-apple-darwin.tar.gz Sha256:9c254505fbabe11b7aab5f2910c9990f855845b2552d4af1b694fb40de19ab81 Selector:&LabelSelector{MatchLabels:map[string]string{arch: amd64,os: darwin,},MatchExpressions:[],} Files:[] Bin:./kubectl-view-allocations}) is badly constructed: can't have a plugin without specifying file operations`
______________________________________
`
NAME                           DESCRIPTION                                        STATUS
kubesec-scan                   Scan Kubernetes resources with kubesec.io.         available
view-serviceaccount-kubeconfig Show a kubeconfig setting to access the apiserv... available
`

I think these issues should be caught during CI and notify the devs, but I'm not sure if  showing this during a simple search is a desired behavior ?

**Comment by corneliusweig** [comment]
The manifest format has evolved a little. The file copy spec now has a default and is no longer required. As you are using an old version of krew, you are seeing a lot of errors. So could you upgrade and check again?

**Comment by corneliusweig** [comment]
@eisraeli Have you had time to check with the latest krew version?

**Comment by eisraeli** [comment]
@corneliusweig I was indeed using an outdated version. Upgraded and the issue was solved. Thanks.
