### ISSUE TITLE
Ensure archive extraction directory is not used before

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#448]
Right now, the archive extraction directories are predictable:

```
I1230 09:20:01.972733   15961 downloader.go:42] Reading archive file into memory
I1230 09:20:15.918530   15961 downloader.go:47] Read 9558121 bytes from archive into memory
I1230 09:20:15.918583   15961 verifier.go:51] Compare sha256 (9cab1684efbb7eac7daaff15882ef59b28b358c9eb24105c26981dfa670342d1) signed version
I1230 09:20:15.918621   15961 downloader.go:203] detected "application/x-gzip" file type
I1230 09:20:15.918636   15961 downloader.go:100] tar: extracting to "/tmp/krew/krew-downloads/tree"
```

This is not good, because if someone creates `/tmp/krew/krew-downloads/tree` ahead of time, and places files in it, then if the plugin manifest specifies installation as:

```
- from: .
  to: *
```

the file placed there earlier will end up in the plugin's installation directory. This is not clean.

Ideally, we should not do `filepath.Join(tempDir, "krew-downloads", name)` and just use an `ioutil.TempDir()` everytime we need to do this operation.

With this, `paths.DownloadPath()` might now be obsolete, because that method doesn't use `KREW_ROOT` anyway (it just joins os.TempDir() with a deterministic path).

/priority P3
/priority backlog
/good-first-issue

**Comment by aimbot31** [comment]
Hello @ahmetb would love to take this issue.
Thus, I have some remarks, why paths.DownloadPath() might be obsolete ? Can't we just change `func (p Paths) DownloadPath() ` to generate a random directory ?

**Comment by ahmetb** [comment]
I think we should get rid of DownloadPath() overall, and just make a tempdir where necessary to ensure we get a clean dir.
