### ISSUE TITLE
Support direct binary (non-archive) downloads

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#45]
I've been thinking about this for a while.

Especially with kubectl 1.12 plugin model, it's inevitable people will have Go repositories on Github with static binary releases (without ZIPs).

I've so far heard from at least one plugin dev that `goreleaser` doesn't support creating .zip, so they need to change their release model to accommodate krew distribution.

#### Strawman design:

We can have 3 modes, like:

<table>
<tbody>
<tr>
<td>
archive downloads:
<pre>
download:
  archive: https://.../foo.zip
  sha256: [...]
</pre>
</td>
<td>
file downloads:
<pre>
download:
  file: https://.../kubectl-foo_linux_amd64
  sha256: [...]
</pre>
</td>
<td>
head:
<pre>
download:
  head: [...]
</pre>
</td>
</tr>
</tbody>
</table>

Thoughts? There's time to do this during for krew 0.2.

cc: @lbb

**Comment by lbb** [comment]
We choose ZIP, as it is the default format GitHub offers to download (although tar.gz is also available).

If we choose to offer different download formats we should not use different classifiers to specify an URI. We should focus on MIME types as UNIX does it. We also should fall back to files post-fixes.

**Comment by ahmetb** [comment]
> We choose ZIP, as it is the default format GitHub offers to download

This is not a good argument and only works for python/bash scripts etc. Not to mention, github supports .tar.gz, too?



> we should not use different classifiers
> We also should fall back to files post-fixes.
> We should focus on MIME types as UNIX does it.

All these 3 are basically just "do not be verbose and employ magic", which I'm against.

Good software rarely tries to guess things (esp. from stuff like mime types or extensions).

**Comment by lbb** [comment]
1. In case we want to be explicit by writing the filetype of the resource at the URI:
   If we do so, we should not make it a field in the plugin spec like `file: 
 https://..`, `archive: https://...`. Adding fields is not flexible:
  * We have to add a new field for every compression type. -> It's a spec version bump on every new field.
  * Developers can declare multiple URI's at once.

  I propose to add a new text field `downloadType` which specifies the download format.


2. We only have a few types we want to support (.tar, tar.gz, zip and plain). All of 
  those types are identifiable by a magic number that is part of it's standard.
  MIME detection is not magic; it's just detecting the file header bytes.

I'm not for employing magic. We **know** what type it is after we have downloaded it. We are not guessing.

**Comment by ahmetb** [comment]
Yeah that mostly makes sense.

We could easily add validation to support multiple fields. I suspect if we receive this request again, we need to go implement something simple (like detecting file extension).

**Comment by ahmetb** [comment]
I'm not sure if there’s enough demand for it currently.
/close
