### ISSUE TITLE
Move away from Travis CI to GitHub Workflows

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#451]
/priority P3

Travis CI at this point seems to be a ticking time bomb. It would be better to migrate to GitHub Workflows. I don't see any particular downsides (we can test/run neither locally). Migration would be the only cost.

Advantages:
- no need to _allow_ an app to kubernetes-sigs org, GH Actions don't require permissions
- no need for encrypted secrets
- we can probably move to `goreleaser` and simplify some of the asset building, stamping (with version+gitinfo) and uploading (to GH Releases) as part of this.
- we can more easily separate the stages of build (e.g. lint, build, tests, release...) with a compartmentalized UI, compared to Travis.

Up for grabs and discussion.

**Comment by ferhatelmas** [comment]
> Travis CI at this point seems to be a ticking time bomb.

Is there a reference to include here?

**Comment by ahmetb** [comment]
No hard references, but anecdotal. Company changing hands, losing many employees, and GitHub has improved in the meanwhile. I suspect Travis will stick around ~2 years at least, so we can continue, but this is something we can address on the backlog.

**Comment by RubenBaez** [comment]
@ahmetb This change will be applied in all projects or only in `Kubernetes-sigs / krew`

**Comment by ahmetb** [comment]
Only this repo, and probably to `krew-index` repo. 

If you want to prototype, you can fork and write .github/* workflow yamls by converting .travis.yml to those tasks.

**Comment by RubenBaez** [comment]
/assign 
Ok, I will help with this.

**Comment by RubenBaez** [comment]
@ahmetb 
What about with secure env variables:
> env:
  global:
  -secure: .....

> api_key:
    secure: .....

Do I need those tokens in GitHub's actions? If so, how can I get the tokens to secure them in GitHub workflows?
Finally why `deploy` stage does not show in Travis logs?

**Comment by ahmetb** [comment]
Hmm. I think one of the secrets is maybe for codecov.io which we can get rid of. Benefits haven’t been so great. 

The other secret is for publishing releases to github, which GitHuh injects automatically https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token

If you look at “tag builds” on travis, you’ll see logs for deploy section, as it only executes on tag pushes.

**Comment by ahmetb** [comment]
This is done in #461. 
/close
