### ISSUE TITLE
support generate bash completion

### ISSUE THREAD

**Issue by wu0407** [kubernetes-sigs/krew#460]
`kubectl krew completion  bash`  generate bash completion file

**Comment by ahmetb** [comment]
Kubectl plugins Mechanism currently don’t support bash completion. You can find the relevant issue on Kubernetes repo. 

We don’t plan to implement this anytime soon either. The value add is minimal. 

/close

**Comment by corneliusweig** [comment]
For reference: https://github.com/kubernetes/kubernetes/issues/74178
