### ISSUE TITLE
kubectl krew errors 'Not supported by windows' message

### ISSUE THREAD

**Issue by shahga** [kubernetes-sigs/krew#463]
At command prompt, kubectl krew ...any command... gives "not supported by windows" message.
The command prompt in administrative mode also gives same message.
e.g. 
> kubectl krew version
> not supported by windows

Environment:
kubectl client version = 1.14.8
krew version = 0.3.3
OS = Windows 10.0.17763

**Comment by ahmetb** [comment]
Kubectl versions earlier than 1.15 had trouble executing any plugin. If you update to a higher version, I suspect this will be fixed. 
/close
