### ISSUE TITLE
wsl support ( krew 0.3.3) 

### ISSUE THREAD

**Issue by yanivpaz1973** [kubernetes-sigs/krew#469]
I am using WSL with Ubuntu 18.04  :
``
kubectl krew 
``
I am getting :
cannot allocate memory

(   set -x; cd "$(mktemp -d)" &&   curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/download/v0.3.3/krew.{tar.gz,yaml}" &&   tar zxvf krew.tar.gz &&   ./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" install     --manifest=krew.yaml --archive=krew.tar.gz; )

**Comment by ahmetb** [comment]
Whats your kubectl version?

**Comment by ahmetb** [comment]
Tried with kubectl v1.17 and krew 0.3.3. Not reproducible. Feel free to add more details then I can reopen. 
/close
/area platform/windows
