### ISSUE TITLE
updated plugin list is should be wrapped more aggressively

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#472]
![image](https://user-images.githubusercontent.com/159209/73154310-d405c080-408b-11ea-8029-443d53caa9fe.png)

With the #457 in,  it now seems like on a 180 char terminal this is still pretty long. 

We should probably wrap more aggressively.

**Comment by corneliusweig** [comment]
Duplicate of #473 
Fixed in #477 
/clode
