### ISSUE TITLE
Show smaller output for updated plugin list

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#473]
cc: @artmello 
With this new change we see this:

![image](https://user-images.githubusercontent.com/159209/73154467-26df7800-408c-11ea-82d0-9dee7f2e1f85.png)

I think we can dramatically update the viewing experience by doing these:

- show "Upgrades available" ONLY IF any of the listed plugins are installed.
- for "New plugins available" , user doesn't care about version number, so ideally we should not show it.

Also we can play a little bit with the indentation.

Here's what I'm thinking:

```
Updated the local copy of plugin index.
  New plugins available:
    * net-forward
  Upgrades available for installed plugins:
    * auth-proxy v0.7.0 -> v1.0.0
    * tree v0.3.1 -> v0.4.0
Installing plugin: tree
[...]
```

Thoughts?

/good-first-issue
/priority important-soon

**Comment by ahmetb** [comment]
> * show "Upgrades available" ONLY IF any of the listed plugins are installed.

It seems like this is already the current behavior, apologies for misunderstanding.

**Comment by artmello** [comment]
@ahmetb I agree about not showing version for new plugins. About indentation, I am afraid that the output can be too long with one plugin per line. If more people agree, maybe we can get back to the  idea of single line output for some commands and multiple lines for update. I pushed one PR with the suggested changes if we want to try it to see how it goes.
