### ISSUE TITLE
Proposal nr.2: Support for custom index repositories

### ISSUE THREAD

**Issue by chriskim06** [kubernetes-sigs/krew#483]
Allowing users to specify custom indices to download plugins from would allow people to distribute plugins without having to go through the main krew-index repo. This would be useful at companies where people want to share plugins that are specific to their workflows or aren't appropriate for krew-index.

I wanted to share the proposal doc I had thrown together here https://docs.google.com/document/d/1Im5gmBA6yuKRWgJWbaBjTTFNvkH0me05V3wEeNPU7fE/edit?usp=sharing and opened a new issue for it based on [this](https://github.com/kubernetes-sigs/krew/pull/478#issuecomment-579107437). There's a lot of similarities to the docs in https://github.com/kubernetes-sigs/krew/issues/23 so if this doesn't add enough I'd be happy to close this.

A lot of ideas came from https://docs.brew.sh/Taps, mainly around how to handle duplicate plugin names.

**Comment by ahmetb** [comment]
Thanks for writing this up.
I'm calling this "proposal number two" for index repos, as you've said there are similarities.
I think both Cornelius and I should read both how Taps work and how your design works. It might take some time but hang in there.

**Comment by corneliusweig** [comment]
@chriskim06 can you ping me on kubernetes slack?

**Comment by ahmetb** [comment]
Ahead of our online meeting about this on Feb 18th, I've documented my wishlist of what I'd love to see from the solution + implementation process:

https://docs.google.com/document/d/1_xYsxtwtQTboKOyp920pb1OWLTQEdU6gF7-QvUA6S0Y/edit?usp=sharing

**Comment by chriskim06** [comment]
Sounds good I'll take a look through that doc and add comments if I have any questions

**Comment by ahmetb** [comment]
Both @corneliusweig and @ahmetb (myself) have discussed the proposal with @chriskim06 and approved it. 

/lgtm
/approve

**Comment by jdolitsky** [comment]
Late to the game here, but would like to point to #580 regarding alternative approach to distribution via OCI

**Comment by jdolitsky** [comment]
The fact that this issue has come up is actually itself testament to "why use OCI" - all these concepts (multitenancy, distributed repos, auth) have already been solved for in the context of Docker push/pull which is the basis for OCI distribution-spec: https://github.com/opencontainers/distribution-spec

**Comment by jdolitsky** [comment]
and yes, I realize this throws a big wrench into the existing plan and architecture, but I feel very strongly this is the correct way forward, especially for tooling in the k8s/container space. feel free to reach out to discuss more.

**Comment by ahmetb** [comment]
@jdolitsky let's move the issue there as it doesn't concern this feature.

**Comment by chriskim06** [comment]
Should we close this one too?

**Comment by ahmetb** [comment]
👍🏼 
/close
