### ISSUE TITLE
Print warning on every command if PATH does not have KREW_ROOT/bin

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#485]
## Scenario 1: Homebrew

This came up in the Homebrew formula (which we aren't supporting officially at the moment). https://github.com/Homebrew/homebrew-core/pull/49547

Homebrew maintainers refuse to have Caveats for `krew` formula that tells users to:

```
      To complete the installation, you need to add the following to your
      ~/.bash_profile, ~/.bashrc or ~/.zshrc:

          export PATH="${PATH}:${HOME}/.krew/bin"
```

But it does link `kubectl-krew` in PATH. So, users will do `kubectl krew install foo` but `kubectl foo` mysteriously won't work (and `kubectl plugin list` won't show `foo` despite `kubectl krew list` does).

User is left confused.

## Scenario 2: Incomplete krew installations

User followed instructions from Krew's README to install krew. But they did not follow the PATH update (or they did not restart their shell).

So they type `./krew install foo`, it works. But `kubectl foo` mysteriously won't work (and `kubectl plugin list` won't show `foo` despite `kubectl krew list` does).

So the user is left confused.

## Proposed solution

In both problems, user does not have $KREW_ROOT/"bin" directory in their PATH.

So, let's add a PreRun **warning** to root krew command that informs the user about this situation, with the message above.

In addition, we can determine which of `~/.bash_profile`, `~/.bashrc` or `~/.zshrc` or Windows instructions we should be mentioning from environment variables (using $SHELL + GOOS).

**Corner case:** This should not print when `krew` running first time ever, to installing itself (e.g. for the first time) using the instructions in the readme.

/good-first-issue
/priority P2

**Comment by corneliusweig** [comment]
What's the best way to detect if this is the first run?
One thing that comes to my mind is to move the `ensureDirs(paths.BasePath(), ..)` call from `init` into `preRun` below:
https://github.com/kubernetes-sigs/krew/blob/da2c84b78336ce481da87e7379a21ca82373ac78/cmd/krew/cmd/root.go#L79-L90

Then we could check with `os.Stat(paths.BasePath())` if the base directory already exists. If it's missing, we don't do the `PATH` check.

**Comment by ahmetb** [comment]
> What's the best way to detect if this is the first run?

I was thinking of something like looking at argv, but it seemed too complex (`--manifest=.*\.krew\.yaml` or `argv[n]==install argv[n+1]==krew`).

Maybe we can move `ensureDirs()` to `preRun()`, that way we can check if it's the first run or not.
