### ISSUE TITLE
Upgrade notification can be misleading for devs

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#501]
If you locally compile and install a krew binary, you might misleadingly
see an upgrade notification like

    A newer version of krew is available (v0.3.3-47-g14f129f -> v0.3.3).
    Run "kubectl krew upgrade" to get the newest version!

This happens because our semver parsing (correctly) assumes any version str with
pre-release section (e.g. -47-g14f129f) is "older" than the string without
prerelease section. (SemVer pkg works as designed, however.)

I suspect this will bug only the developers. Hope that's not big of a deal, but
if there's an easy fix I'm missing, we should apply (e.g. changing the first `-`
to `+` probably will solve, but not sure how git can do that)

/priority P3

**Comment by yardenshoham** [comment]
Seeing as we don't do upgrade checks In development builds, this can be closed.

#494 closes this.

https://github.com/kubernetes-sigs/krew/blob/f9772a92863cbedc0de118a06a1a231441786bb4/cmd/krew/cmd/root.go#L130

**Comment by ahmetb** [comment]
/close
thanks
