### ISSUE TITLE
Upgrade failed; but receipt still written when symlinking fails

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#502]
/kind bug
/priority P3

Repro steps:

1. Install krew v0.3.3 normally
2. Build a Krew binary locally.
3. Replace ~/.krew/bin symlink of krew itself with the binary :D 

     `mv out/bin/krew-darwin_amd64 $(which kubectl-krew)`

4. `kubectl krew update`  && `kubectl krew upgrade` to krew v0.3.4

5. Observe output:

```
~ $ kubectl krew upgrade
Updated the local copy of plugin index.

Upgrading plugin: krew
WARNING: failed to upgrade plugin "krew", skipping (error: failed to install new version: failed to link installed plugin: failed to remove old symlink: file "/Users/ahmetb/.krew/bin/kubectl-krew" is not a symlink (mode=-rwxr-xr-x))
Upgrading plugin: ns
Skipping plugin ns, it is already on the newest version
WARNING: Some plugins failed to upgrade, check logs above.
A newer version of krew is available (v0.3.3-47-g14f129f -> v0.3.4).
Run "kubectl krew upgrade" to get the newest version!
```

6. `kubectl krew upgrade krew`  says **"can't upgrade, the newest version is already installed"**

7. But `kubectl krew version` still shows `v0.3.3-47-g14f129f`  and `krew list` shows v0.3.4

Clearly the upgrade receipt was written despite upgrade operation actually failing.

I'm not saying we should support this case (e.g. user breaking the symlink) but if an upgrade fails, install receipt should not be changed.

**Comment by corneliusweig** [comment]
Related to https://github.com/kubernetes-sigs/krew/pull/195#discussion_r296915679

Looks like install does it right, but in upgrade I messed it up :/

**Comment by ahmetb** [comment]
I honestly don't know how we merged 4000 line PR back in the day.
