### ISSUE TITLE
Website Table of Contents proposal

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#509]
/kind proposal
/area docs

Before [docs/](/docs) go out of control, I'm hoping to create a website (taking the example of https://kind.sigs.k8s.io) hosted on Kubernetes org’s Netlify account.

Right now both user guide and the developer guide are lengthy. Hopefully, this will make things easier for users and plugin developers can navigate the docs much easier.

## Proposed ToC

* What is Krew?
* User Guide
  * Setup
    * Installing
    * Verifying installation
    * Uninstalling Krew
  * Using Krew
    * Discovering Plugins
    * Installing Plugins
    * Listing Installed Plugins
    * Upgrading Plugins
    * Uninstalling Plugins
* Developer Guide
    * Developing kubectl plugins
      * How to develop plugins
      * Plugin Naming Guide
      * Best practices
    * Writing a Krew plugin manifest
    * Example krew plugin manifests
    * Testing plugin manifests locally
    * Releasing
       * Submitting a new plugin to Krew
       * Releasing plugin updates
       * Automating plugin releases

Any objections/comments?
If not, I'll move forward with a PR sending empty files with these titles, and fill them up over time.

**Comment by corneliusweig** [comment]
Go ahead, this looks great!

I'd also include a section about contributing to krew. I think it's good to have this in the krew repo too, but it should also be on this new page. Something like

* Krew contributor guid
  * How to get involved
  * Coding standards
  * Running tests

WDYT?

**Comment by ahmetb** [comment]
Yeah I am hoping over time we can publish those as well. Our contributing docs are looking quite official at the moment. We can loosen the tone a bit and write more.

**Comment by ahmetb** [comment]
Superseded by #514. Closing here.
/close
