### ISSUE TITLE
add details to Test_fetchLatestTag_GitHubAPI

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#516]
```
--- FAIL: Test_fetchLatestTag_GitHubAPI (0.16s)
    fetch_tag_test.go:29: Expected a latest tag in the response
FAIL
```

This test is very frequently failing on Travis CI.

I'm guessing because of GitHub API rate limits exposed to pool of Travis CI machines. Surprisingly works fine on GitHub Actions, however.

Maybe it'd be ideal if we add some message to the error so we can see what's going on.

**Comment by corneliusweig** [comment]
Yes, this is on my todo list. I'll try to get to it later today.
