### ISSUE TITLE
Inconsistent program name in --help message

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#521]
See the end, it doesn't say `kubectl krew`

```
$ kubectl krew
[...]
Flags:
  -h, --help      help for krew
  -v, --v Level   number for the log level verbosity

Use "krew [command] --help" for more information about a command.
```

**Comment by aimbot31** [comment]
Hi @ahmetb would love to help on this one !

**Comment by aimbot31** [comment]
After some researches i've found that we cannont change this behaviour.
However, we can use the `Aliases` field to print the fact that you can do `krew` and `kubectl krew`.
I've tried to use template but this seems a little bit overkill for the need.

Here is the result with the `Aliases` field :
```
krew is the kubectl plugin manager.
You can invoke krew through kubectl: "kubectl krew [command]..."

Usage:
  krew [command]

Aliases:
  krew, kubectl krew

Available Commands:
  help        Help about any command
  info        Show information about a kubectl plugin
  install     Install kubectl plugins
  list        List installed kubectl plugins
  search      Discover kubectl plugins
  uninstall   Uninstall plugins
  update      Update the local copy of the plugin index
  upgrade     Upgrade installed plugins to newer versions
  version     Show krew version and diagnostics

Flags:
  -h, --help      help for krew
  -v, --v Level   number for the log level verbosity

Use "krew [command] --help" for more information about a command.
```

**Comment by ahmetb** [comment]
I think that makes the situation worse. Isn't there a Name field?

**Comment by aimbot31** [comment]
There's a field "Use" but if we enter a space in this field, it will only take the first name.
For example: `Use: "kubectl krew"` will give : 

`Use "kubectl [command] --help" for more information about a command.`

**Comment by ahmetb** [comment]
Hmm I suspect that might be a bug in cobra. (It would be good to follow up with them). Alternatively, we can consider nbsp character to prevent splitting

**Comment by aimbot31** [comment]
Do you want me to try something with nbsp and place an issue to cobra repository ?

**Comment by ahmetb** [comment]
Let's ask cobra repo first since this is not urgent. Maybe they have a solution. I also recommend looking at cobra code to see where/why the splitting happens. Maybe there's a way to disble it.

**Comment by brianpursley** [comment]
Has anyone asked cobra yet?

I worked up a little example that I think illustrates the problem from cobra's perspective:

```
package main

import (
	"github.com/spf13/cobra"
)

func main() {
	var rootCmd = &cobra.Command{
		Use: "kubectl myplugin",
	}

	rootCmd.AddCommand(&cobra.Command{
		Use: "dosomething",
		Run: func(cmd *cobra.Command, args []string) {
		},
	})

	_ = rootCmd.Execute()
}
```

**Default help for root command when running without a command:**
```
go run main.go
```

```
Usage:
  kubectl [command]

Available Commands:
  dosomething 
  help        Help about any command

Flags:
  -h, --help   help for kubectl

Use "kubectl [command] --help" for more information about a command.
```

**Help for a specific command:**
```
go run main.go dosomething --help
```

```
Usage:
  kubectl dosomething [flags]

Flags:
  -h, --help   help for dosomething
```

**Comment by ahmetb** [comment]
Don’t think anyone followed up in Hugo repo. If anyone has time to fix it in upstream, would be super appreciated. 💕

**Comment by brianpursley** [comment]
I'll take a look at it and follow up in the cobra repo.

/assign

**Comment by corneliusweig** [comment]
Cobra people are very reluctant to merge anything. I would not count on them suddenly merging a PR. See https://github.com/spf13/cobra/issues/959.

**Comment by brianpursley** [comment]
@corneliusweig I noticed they have a lot of unmerged PRs, so I guess you're probably right.  I did open an [issue](https://github.com/spf13/cobra/issues/1057) and suggest a potential [PR](https://github.com/spf13/cobra/pull/1058) that would allow space to be preserved if it is escaped, but I won't get my hopes up.  

In the meantime, I will revisit the krew code and see if there is a workaround.

**Comment by corneliusweig** [comment]
Yeah, I fear we have to handle this on our side.

**Comment by brianpursley** [comment]
Its ok I actually think I found a way that cobra lets us customize the usage template.... working on it now to try it out.  looks promising so far.

**Comment by ahmetb** [comment]
I am hoping we don’t maintain a custom go template. But if we do, maybe we can simplify a few other things along the way.

**Comment by ahmetb** [comment]
If the patch is trivial btw I might be able to get it merged. Just let me know.

**Comment by brianpursley** [comment]
OK, let me know what you think.

It's a little bit hack-y but not TOO bad :smile:

https://github.com/kubernetes-sigs/krew/pull/547
