### ISSUE TITLE
logo: Add source files for Krew logo

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#532]
It would be great to get the src files added for the logo designs so that future contributors/designers can work on it. 

/cc @iboonox

**Comment by ahmetb** [comment]
@iboonox if you have time, it would be great if you can take a stab at #533 and this.

**Comment by corneliusweig** [comment]
I think the SVGs are already pretty good to work with. We don't want to bloat the repo with `psd` files anyway, right?

**Comment by ahmetb** [comment]
I suppose you’re right.  I am not sure how we’d edit/modify them if needed though.

**Comment by corneliusweig** [comment]
Inkskape is usually quite good at handling SVGs. I don't know how the experience is in Photoshop, but I hope it's somewhat reasonable.

SVG is a lossless vector format, so in the end, it's a problem of the editing software :woman_shrugging:
