### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by Parth6288** [kubernetes-sigs/krew#535]
I installed krew following instructions on https://krew.sigs.k8s.io/docs/user-guide/setup/install/
however when i run 

> kubectl krew update

 i am getting below error:
`F0305 08:08:36.537792    6874 root.go:77] failed to update the local index: command execution failure, output="": exec: "git": executable file not found in $PATH`

**Comment by ahmetb** [comment]
Ah, git is a dependency. We should note that.

**Comment by corneliusweig** [comment]
@Parth6288 The git dependency is mentioned in step 1 for all environments. So you have to install git somehow on your system. For example, on Ubuntu you would do
```sh
sudo apt-get install git
```
