### ISSUE TITLE
Proposal: cut git dependency

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#536]
Through a pure Go implementation like https://github.com/src-d/go-git
we should be able to phase out shelling to git and therefore having external
dependencies.

Of course git will always be beteter and we don't rely on a lot of detailed
or exotic features (the only interesting one that comes to mind is
"git reset --hard @{upstream}" usage we have).

I might try and prototype this.

/kind proposal

**Comment by corneliusweig** [comment]
This would make it easier to use `krew` in minimal environments, such as an alpine container. I would still be careful here. Let's avoid to tie our hands in the future.

@ferhatelmas Do you have some experience with this library? I saw that you contributed to it.

**Comment by ahmetb** [comment]
> Let's avoid to tie our hands in the future.

Worst case, the old implementation would still be there (possibly behind a feature flag), and our git.go does a decent job of serving as a wrapper.

**Comment by ahmetb** [comment]
I think one of the main concerns would be supporting custom credential helpers (for custom indexes).

For example, at Google, `sso://user/ahmetb/foo.git`  is a valid git repository, authenticated via `git-credential-helper-sso` auth plugin that's in PATH. I'm not seeing support for that in go-git. https://godoc.org/gopkg.in/src-d/go-git.v4/plumbing/transport/client

**Comment by corneliusweig** [comment]
> Worst case, the old implementation would still be there (possibly behind a feature flag), and our git.go does a decent job of serving as a wrapper.

Yes, I would prefer that. Maybe just fallback to the library, if no `git` is found in `PATH`? Then Google-magic would work out of the box without a flag.

**Comment by ahmetb** [comment]
Some more on go-git project health:
https://github.com/go-git/go-git/wiki/go-git-has-a-new-home!-v5-and-some-explanations

**Comment by corneliusweig** [comment]
Ok.. so let's see if the project stays as active as before if the backing company doesn't exist anymore.

**Comment by ferhatelmas** [comment]
@ahmetb @corneliusweig sorry I was late. I take a stub on this. 

Project is active but moved to https://github.com/go-git/go-git due to copyright.

/assign @ferhatelmas
