### ISSUE TITLE
Add unit tests for internal/gitutil pkg

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#538]
This package is currently lacking tests. It should be fairly easy to implement some tests that reach 100% coverage in this package. This would also help #536.

/priority backlog
/help
/good-first-issue

**Comment by naxhh** [comment]
Is okay if I assign this to me?

I'm still exploring the repo and looking how things are done around here but I think 'll be a good issue to start

**Comment by ahmetb** [comment]
Thanks @naxhh I've assigned you.


This is prob most important: It should be able to clone public URLs as well as local git directories. Need to make sure destinationPath is mkdir'ed or not:
```
func EnsureCloned(uri, destinationPath string) error
```

Ditto above. You can probably test this by `EnsureCloned` + `Exec(git reset hard --head~1)` + `EnsureUpdted` + `Exec` to see if update actually worked by looking at current hash.
```
func EnsureUpdated(uri, destinationPath string) error
```

I'm not quite sure why this is exported currently. Maybe we can eliminate.
```
func Exec(pwd string, args ...string) (string, error)
```

Should be rather easy after EnsureCloned.
```
func GetRemoteURL(dir string) (string, error)
```

Should be rather easy:
```
func IsGitCloned(gitPath string) (bool, error)
```

**Comment by naxhh** [comment]
Hi again @ahmetb I made two functions just to ensure this is the approach you where expecting:
https://github.com/naxhh/krew/blob/add-test-for-gitutil/internal/gitutil/git_test.go
If you can confirm that is the approach you wanted I'll finish the tests.

Regarding `gitutil.Exec` I've only see it being used in https://github.com/kubernetes-sigs/krew/blob/master/internal/index/indexoperations/index_test.go#L160

And it's being used to generate an empty repository. Personally I think that function is too open and I would prefer to generate a helper function for that use case. but I let the decision on you.
