### ISSUE TITLE
Update kubectl autocomplete when installing plugins

### ISSUE THREAD

**Issue by mrwulf** [kubernetes-sigs/krew#543]
First, krew is awesome, much needed, and much appreciated!
Second, it would be nice if after I install a plugin it "magically" showed up when I tab-complete after `kubectl`. For example, I just installed `resource-capacity` (aka `kube-capacity`). Now, when I try to remember how to access the plugin I begin typing:
```
$ kubectl [tab][tab]
annotate       apply          autoscale      completion     cordon         delete         drain          explain        kustomize      options        port-forward   rollout        set            uncordon       
api-resources  attach         certificate    config         cp             describe       edit           expose         label          patch          proxy          run            taint          version        
api-versions   auth           cluster-info   convert        create         diff           exec           get            logs           plugin         replace        scale          top            wait       
```
but no `resource-capacity`.

Supplying a few characters for the plugin name doesn't help either:
```
$ kubectl res[tab][tab]
```

**Comment by corneliusweig** [comment]
This came up before: https://github.com/kubernetes-sigs/krew/issues/155
It's not something that can be solved on krew's side, so I'm going to close this. But you can make some noise here: https://github.com/kubernetes/kubernetes/issues/74178

/close
