### ISSUE TITLE
kubectl krew errors 'Not supported by windows' message

### ISSUE THREAD

**Issue by EtaySchur** [kubernetes-sigs/krew#557]
I follow this issue https://github.com/kubernetes-sigs/krew/issues/463 , and although I have kubectl version 1.15.5 I'm still facing the same output "not supported by windows" ..
any ideas ? 

Environment:
kubectl client version = 1.15.5
krew version = 0.3.4
OS = Windows 10.0.18362

**Comment by ahmetb** [comment]
Try kubectl 1.16.x if you can. It seems like this issue wasn’t fixed until those versions. (According to issue 603 in kubectl repo.)

Closing since it’s not a krew issue. 
/close

**Comment by IsuruDilhan** [comment]
> Try kubectl 1.16.x if you can. It seems like this issue wasn’t fixed until those versions. (According to issue 603 in kubectl repo.)
> 
> Closing since it’s not a krew issue.
> /close

Updating to kubectl 1.16.+ worked for me.
