### ISSUE TITLE
Proposal: make `krew info` work with multiple indexes

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#559]
Since we had 1 index up until now, `krew index` had been fairly easy to implement. It did not distinguish between `Receipt`s or `Plugin`s (ref: `LoadManifestFromReceiptOrIndex`).

In other words, an "installed" plugin could only come from the Plugin manifest with the same name –as there were no other index.

So now, by allowing multiple indexes, `krew info` now has to understand if:

    krew info foo

means `foo` the installed plugin (could be from any index), or the `default/foo` uninstalled plugin.

-----

## Option 1

I recommend we change krew info’s behavior. `krew info foo` means:

- show info of `foo` installed plugin (could be from any index)
- show info of `foo` uninstalled plugin (from `default` index)

To disambiguate an "uninstalled" plugin, the user can run `krew info my-index/foo`. However, if `my-index/foo` is installed, could the user have meant show the "installed" plugin?

Keep in mind that `krew info` works on plugins installed via `--manifest` (i.e. has no index, but recorded as `default` with #555).

I'm losing my train of thought here.
If you see a straightforward solution, let me know.
/cc @corneliusweig 
cc: @chriskim06 
/kind proposal
/area multi-index

**Comment by ahmetb** [comment]
## Option 2

We change `krew info`'s behavior to only look at "available" plugins. It never looks at installed plugin receipts.

```sh
krew info foo # -> show default/foo
krew info my-index/foo
```

Advantages:

- easy to document for us, and easy to understand for users
- if we want to show if the plugin showed is_installed:true/false in "krew info" output, we can just query receipt by name and match the source index name.

Disadvantages:

- plugins installed but that don't exist in an index (i.e. installed via `--manifest`) (or index is deleted ==not supported) won't show here. I think it's an acceptable trade-off.

**Comment by corneliusweig** [comment]
I generally prefer option 2 over option 1, because it is more predictable and yields the same result regardless on which machine the command is executed on.

To make our user's lives easier, we can offer them some guidance when no manifest is found. For example, when looking for plugin `bar` from `my-index`:

```sh
$ krew info bar
Plugin `default/bar` does not exist. Did you mean `krew info my-index/bar`?
```

---

Lastly, the inconvenience about not being able to show info about plugins installed via `--manifest` is not a small thing IMO. Plugin devs will want to see how their info prints on screen and they should be able to. To enable this, we could add an option `--installed` that will force reading the manifest from the  receipts folder. WDYT?

**Comment by ahmetb** [comment]
> Lastly, the inconvenience about not being able to show info about plugins installed via `--manifest` is not a small thing IMO. Plugin devs will want to see how their info prints on screen and they should be able to. To that end, we could add an option `--installed` that will force reading the manifest from the receipts folder. WDYT?

I think for those people, I'd much rather prefer if `krew info --manifest` exists. :) That way, we make `info` work on `Plugin` concept only.

**Comment by corneliusweig** [comment]
Yeah, that's even better.
