### ISSUE TITLE
integration_test: RunOrFailOutput + RunOrFail is redundant

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#561]
I noticed that integration tests with `.RunOrFail()` actually fail not so useful error messages like `krew [index add]: exit error 255`.

Further exploration revealed that there's actually no value add of `.RunOrFail()`.

![image](https://user-images.githubusercontent.com/159209/77829857-efb83200-70e1-11ea-8cfa-50c21156cefd.png)

/good-first-issue
/help

**Comment by corneliusweig** [comment]
Isn't `Run()` used for situations where the `krew` command should actually fail? I think its behavior is required for our integration tests.
