### ISSUE TITLE
cleanup: Do not use path calculation in multi-index integration tests

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#562]
Right now the integration tests for TestKrewIndex** methods have:

	localIndex := test.TempDir().Path("index/" + constants.DefaultIndexName)

We should avoid guessing directory layouts in the test code, and in general.

`environment.Paths` type is supposed to calculate path segments.

It's advisable to move these to use:

    localIndex := environment.NewPaths(test.Root()).IndexPath(constants.DefaultIndexName)

after the multi-index switch can be removed. Otherwise these tests will also need os.Setenv + "defer os.Unsetenv" with `constants.EnableMultiIndexSwitch` to influence how environment.Paths computes paths.

cc: @chriskim06
/kind cleanup
/priority important-soon
/area multi-index

**Comment by chriskim06** [comment]
Should we switch these to use `environment.Paths`/`Setenv` and `Unsetenv` now? There's the item in #566 to remove the multi-index flag feature where the `Setenv` and `Unsetenv` could be cleaned up in the tests along with the `os.Getenv(...)` calls in the code.

**Comment by ahmetb** [comment]
Since it's tied to that this is probably one of the last items to do. But take it for a spin if you're sure we can churn through the list rather quickly.

**Comment by ahmetb** [comment]
@chriskim06 any ideas if this is addressed?

**Comment by chriskim06** [comment]
I haven''t started this yet, but should be able to get to it fairly soon.
