### ISSUE TITLE
CI fails when commit hashes starting with 0 are merged

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#571]
So we just merged 0571889 and the build says:

```
> Run hack/verify-installation.sh
Extracting krew from tarball.
Installing the krew build to a temporary directory.
[...]

WARNING: Detected stdin, but discarding it because of --manifest or args
F0329 06:20:14.510198    9214 root.go:79] failed to load plugin manifest from 
file: plugin manifest validation error: failed to parse plugin version: illegal 
zero-prefixed version component "0571889" in "v0.0.0-detached.0571889"
##[error]Process completed with exit code 255.
```

It seems like 

```
v0.0.0-detached.0571889
                ^^^^^^^
````

this is somehow a problem –which I never expected.

The error is coming from `semver.Parse` –and I'm not sure if https://semver.org dictates that stuff that comes after the `-` are supposed to be validated like this. If so, maybe we need to switch to `+` syntax.

It would be great if someone can take a look

/help
/good-first-issue
/kind flake
/priority backlog

**Comment by ahmetb** [comment]
> The error is coming from `semver.Parse` –and I'm not sure if https://semver.org dictates that stuff that comes after the `-` are supposed to be validated like this. If so, maybe we need to switch to `+` syntax.

from semver.org

> Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Build metadata MUST be ignored when determining version precedence. Thus two versions that differ only in the build metadata, have the same precedence. Examples: 1.0.0-alpha+001, 1.0.0+20130313144700, 1.0.0-beta+exp.sha.5114f85.

So yeah maybe we just need to build untagged commits with `+` to indicate commit.

**Comment by ericzhang08** [comment]
I'd like to do some contribution for this issue

**Comment by ahmetb** [comment]
Sounds good!
