### ISSUE TITLE
Krew uninstall behavior for multi-index

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#579]
With multi-index, plugins can come from different indexes. For example, we can have 

* `foo/bar`, plugin `bar` from index `foo` and
* `baz/bar`, plugin `bar` from index `baz`

These two plugins cannot be installed at the same time, because the plugin name `bar` is the same in both cases, and krew does not allow to rename plugins during install. In fact, when installing plugin `bar`, it becomes (almost) oblivious of its index source.

This opens the question, how plugins should properly uninstalled.

**Option 1**
Ignore the index source altogether. Every plugin is uninstalled by its plain plugin name, for example

```bash
krew uninstall bar  # could refer to foo/bar  or  baz/bar alike
```

Pro:
* easy to implement
* users are used to refer to the plugin as `bar` when they use it

Con:
* the commands to install and _un_install are not consistent

**Option 2**
Uninstall goes by its canonical name. For example,

```bash
krew uninstall foo/bar  # fails when baz/bar was installed
krew uninstall bar      # fails bc ambiguous
```

Pro:
* good consistency between uninstall/install commands

Con:
* hard to implement
* hard to use, because users need to find out the actual source of the plugin (`krew info`). Here we could help the users by saying "Did you mean `krew uninstall baz/bar`?"--again, more complexity.

**Option 3**
Uninstall accepts canonical and short names and just ignores the index part. For example

```bash
krew uninstall foo/bar   # succeeds even if baz/bar was installed
krew uninstall bar   # succeeds for baz/bar and foo/bar alike
```

Pro:
* easy to implement
* good consistency between install/uninstall commands

Con:
* can be confusing when mixing `krew install foo/bar` with `krew uninstall baz/bar`, which succeeds.

/cc @ahmetb @chriskim06 
/area multi-index
/kind proposal

**Comment by chriskim06** [comment]
#### Option 1
I think this doesn't require any change which is nice, but I agree that it could be confusing that install and uninstall would be different.

#### Option 2
I'm not sure that this would be too difficult to do. The receipt gets loaded in the uninstall code to verify that the plugin being uninstalled has been installed. I feel like it wouldn't take too many changes to check the index of the receipt and match it with what's being uninstalled.

Adding help text "did you mean `krew uninstall baz/bar`" definitely complicates it, but would be a nice usability feature.

#### Option 3
Agreed that consistency between install/uninstall is nice. I think it would be a little weird if someone does:
```
$ krew install baz/bar
$ krew uninstall foo/bar
```
and it succeeds. 

---

What about a hybrid of options 2 and 3? Something like this:
```
$ krew install foo/bar
---
$ krew uninstall bar # succeeds because only one "bar" can be installed at a time
$ krew uninstall foo/bar # succeeds because "bar" comes from index "foo"
$ krew uninstall baz/bar # fails because "bar" is not from "baz"
```

**Comment by ahmetb** [comment]
I'm currently leaning towards **Option 1**. The only shortcoming I see is the inconsistency between install vs uninstall –and I'm not too worried about it. Here's why:

- we can start less forgiving and be more forgiving in the future (if necessary)
  - however we can't start as forgiving then be more restrictive without breaking the experience
  - hybrid of 2&3 is _very_ forgiving, and actually is harder to implement
- if an user is running `kubectl foo` frequently, it comes natural to them to run `krew remove foo` and not worry about the source index
- if the user remembers the source index and runs `krew remove foo/bar` we can easily error out saying: `remove command does not support INDEX/PLUGIN syntax; just specify PLUGIN`
  - this is a _far easier_ check to implement than if `bar` comes from `foo`, and easily nudges the user in the right direction)
- if we implement aliasing/renaming so there can be multiple `bar`s installed in the future, we can easily allow INDEX/PLUGIN syntax and not break the existing implementation.

**Comment by corneliusweig** [comment]
There's an important point here: _if_ we are going to support aliasing for installed plugins, like `krew install foo/bar --as boo`, users will be accustomed to using the plugin as `kubectl boo`. Consequently, one should expect that uninstall goes by `krew uninstall boo` and not `krew uninstall foo/bar`.

AFAICT, everybody wants to support the short syntax without the index name (`PLUGIN` instead of `INDEX/PLUGIN`). So let's start with that as a baseline and if somebody complains about consistency, iterate from there.
Besides, when we anticipate how users _might_ use `uninstall` with the canonical name and print a helpful message what to do instead, we already take care of consistency (albeit in a crude way).

**Comment by ahmetb** [comment]
Got it I'm sending a PR shortly.

**Comment by chriskim06** [comment]
@ahmetb @corneliusweig do you guys think this can be closed now? `krew uninstall foo` works now for `default/foo` and `custom/foo`, and the warning message was just added when a user tries `krew uninstall custom/foo`.

**Comment by ahmetb** [comment]
/close
thanks!
