### ISSUE TITLE
Distribute plugins over OCI?

### ISSUE THREAD

**Issue by jdolitsky** [kubernetes-sigs/krew#580]
Hello! Just curious if there has been any discussion regarding Krew plugin distribution over OCI? 

It looks like the distribution mechanism relies on a new YAML format/type (krew.googlecontainertools.github.com/v1alpha2). I'm involved with the Helm project, and I've seen a simple repo index format after reaching some scale. While I'm sure the current setup works fine, it's defining yet another format which will need to be maintained, not only by this project but any tool that integrates with it.

If you're open to it, I could take a stab at making the distribution mechanism pluggable with OCI support.

**Comment by ahmetb** [comment]
@jdolitsky I'm currently not so positive as we are not having issues with the distribution format (zip/tarballs and a purpose-built simple yaml manifest).

We also have matured tooling on this model for developers such as release automation, and tools to test the manifests. I'm not sure if a change massive like that size can benefit us visibly at the cost of breaking things (given we have >80 plugins).

Do you mind providing some links/examples to how the payload and the manifest would look like? I'm currently imagining stuff like docker image manifests and layers, which would be harder to built for our user/dev community.

**Comment by jdolitsky** [comment]
If I'm understanding correctly, the tooling would not be affected. I'm not sure what the release mechanism is doing, but imagine same UX, different API under the hood.

You can  check out the Helm docs on OCI integration here: https://helm.sh/docs/topics/registries/

Towards the bottom of that doc is the format on content. Essentially the chart package is stored as a single layer on the manifest. Krew could easily do just the same, or expand on layers as needed.

The real downside is registries are typically live services - but technically a public registry could be entirely static. 

The reason I open this is that you're now facing how to address content trust. I think it would be in benefit for all Kubernetes users to have a shared strategy for general content trust and verification, and that conversation is going on right now as part of a Notary V2 effort. In CNCF there is a #notary-v2 channel dedicated to it.

The only foreseeable prerequisite of leveraging the notary v2 work is that your content is distributed over OCI.

Again - this issue is not that your distribution mechanism does not do it's job well (in fact, it seems pretty solid). The issue is that every package manager will face the exact same problems eventually. For example - what if somebody comes across and asks for support for private/protected krew indexes? Now you have to come up with a krew-specific auth solution. You will find that the Docker registry model has addressed all of these problems and OCI is continuing to build upon that model.

**Comment by jdolitsky** [comment]
As far as implementation on the code level, it's fairly easy to construct and push arbitrary layers using ORAS or containerd (which ORAS is built upon) https://github.com/deislabs/oras#oras-go-module-example

**Comment by trishankatdatadog** [comment]
Agreed with @jdolitsky! There are a few good reasons to target OCI as the distribution mechanism:

1. You get distribution for free with any OCI-compliant registry.
2. You also get security (content trust) for free with Notary v1 right now, and Notary v2 in the future.
