### ISSUE TITLE
Some Krew commands susceptible to path manipulation

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#581]
This is low-risk security issue so I'm opening it here.

While using `KREW_ROOT=~/.krew2`, I can still manipulate stuff in `~/.krew/` through the CLI by hijacking `PLUGIN` arguments with relative paths:

```
$ krew remove ../../.krew/receipts/whoami
Uninstalled plugin ../../.krew/receipts/whoami
```

This works even if `whoami` plugin is not installed in `~/.krew2` because we point to a valid receipt, which then gets deleted.

This happens because:
- `remove` command is not actually using `validation.IsSafePluginName` (like `LoadPluginByName` does) because it's operating on `Receipt`s
  - We actually added this check so that people don't use `name:` field in the plugin manifest to get random fs access.
- `environment.Paths` is vulnerable to manipulation because it doesn't do checks or return errors. I think this is by design

`krew index` cmds are not susceptible 
The methods who use LoadPluginByName fail correctly:

```
$ out/bin/krew-darwin_amd64 info ../../.krew/receipts/warp
F0401 11:02:03.677641   50768 root.go:79] failed to load plugin manifest: plugin name
"../.krew/receipts/warp" not allowed
```
```
out/bin/krew-darwin_amd64 upgrade ../../.krew/receipts/warp
Updated the local copy of plugin index.
F0401 11:04:52.552720   50879 root.go:79] failed to load the plugin manifest for plugin ../../.krew/receipts/warp: plugin name
"../.krew/receipts/warp" not allowed
```
```
out/bin/krew-darwin_amd64 install ../../.krew/receipts/warp
Updated the local copy of plugin index.
F0401 11:02:27.087157   50788 root.go:79] failed to load plugin "../../.krew/receipts/warp" from the index: plugin name
"../.krew/receipts/warp" not allowed
```

`krew index [add|remove]` are not susceptible to this as they use `IsValidIndexName` (although they do this check in pkg/indexoperations; not cmd/)

I propose we scan all cmds and validate plugin/index names with respective methods. The part that I'm not sure: should we do this in `cmd/` or `pkg/*`? Technically, cmd/ is a better place as it reduces test burden in lower layers.

**Comment by corneliusweig** [comment]
Oh no :(

Well this is input validation, so we should do it as early as possible, which means it should go somewhere into  the `cmd` package. Maybe we can even make cobra check this for us?

**Comment by ahmetb** [comment]
I've thought about a cobra check but there are cases like reading plugin list from `stdin` so I think let's just do it where we parse plugin names.
