### ISSUE TITLE
Sign krew.exe (This app might harm your device)

### ISSUE THREAD

**Issue by jozefizso** [kubernetes-sigs/krew#596]
As the **krew.exe** application is not signed with Authenticode certificate, it is reported as harmful application and it is not easy to download it and use it on Windows system.

<img width="311" alt="krew" src="https://user-images.githubusercontent.com/287778/80310950-72b1d280-87dd-11ea-9fdb-2c3eb50f0c47.png">

**Comment by ahmetb** [comment]
Do you commonly download open source software from GitHub and observer they are signed properly?

**Comment by jozefizso** [comment]
Yes, I do.

**Comment by ahmetb** [comment]
Got it. Do you mind investigating if binaries like kubectl are signed? If so, how are they doing so? I am afraid I don’t know how we would create a secure enough build env to sign binaries and ensure their long-term maintenance. The logistics around this currently scares me a bit.

**Comment by ahmetb** [comment]
@jozefizso Despite your report, it appears that `kubectl` also does not sign binaries. Without `kubectl` signed, there's no point of Krew trying to sign.

> ​Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk. App: kubectl.exe Publisher: Unknown publisher

/close

**Comment by jozefizso** [comment]
🤦🏻‍♂️ thanks for pro-customer approach 🖕
