### ISSUE TITLE
Explore accommodating kubectl plugins requiring Mac notarization

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#601]
https://soluble-ai.github.io/kubetap/kubetap_development/caveats/#krew-plugin page talks about:

> From my light browsing of the krew index it seems that all of the plugins are binary only. This is very unfortunate.
> 
> Due to the Mac notarization changes described above, kubetap will not have a krew plugin.

Opening this issue to track if there are any changes we can do to krew to accommodate this.

@eriner sorry about unsolicitedly pulling you in here. Do you mind explaining what do these notarization changes look like?

As far as I can tell `kubectl tap` is still a CLI plugin, and Krew doesn't rely on single-binary plugins at all. It can extract a zip/tarball to a directory and symlink to a particular executable (binary or script).

Many of the plugins in krew-index support macOS as a target without any problems.

**Comment by Eriner** [comment]
Mac executables must be notarized by Apple or you get a nasty warning and the only option is to trash the binary. This is a horrible experience that those installing from source do not have to deal with.

I **could** spend a whole bunch of time setting up goreleaser to use gon for notarization, but it feels like a whole bunch of extra work that I shouldn't need to do. And I mean that in the sense of distributing with krew - Complaints about Apple's enforcing binary notarization are neither here nor there.

Go makes it easy enough to install things from source, especially now that module support is improving.

**Comment by Eriner** [comment]
I guess as a hack (and oh boy, it would be one), I could release a krew plugin that has a script that does the following pseudocode:
```
if upToDate():
    exec kubectl-tap args[]
else:
    BuildBinary()
    exec kubectl-tap args[]
```

But AFAIK that's the only option that doesn't create a lot of work for me and make my releases dependent on Apple.

**Comment by Eriner** [comment]
And if the "solution" described above is indeed a viable and recommended solution, then building from source should just be made a first-class citizen either through plugin definition extensions or examples in documentation, but I haven't given it much thought.

**Comment by ahmetb** [comment]
> Mac executables that you didn't build from source yourself [must be notarized by Apple](https://developer.apple.com/news/?id=09032019a) or you get a nasty warning and the [only option is to trash the binary*](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macos/Catalina/macos-catalina-alert-unsigned.jpg).

Are you sure this happens for CLI tools executed from shells (kubectl plugins are like this).

If what you've said was true, no Go developer would be able to run the binaries they just compiled (that isn't notarized by Apple) on their macOS machine. But that's simply not the case.

For example `kubectl` itself is NOT notarized by Apple, yet it works fine. As far as I know `brew` formulas are not notarized by Apple, either.

Mac notarization applies to executables you double-click-to-execute (e.g. the packages in ~/Applications or /Applications). As far as I know your project isn't a desktop app, so users wouldn't need to double-click.

If `kubectl-tap` works with a `go get` as you listed in your README, it would work with krew.

**Comment by Eriner** [comment]
I refer you to the README of gon: https://github.com/mitchellh/gon

I just built the following executable on one laptop and airdroped it to another mac:
```
package main

func main() {
    fmt.Println("test")
}
```

This produces the following error: 
![notarize](https://user-images.githubusercontent.com/6919167/82957578-542c2c00-9f81-11ea-8039-e4b8b5df87bf.png)

**Comment by Eriner** [comment]
According to a friend I asked (and my testing with the kubectl binary, which indeed isn't signed but executes just fine) apparently this is a push vs pull thing, and airdrop marks as untrusted as it can push files without user interaction. But files downloaded with `wget` or `curl` or whatever can be run from CLI without issue, even when no code signing is present.

**Comment by Eriner** [comment]
Based on the above, I may be able to distribute without notarization or signing (and thus this ticket can be closed). I can't find any official documentation that states this, but I will do some experimentation.

**Comment by Eriner** [comment]
It seems that in addition to airdrop marking a file/archive as unequivocally untrusted, files downloaded by packaged apps (Chrome.app, Firefox.app) also mark the file/archive as "untrusted". In this context, once "untrusted" the CLI exception no longer applies.

**Comment by ahmetb** [comment]
> But files downloaded with `wget` or `curl` or whatever can be run from CLI without issue, even when no code signing is present.

Yeah. This is why you’re able to execute kubectl, or anything brew installs. Files downloaded via Chrome/Safari have certain xattrs set on them that causes macOS to detect this.

You should be able to package for krew just fine, let me know if I can help. Feel free to give it a try yourself as well, docs here: https://krew.sigs.k8s.io/docs/developer-guide/ Thanks for checking out.

/close

**Comment by Eriner** [comment]
Further testing shows I was wrong and I should have no issue distributing with krew. My previous understand was a misconception. Thanks for the ticket @ahmetb, hopefully others who may also be under the same false assumption will find this ticket. Cheers!
