### ISSUE TITLE
Update security warning for custom indexes

### ISSUE THREAD

**Issue by chriskim06** [kubernetes-sigs/krew#615]
Right now a security warning is printed anytime a plugin is installed/upgrade. This should be changed in the case of custom indexes to:
- the warning should be printed when the index is added
- plugin install/upgrade should only print the warning if the plugin is from the default index

Related to: #576 

/area multi-index

**Comment by ahmetb** [comment]
I recall our discussion was to perhaps move the warning to the `index add` and do not print for non-`default` indexes. My memory doesn't serve me well what we decided here.

**Comment by chriskim06** [comment]
Ah ok, I was probably misremembering. I can update this issue description to reflect that.

**Comment by chriskim06** [comment]
I was mainly adding this issue to keep track of the work for this, but if its ok to use the existing issue #576 then I'll close this and mention #576 in the PR.
