### ISSUE TITLE
Allow overriding `DefaultIndexURI` from an env variable

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes-sigs/krew#637]
We want to give operators who do not want to install from the default krew index the possibility to provide their own release branch of `krew`. For that, we should allow overriding the `DefaultIndexURI` from an env variable, e.g. `KREW_DEFAULT_INDEX_URI`.
Then operators can start using their own index (containing some krew plugin) from scratch. This will then also set up the default index and point to this custom index location.

- [ ] Implement override via env variable.
- [ ] Update the documentation for custom indices.

/cc @chriskim06

**Comment by ahmetb** [comment]
I'm supportive. This likely only benefits people who never want to touch krew’s own default.

**Comment by chriskim06** [comment]
Is this something we need before 0.4.0?

**Comment by ahmetb** [comment]
No, I think it can be done later.

**Comment by chriskim06** [comment]
Been busy this week, but I'll try to take a crack at this this weekend. I have a feeling integration testing might be interesting but I haven't taken a close look yet.

**Comment by chriskim06** [comment]
This completely fell off my radar, I'll try to get to this soon

/assign
