### ISSUE TITLE
unknown command "index" for "krew"

### ISSUE THREAD

**Issue by schizoid90** [kubernetes-sigs/krew#638]
I've been following the documentation here https://krew.sigs.k8s.io/docs/user-guide/custom-indexes/ but get an error when trying to add a custom index

```shell
kubectl krew index add myindex git@ssh.dev.azure.com:v3/MYORG/Kubernetes/kubernetes-plugins
F0824 15:35:00.602738   28934 root.go:77] unknown command "index" for "krew"
```
I'm on the latest version (as per github releases).

```
kubectl krew list krew
PLUGIN     VERSION
krew       v0.3.4
```

Is this a case of the documentation being ahead of the releases?

**Comment by ahmetb** [comment]
Sorry, yeah, we made a v0.4.0 release but had to roll back due to a critical bug we discovered in the last minute. We'll make a new release todya.

**Comment by ahmetb** [comment]
Should be resolved now, try `kubectl krew upgrade krew`.
/close
