### ISSUE TITLE
Consider add Go Vet tool in the CI

### ISSUE THREAD

**Issue by Dentrax** [kubernetes-sigs/krew#639]
Since we already use _golangci-lint_ static analysis in the _run-lint.sh_ file, adding the yet another static analysis tool _(a.k.a go vet)_ would still makes sense. In order to detect suspicious constructs (too see _registered analyzers_: `go tool vet help`), we should use that official tool. (We are still covering some cases, by using [.golangci.yaml](https://github.com/kubernetes-sigs/krew/blob/master/.golangci.yml) config file.)

**Comment by ahmetb** [comment]
I believe go vet is already run as part of that. Do you see any output from go vet?

**Comment by Dentrax** [comment]
As far as i know, go vet is not part of golangci. But it covers some of cases. I just opened a PR about this, btw. 🙃

**Comment by chriskim06** [comment]
It seems like it is part of golangci-lint https://golangci-lint.run/usage/linters/, but I think would have to be added to this list https://github.com/kubernetes-sigs/krew/blob/master/.golangci.yml#L40
