### ISSUE TITLE
created automatic chocolatey for krew 👏🏼

### ISSUE THREAD

**Issue by jetersen** [kubernetes-sigs/krew#645]
Hopefully other users on windows will find it helpful to write `choco install krew` once the package is available :)
https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1537

**Comment by corneliusweig** [comment]
We would prefer to keep control over the krew versions that get distributed, and thus prefer to install krew via krew. While installation via the users preferred package manager may look good for the initial install, it has disadvantages:

- first, it forces the krew maintainers to maintain multiple package managers that we cannot test and verify, and are not familiar with.
- second, the whole point of krew is to help our users to install kubectl plugins. Consequently, they have to get familiar with krew plugin installation anyway, and installing krew via krew is the very first step to learn the necessary commands.

Overall, it makes more sense to distribute krew via krew.

**Comment by jetersen** [comment]
This is just doing the initial install of adding krew cli on path and putting %USERPROFILE%\.krew\bin on path.

https://github.com/chocolatey-community/chocolatey-coreteampackages/pull/1537/files#diff-e088eb425b882eb52a4f2d9aa3ce7d55R7-R8

Makes `krew install krew` simpler 😉

**Comment by jetersen** [comment]
> first, it forces the krew maintainers to maintain multiple package managers that we cannot test and verify, and are not familiar with.
I don't see that point. No one asked you to maintain the chocolatey package. I choose to maintain, test and verify it.
I made this chocolatey package use the automatic updating when you release a new version GitHub so maintenance should be minimal.

> second, the whole point of krew is to help our users to install kubectl plugins. Consequently, they have to get familiar with krew plugin installation anyway, and installing krew via krew is the very first step to learn the necessary commands.
They will still have to run `krew install krew` the way the chocolatey package is setup.

The steps the chocolatey package does do for you is provide the executable for you, install it on path and adding `%USERPROFILE%\.krew\bin` on path.

I prefer to install my executable on windows using chocolatey.

**Comment by corneliusweig** [comment]
I see, thanks for explaining that. I have no experience with chocolatey and pretty much don't know how it works and what are its capabilities.

If I understand correctly, the choco package will install the latest `krew` in some chocolatey bin dir and adds a choco-managed entry `$HOME/.krew/bin` to windows PATH. You then recommend to run `krew install krew` to install krew into krew's plugin directory.

What I don't fully understand is the precedence of the PATH entries. If you run `krew` does it take the choco-installed binary, or the one from krew's bin dir? I suspect it is the choco one. I think if you uninstall the choco package, it also removes krew's bin dir from PATH and the users will not be able to run any plugins at all.

In essence, I suspect that users will be stuck forever with the krew version that got installed by chocolatey. And they won't get bugfixes unless they uninstall and re-install `krew` via chocolatey.

**Comment by jetersen** [comment]
Hmm while testing.

I noticed during install you like to log to stderr. Seems wrong as that would note an error.
In powershell with `$ErrorActionPreference = 'Stop'` it would immediately stop any executable as soon as you log to stderr.

https://github.com/kubernetes-sigs/krew/blob/7ba67155685d978c3661526ed5b9725425c42a97/cmd/krew/cmd/update.go#L174-L178

**Comment by corneliusweig** [comment]
Would it be possible to redirect stderr, so that powershell does not complain?

**Comment by jetersen** [comment]
Ya it is but there seems to be a mixture on when to log and when to write to stderr.

Fine
https://github.com/kubernetes-sigs/krew/blob/7ba67155685d978c3661526ed5b9725425c42a97/cmd/krew/cmd/install.go#L159-L162

Not to fine :)
https://github.com/kubernetes-sigs/krew/blob/f90ce36fb4b6bd81bf477eb7c9383e0cfeeefb26/cmd/krew/cmd/upgrade.go#L99-L102

**Comment by ahmetb** [comment]
Here's how we currently stand on third-party distributions:

We can't prevent it (e.g. homebrew packages). But we passively discourage use of other package managers. This is primarily because we ensure the install instructions listed in the docs works and up to date. (That's why we don't document other package managers.) Limiting the installation methods keeps maintenance burden manageable for us, the maintainers.

If you are willing to maintain it, go for it and create a Chocolatey or OneGet package. We probably won't be documenting that method, but anyone using Chocolatey can easily find it there (which is good enough).

If we decide to maintain own the Chocolatey package in the future (highly unlikely), we can consider transferring the ownership then (it's possible). But for now, the Kubernetes project overall doesn't package binaries (even kubectl) for other pkg managers.
