### ISSUE TITLE
no pods for deployment ingress-nginx-controller found in namespace ingress-nginx

### ISSUE THREAD

**Issue by herrywen-nanj** [kubernetes-sigs/krew#646]
I have installed Krew, but I can't use it. I have used deployment, but it doesn't work properly?My kubectl version is v18.6，The following is detail info
kubectl version:
![image](https://user-images.githubusercontent.com/33476935/93450689-d661a700-f908-11ea-991c-c644efcb7f80.png)

Error information:
![image](https://user-images.githubusercontent.com/33476935/93450795-f729fc80-f908-11ea-9bee-f353092cf3b1.png)

Why?

**Comment by ahmetb** [comment]
You're using ingress-nginx plugin, which is a different project. You should ask in their repo.
