### ISSUE TITLE
Show custom index on krew website

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-sigs/krew#661]
We have started maintaining our custom index for krew. https://github.com/appscode/krew-index .

We would be interested to list our plugins on the krew website. Is that something krew wants to do for custom indexes? If yes, how should we proceed?

Thanks.

**Comment by ahmetb** [comment]
One major reason that we have created a custom plugin indexes is that we get out of the business of maintaining such lists. 

Right now there are a few similar custom index repositories out there, however they contain one or two plug-ins, which are several orders of magnitude smaller than the krew-index.

There's a reason why we still maintain the krew-index repo, it provides great discoverability. However, we can't help other repos. 

Maybe we can create a repo tag on GitHub like "kubectl-plugin-index" or "krew-index" and recommend people to add that to their repos.

**Comment by tamalsaha** [comment]
Understood. May be ArtifactHub will start surfacing krew index also. Thanks.

**Comment by ahmetb** [comment]
First time I'm hearing artifacthub. Yeah krew repos are fairly easy to discover (using a bigquery dataset query etc) as they have a very specific structure. I suppose this is not a priority for us right now.

**Comment by tamalsaha** [comment]
I am not in on the all the politics around Hubs. But my understanding is that ArtifactHub wants to be the universal Hub for cloud native artifacts. So, it will be nice to have krew indexes show up there.

**Comment by tegioz** [comment]
You can now add your custom index repository to Artifact Hub @tamalsaha. For more details please see: https://artifacthub.io/docs/topics/repositories/#krew-kubectl-plugins-repositories.
