### ISSUE TITLE
Sanitize path, before comparing with krew binary folder

### ISSUE THREAD

**Issue by RouxAntoine** [kubernetes-sigs/krew#664]
Hi, 

First of all thanks for this plugin manager it is simple and really convenient. This issue is about warning display when i use krew : 

```
--> kubectl krew list
WARNING: To be able to run kubectl plugins, you need to add
the following to your ~/.bash_profile or ~/.bashrc:

    export PATH="${PATH}:${HOME}/.krew/bin"

and restart your shell.
```

This warning is due to my PATH variable which contain `$PATH:/home/user//go/projects/gopath/.krew/bin` => note double slash for example. And the code here : 
https://github.com/kubernetes-sigs/krew/blob/7ba67155685d978c3661526ed5b9725425c42a97/internal/environment/environment.go#L43-L47
and here : 
https://github.com/kubernetes-sigs/krew/blob/7ba67155685d978c3661526ed5b9725425c42a97/cmd/krew/cmd/internal/setup_check.go#L60-L64

who is not symmetric for bin and path directory. My proposal here https://github.com/RouxAntoine/krew/commit/97099d1d97aa332653b96aef6b63dd6d1041878b is to use function `filepath.Abs(dirInPATH)` to sanitize dir segment of PATH.

Do you think it's a good idea ? I also add unit test `TestIsBinDirInPATH_Custom` for demonstrate this case.

**Comment by corneliusweig** [comment]
That's a valid flaw and you analyzed it perfectly. Thanks for taking a look and the time to fix this.

**Comment by RouxAntoine** [comment]
Thanks I look to fix your PR review

**Comment by RouxAntoine** [comment]
Thanks I look to fix your PR review
