### ISSUE TITLE
Heavy handed path setting?

### ISSUE THREAD

**Issue by flickerfly** [kubernetes-sigs/krew#676]
The install docs say to set the path to:
"${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

Why put Krew at the front? This seems a bit heavy handed? Could it simply be put at the end? Is it overriding something in my path?

**Comment by ahmetb** [comment]
Shouldn't have any practical difference. Often, your path is entirely scanned before it's used in a shell environment like bash or zsh.

The only place it would make difference is if you install Krew with another package manager like Homebrew, having PATH set like this and running `krew install krew` would make the krew-installed version of krew being picked up first. (Sorry if I confused you there.)

If it cosmetically bothers people, we can always change.

**Comment by flickerfly** [comment]
Well, it is more that it leaves a question of what is being hidden because anything in $HOME/.krew/bin would override anything else in the path. For example, the project could create a file `$HOME/.krew/bin/less` that would then be used to override the use of the proper system `less`. This is a common type of thing done in attacks to swap out a program for another that when run looks the same, but does some extra work behind the scenes as the unsuspecting user using their privileges.

**Comment by ahmetb** [comment]
Krew creates files under `bin/` with only `kubectl-` prefix for obvious reasons. :)

However, moving it to the end on the PATH only partially mitigates such a potential risk. For example, many scripts look for `gsed` then falls back to `sed`. Such a malicious process, despite being at the end, could still get picked up.

So this alone is not a great reason to move it to the end. It doesn't help reduce any threat vector. If you have another argument.

**Comment by flickerfly** [comment]
What's to prevent some other process outside krew from adding something ~/.krew/bin?

**Comment by ahmetb** [comment]
If you have concerns with respect to the writeable nature of the ~/.krew/bin, you can use KREW_ROOT to change the install path to a less writable location. https://krew.sigs.k8s.io/docs/user-guide/advanced-configuration/#custom-install-dir However, I think if a process has full RW access to your home directory, you might have larger issues. 

Overall you'd be installing unaudited plugins with Krew, and we present that security risk. With that sort of risk factor in place, I'm not sure if addressing this is worthwhile.

**Comment by flickerfly** [comment]
Okay, thanks for sharing your thoughts on the matter.
