### ISSUE TITLE
Linux installation error

### ISSUE THREAD

**Issue by gkumarchilakala** [kubernetes-sigs/krew#680]
I facing the below error while trying to install the krew on the Oracle Linux 7.9, Need Help in fixing the error.

**Output of the Install command execution:**

++ mktemp -d
+ cd /tmp/tmp.Xb9SycXFBM
+ curl -fsSLO -k https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz
+ tar zxvf krew.tar.gz
./LICENSE
./krew-darwin_amd64
./krew-linux_amd64
./krew-linux_arm
./krew-windows_amd64.exe
++ uname
++ tr '[:upper:]' '[:lower:]'
++ uname -m
++ sed -e s/x86_64/amd64/ -e 's/arm.*$/arm/'
+ KREW=./krew-linux_amd64
+ ./krew-linux_amd64 install krew
Adding "default" plugin index from https://github.com/kubernetes-sigs/krew-index.git.
F1231 21:14:46.491711    4760 root.go:79] failed to add default plugin index in absence of no indexes: command execution failure, output="Cloning into '/home/gse/.krew/index/default'...\nfatal: unable to access 'https://github.com/kubernetes-sigs/krew-index.git/': Peer's certificate issuer has been marked as not trusted by the user.\n": exit status 128

**Comment by ahmetb** [comment]
Your root certs are not properly working. It can’t query github.com as you see. We can’t do anything for you.
/close

**Comment by gkumarchilakala** [comment]
Appreciate the quick response @ahmetb
