### ISSUE TITLE
Windows 10 WSL - "cannot allocate memory" when calling krew commands

### ISSUE THREAD

**Issue by tace** [kubernetes-sigs/krew#682]
Windows 10 1809 and WSL1, most of krew calls I get "**cannot allocate memory**". 
I'm using ConEmu terminal.

**Comment by ahmetb** [comment]
I think you're hitting a quite old bug (regarding executing plugins) that existed in old versions of kubectl.

https://github.com/kubernetes/kubectl/issues/603#issuecomment-569646963

**Comment by tace** [comment]
My kubectl version is v1.19.3
