### ISSUE TITLE
Explore use of t.TempDir()

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#696]
Go 1.15 started offering t.TempDir() function https://golang.org/doc/go1.15#io/ioutil
We can now deprecate our implementation of `testutil.NewTempDir(t)`.

/help-wanted
/good-first-issue

**Comment by Evalle** [comment]
Hi, I would like to contribute.
/assign

**Comment by ahmetb** [comment]
@Evalle go for it! thanks for signing up.
