### ISSUE TITLE
Installing krew - failed to list indexes

### ISSUE THREAD

**Issue by Stefanqn** [kubernetes-sigs/krew#706]
```zsh
❯ "$KREW" install krew
Adding "default" plugin index from https://github.com/kubernetes-sigs/krew-index.git.
F0331 09:44:31.046373   23043 root.go:79] failed to list indexes: failed to list the remote URL for index default: command execution failure, output="": exit status 1
```

```zsh
❯ curl  https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz
<html><body>You are being <a href="https://github.com/kubernetes-sigs/krew/releases/download/v0.4.1/krew.tar.gz">redirected</a>.</body></html>
```

```zsh
❯ kubectl version                                                                                            
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2021-01-13T22:07:54Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
```

```zsh
❯ uname -a                                                                                                  
Linux xxx-P15v 5.12.0-1-MANJARO #1 SMP PREEMPT Sun Mar 14 21:56:45 UTC 2021 x86_64 GNU/Linux
```

**Comment by ahmetb** [comment]
I cannot reproduce this in an `ubuntu` container from Docker Hub that has `git` and `curl` installed. The installation command over at https://krew.sigs.k8s.io/docs/user-guide/setup/install/ works fine.

**Comment by Stefanqn** [comment]
ok, I found the issue. 

krew installation does not handle `[GIT_CONFIG` ](https://git-scm.com/docs/git-config) properly. Prefix the installation command with `export GIT_CONFIG=` to reproduce.

**Comment by ahmetb** [comment]
We just shell out to `git`, but we don't pass environment variables to it. I don't know if git has full list of env vars, but I couldn't find GIT_CONFIG [here](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables), it seems to be appearing on the man-page you linked.

I suspect [certain variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) like `GIT_CONFIG` might be helping some users to configure proxies etc to make `krew` work on their machines, however some other variables like `GIT_DIR` can meddle with how `krew` works internally and create a non-uniform setup for users (I'm not sure if we care much about this).

Maybe the way to go here is to let `krew` pass existing environment variables down to `git`, so users can have a control over the underlying process. (Downside is the users might be unaware that krew uses "git" and they might break themselves and not notice why it's not working.) You’re the first one to report this issue.

/kind bug
/priority P3

**Comment by Stefanqn** [comment]
This is the interesting part, I don't use GIT_CONFIG for connection settings. 

I use it to switch git configs (diff tools, newline handling) for different computers, with shared, versioned dot files.

To emphazise, 
a) without any gitconfiguration, krew works fine,
b)  with the gitconfiguration, which I referred to in `GIT_CONFIG`, krew works fine
c) just if I set `GIT_CONFIG` to any value, even empty, krew fails.

**Comment by shyr** [comment]
I also faced the same issue. After deleting ~/.krew directory, and try to install it agin. For me, it worked.

**Comment by MaitreDede** [comment]
Hi,
With release v0.4.1 (using bash script from doc setup/install on debian buster amd64):
```
damien@damien:~/.krew$ (
>   set -x; cd "$(mktemp -d)" &&
>   OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
>   ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
>   curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
>   tar zxvf krew.tar.gz &&
>   KREW=./krew-"${OS}_${ARCH}" &&
>   "$KREW" install krew
> )
++ mktemp -d
+ cd /tmp/tmp.uGRvPNxmhA
++ uname
++ tr '[:upper:]' '[:lower:]'
+ OS=linux
++ uname -m
++ sed -e s/x86_64/amd64/ -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
+ ARCH=amd64
+ curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz
+ tar zxvf krew.tar.gz
./LICENSE
./krew-darwin_amd64
./krew-darwin_arm64
./krew-linux_amd64
./krew-linux_arm
./krew-linux_arm64
./krew-windows_amd64.exe
+ KREW=./krew-linux_amd64
+ ./krew-linux_amd64 install krew
Adding "default" plugin index from https://github.com/kubernetes-sigs/krew-index.git.
F0614 08:05:04.562785 1809220 root.go:79] failed to add default plugin index in absence of no indexes: command execution failure, output="Clonage dans '/home/damien/.krew/index/default'...\nfatal: impossible d'accéder à 'https://github.com/kubernetes-sigs/krew-index.git/'\u00a0: Failed sending HTTP2 data\n": exit status 128
```

**Comment by ahmetb** [comment]
@MaitreDede I don't have french but it's likely a connectivity issue on your end. Nothing we can fix here.
