### ISSUE TITLE
Krew install issue

### ISSUE THREAD

**Issue by woodliu** [kubernetes-sigs/krew#708]
Hi, This is my first time useing krew. I download the krew and run the command below, it return err:
```
# ./krew-linux_amd64 version
This version of Krew is not supported anymore. Please manually migrate:
1. Uninstall Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/uninstall/
2. Install latest Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/
3. Install the plugins you used
F0507 18:38:59.829652   49426 root.go:79] krew home outdated
```

This is my sys info:
```
# uname -a
Linux ubuntu 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Because the network issue, I want install manually, thanks!

**Comment by ahmetb** [comment]
Please follow installation instructions. Running a binary alone like that can have issues.

**Comment by woodliu** [comment]
> Please follow installation instructions. Running a binary alone like that can have issues.

Hi, This is may be the reason. Thanks!
Do you have a plan that support install Krew manually?

**Comment by ahmetb** [comment]
Our installation script is a spelled out manual installation already. I think you just need to run "krew update" command on the binary.

**Comment by abinet** [comment]
Have same issue with latest windows binary downloaded
PS C:\Users\USER> krew version
This version of Krew is not supported anymore. Please manually migrate:
1. Uninstall Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/uninstall/
2. Install latest Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/
3. Install the plugins you used
F0519 13:15:38.360932   75436 root.go:79] krew home outdated
