### ISSUE TITLE
Can Krew support the installation of local plug-in packages

### ISSUE THREAD

**Issue by myxxhui** [kubernetes-sigs/krew#709]
How do I install plug-ins offline

![image](https://user-images.githubusercontent.com/69575321/123601296-1788cf00-d82a-11eb-8118-7360a319c9a8.png)

**Comment by ahmetb** [comment]
You can install them with --manifest and --archive options but these are not meant for end-users who are using plugins (these options are for plugin developers). If you use these, the plugins will not get updates.

**Comment by corneliusweig** [comment]
I think this question has been resolved, right? If it wasn't, please leave a note and we'll reopen.
/close
