### ISSUE TITLE
Unable to update to the lastest stable release on macOS 11.6

### ISSUE THREAD

**Issue by conradwt** [kubernetes-sigs/krew#723]
When I enter:

```zsh
➜ (
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
  tar zxvf krew.tar.gz &&
  KREW=./krew-"${OS}_${ARCH}" &&
  "$KREW" install krew
)
```

I'm getting the following:

```text
+-zsh:3> mktemp -d
+-zsh:3> cd /var/folders/vc/sbw5khnx29lfhppt4cmbxqmc0000gn/T/tmp.950Ig17Q
+-zsh:4> OS=+-zsh:4> uname
+-zsh:4> OS=+-zsh:4> tr '[:upper:]' '[:lower:]'
+-zsh:4> OS=darwin 
+-zsh:5> ARCH=+-zsh:5> uname -m
+-zsh:5> ARCH=+-zsh:5> sed -e s/x86_64/amd64/ -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
+-zsh:5> ARCH=amd64 
+-zsh:6> curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz
curl: (22) The requested URL returned error: 404
```

**Comment by chriskim06** [comment]
ah there's an [open PR](https://github.com/kubernetes-sigs/krew/pull/700) currently for updating the install instructions after a change was made for [releasing separated archives for each platform](https://github.com/kubernetes-sigs/krew/pull/699). if you already had krew installed then the usual `kubectl krew upgrade` should upgrade it properly. for new installs the instructions will be updated

**Comment by conradwt** [comment]
@chriskim06 `kubectl krew upgrade` does upgrade `krew`.  However, the documentation says that this command would `upgrade installed plugins to newer versions`.  Is this documentation missing from the `help` option or should there be another option for `krew` updating itself?
