### ISSUE TITLE
site: plugin list Loading... row never disappears

### ISSUE THREAD

**Issue by ahmetb** [kubernetes-sigs/krew#729]
The "Loading..." row remains even after the plugins are loaded.

/kind bug
/area docs
/priority P3
/help
/good-first-issue

![image](https://user-images.githubusercontent.com/159209/138008052-8ba6cb6a-b593-4dff-b5e8-5324531de330.png)

**Comment by zhengtianbao** [comment]
I would like to take this up as my first issue.
/assign @zhengtianbao
