### ISSUE TITLE
krew.sh install is broken

### ISSUE THREAD

**Issue by kwsorensen** [kubernetes-sigs/krew#731]
According to https://krew.sh/ we should be able to install krew with the following... 
```
curl https://krew.sh/ | bash
```

However it gets the following output

```
curl https://krew.sh/ | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2115    0  2115    0     0   8359      0 --:--:-- --:--:-- --:--:--  8359
curl: (22) The requested URL returned error: 404 
tar (child): krew.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by chriskim06** [comment]
I believe this isn't an officially supported installation method by the krew team. IIRC this is something added by Replicated that we don't maintain. We recently changed the archives we publish with releases and this script is trying to use the old one. I'll try looking for the repo for it to file an issue.

/cc @laverya

I think you filed an issue awhile back about this mentioning krew.sh

**Comment by corneliusweig** [comment]
As a side-note: krew.sh is not an officially supported installation method. It is a community contribution and bugs should be filed there.
