### ISSUE TITLE
List fails without default index

### ISSUE THREAD

**Issue by Junnplus** [kubernetes-sigs/krew#750]
```
[N] ❯ kubectl krew list
F1230 10:47:56.057894   30356 root.go:79] krew local plugin index is not initialized (run "kubectl krew update")
```

I still have the same problem after update.

list command always check default index, but update command will skip add default when found other index. https://github.com/kubernetes-sigs/krew/blob/master/cmd/krew/cmd/update.go#L139-L142

**Comment by ahmetb** [comment]
Thanks for the report. Do I understand your use case correctly:

- install krew
- krew index add $other-index
- krew list: fails with the error you mentioned?

**Comment by Junnplus** [comment]
@ahmetb Yes, I need other index to install plugin.

**Comment by ahmetb** [comment]
Thanks that must be an oversight. We should allow using krew without the default index. 

/kind bug
/area multi-index

**Comment by Junnplus** [comment]
> We should allow using krew without the default index. 

I agree with you. The default index is not required. 
So i make a [PR](https://github.com/kubernetes-sigs/krew/pull/751) to check existing index.
