### ISSUE TITLE
Unable to install Krew on Linux

### ISSUE THREAD

**Issue by Hector242** [kubernetes-sigs/krew#752]
Hello Team,

I'm trying to install Krew on a Linux server, but I got the following error messages.
 
[root@vts~]# (
>   set -x; cd "$(mktemp -d)" &&
>   OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
>   ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
>   KREW="krew-${OS}_${ARCH}" &&
>   curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
>   tar zxvf "${KREW}.tar.gz" &&
>   ./"${KREW}" install krew
> )
++ mktemp -d
+ cd /tmp/tmp.q0JygZVSfi
++ uname
++ tr '[:upper:]' '[:lower:]'
+ OS=linux
++ uname -m
++ sed -e s/x86_64/amd64/ -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/'
+ ARCH=amd64
+ KREW=krew-linux_amd64
+ curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/latest/download/krew-linux_amd64.tar.gz
+ tar zxvf krew-linux_amd64.tar.gz
./LICENSE
./krew-linux_amd64
+ ./krew-linux_amd64 install krew
-bash: ./krew-linux_amd64: Permission denied.

Checking the tmp file I noticed that the script file is taking another user as it's owner. However, I did try to change the owner to root, but I'm still getting the same error messages. 

[root@vts~]# cd /tmp/tmp.q0JygZVSfi/
[root@vts tmp.q0JygZVSfi]# ls -l
total 15980
-rwxr-xr-x. 1 redhat  121 12164162 Dec 31  1999 krew-linux_amd64
-rw-r-----. 1 root   root  4186018 Jan  3 17:16 krew-linux_amd64.tar.gz
-rw-r--r--. 1 redhat  121    11358 Dec 31  1999 LICENSE
[root@vts tmp.q0JygZVSfi]# 

Thanks in advance,
Best.

**Comment by guettli** [comment]
I just had the same issue. I think it is related to some security-feature that you are not allowed to execute files from /tmp.

I copied the file to /var/tmp, and there it was executable.

**Comment by ahmetb** [comment]
> I think it is related to some security-feature that you are not allowed to execute files from /tmp.

I'd be interested in what that security feature is. If anyone knows, please add a comment. I am able to do `docker run --rm alpine` + `apk add curl git` and install Krew in there just fine. So I assume this is not a standard thing.

**Comment by NimbleArchitect** [comment]
it sounds like SELinux could be blocking it but without knowing more details like the distribution its hard to guess at

**Comment by ahmetb** [comment]
/close
not reproducible. please feel free to open a new issue if you have a clean repro.
