### ISSUE TITLE
change default name of ingress-nginx plugin

### ISSUE THREAD

**Issue by rthamrin** [kubernetes-sigs/krew#764]
normal command

```kubectl ingress-nginx backends -n ingress```

error
```no pods for deployment ingress-nginx-controller found in namespace ingress```

my deployment name is ```ingress-controller-nginx-ingress-controller-default-backend```
is it possible to ask the krew ingress-nginx to recognize my deployment name? I am also thinking to change my ingress-Nginx deployment name but doubt if it will ruin my other services.

thank you.

**Comment by rajatjindal** [comment]
This issue should be reported in ingress nginx repo. On a side note, i believe it already supports using a different name.
