### ISSUE TITLE
Bump up to Go 1.18

### ISSUE THREAD

**Issue by JohnTitor** [kubernetes-sigs/krew#778]
Is there a policy about bumping up Go version? If not, I'm happy to do it.

**Comment by ahmetb** [comment]
Should be OK.

**Comment by JohnTitor** [comment]
Okay, I investigated this and found some blockers. The first is some lints in golangci-lint don't support Go 1.18. In our case, `structcheck` and `unparam` don't. _I think_ this should be fine as our codebase isn't changed so frequently.
The second is, to get golangci-lint's Go 1.18 support, we have to bump up it to 1.45.0 or higher. This itself isn't a problem but https://github.com/daixiang0/gci/issues/54 is. It reports some false positives, see https://github.com/JohnTitor/krew/runs/6422270074?check_suite_focus=true for example. I checked golangci config and I found we also use goimports. I think it's enough to format/order imports and could remove gci. Is there a reason to have gci here?

**Comment by JohnTitor** [comment]
Still needs an update from golangci-lint, /remove-lifecycle stale

**Comment by JohnTitor** [comment]
Superseded by #801

**Comment by JohnTitor** [comment]
https://github.com/kubernetes-sigs/krew/pull/801 will resolve this but not yet.
/remove-lifecycle stale
