### ISSUE TITLE
GitHub Release's body isn't rendered as Markdown

### ISSUE THREAD

**Issue by JohnTitor** [kubernetes-sigs/krew#780]
See https://github.com/kubernetes-sigs/krew/releases/tag/v0.4.3. https://github.com/kubernetes-sigs/krew/releases/tag/v0.4.2 is rendered correctly, so there should be something between them.

![image](https://user-images.githubusercontent.com/25030997/168051811-2dfd9ca5-0ffd-4b5b-b541-86f0dfed450a.png)

**Comment by ahmetb** [comment]
That's a GitHub issue I think. Someone needs to manually copy those notes, click Edit on the release and paste them again, then it actually becomes markdown.

**Comment by JohnTitor** [comment]
I see, I'm going to check if there's a way to tell GitHub that it's markdown.

**Comment by JohnTitor** [comment]
Okay I found the cause. So, the problem is we don't pass the notes to GitHub but only include them in the git tag. GitHub will render the passed body as Markdown but if the body is empty, they will instead use git tag's description as plain text.
For instance, if we pass the body like https://github.com/2k36/krew/commit/d1e569affd4b68499afecdd2a8eda4e7f2418e90, the notes are rendered intentionally: https://github.com/2k36/krew/releases/tag/v0.100.4
I'm happy to include this change to #781 if you'd like :)

**Comment by ahmetb** [comment]
Yeah that'd be appropriate!
