### ISSUE TITLE
failed to install some plugins: [examples]: plugin "examples" does not offer installation for this platform

### ISSUE THREAD

**Issue by mahesh2121** [kubernetes-sigs/krew#797]
installing plugin using krew 

CRI used here Docker desktop

C:\Users\mahes\Desktop\ckaexample>kubectl krew install cs/examples
Updated the local copy of plugin index "cs".
Updated the local copy of plugin index.
Installing plugin: examples
W0903 14:20:54.589626    8384 install.go:164] failed to install plugin "examples": plugin "examples" does not offer installation for this platform
failed to install some plugins: [examples]: plugin "examples" does not offer installation for this platform
Error: exit status 1

**Comment by ahmetb** [comment]
You need to file these issues in plugin repos not here. 
/close
