### ISSUE TITLE
:scroll:  Documentation > BASH > no more session close required

### ISSUE THREAD

**Issue by adriens** [kubernetes-sigs/krew#805]
# :grey_question: Context

Currently, the [documentation](https://krew.sigs.k8s.io/docs/user-guide/setup/install/) tells to restart the shell : 

![image](https://user-images.githubusercontent.com/5235127/192126673-49c2969b-4349-400c-90e3-5d3db98c0557.png)

which can be annoying in some situations.

# :bulb: Proposal

Therefore sourcing the `.profile` should ne enough.

**Comment by adriens** [comment]
:point_right:  See #806 for more

**Comment by ahmetb** [comment]
I don't have a .profile file. I think it's a lot cleaner to just restart the shell. Not all bashrc/zshrc/profile files are idempotent either (they're meant to be run once per session, otherwise can have unexpected results). I don't see a clear value-add here either.

**Comment by adriens** [comment]
:+1:
