### ISSUE TITLE
Unable to install pod-lens plugin

### ISSUE THREAD

**Issue by kesavakadiyala** [kubernetes-sigs/krew#807]
Unable to install pod-lens, getting below error. Is there any alternative solution for this.

[kke:~] kubectl krew install pod-lens
Updated the local copy of plugin index.
Installing plugin: pod-lens
W1013 15:03:52.422199 3468 install.go:164] failed to install plugin "pod-lens": plugin "pod-lens" does not offer installation for this platform
failed to install some plugins: [pod-lens]: plugin "pod-lens" does not offer installation for this platform

[kke:~] uname -a
Linux kke 5.10.124-linuxkit https://github.com/jpriebe/kubectl-pod-inspect/issues/1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022 aarch64 GNU/Linux

[kke:~] kubectl krew version
OPTION VALUE
GitTag v0.4.3
GitCommit dbfefa5
IndexURI https://github.com/kubernetes-sigs/krew-index.git
BasePath /root/.krew
IndexPath /root/.krew/index/default
InstallPath /root/.krew/store
BinPath /root/.krew/bin
DetectedPlatform linux/arm64

**Comment by ahmetb** [comment]
Please file this issue in plugin's repo. This is not the place for issues about individual plugins. 
/close
