### ISSUE TITLE
Windows installation KREW fails due to missing file "v0.4.3/krew-windows_amd64.tar.gz" releases download

### ISSUE THREAD

**Issue by SatheesP** [kubernetes-sigs/krew#808]
Dear Team,

C:\Users\<id>\.krew>krew install krew
←[31;1mWARNING: ←[0mTo be able to run kubectl plugins, you need to add the
"%USERPROFILE%\.krew\bin" directory to your PATH environment variable
and restart your shell.

Adding "default" plugin index from https://github.com/kubernetes-sigs/krew-index.git.
Updated the local copy of plugin index.
Installing plugin: krew
W1020 11:20:06.504415   16392 install.go:164] failed to install plugin "krew": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": Get "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": dial tcp: lookup github.com: no such host
F1020 11:20:06.506060   16392 root.go:79] failed to install some plugins: [krew]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": Get "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": dial tcp: lookup github.com: no such host
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000006001, 0xc000076b40, 0x1c8, 0x21d)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1021 +0xbf
k8s.io/klog/v2.(*loggingT).output(0xda6b40, 0xc000000003, 0x0, 0x0, 0xc0001a2070, 0xb0e31e, 0x7, 0x4f, 0x2ee800)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:970 +0x19b
k8s.io/klog/v2.(*loggingT).printDepth(0xda6b40, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00004ee90, 0x1, 0x1)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:733 +0x185
k8s.io/klog/v2.(*loggingT).print(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:715
k8s.io/klog/v2.Fatal(...)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1489
sigs.k8s.io/krew/cmd/krew/cmd.Execute()
        /home/runner/work/krew/krew/cmd/krew/cmd/root.go:79 +0x257
main.main()
        /home/runner/work/krew/krew/cmd/krew/main.go:25 +0x4b

goroutine 6 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0xda6b40)
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:1164 +0x92
created by k8s.io/klog/v2.init.0
        /home/runner/go/pkg/mod/k8s.io/klog/v2@v2.8.0/klog.go:418 +0xe5

-Sathees

**Comment by ahmetb** [comment]
If retrying doesn't fix, it's a problem with your machine/network. It shows that it's failing to connect github.com. 

/kind support
/close
