### ISSUE TITLE
windows power shell - tried to install krew but same issue

### ISSUE THREAD

**Issue by SatheesP** [kubernetes-sigs/krew#809]
Dear Team,

I have no idea why it is failing (git clone other commands are working in my corporate environment)

PS C:\dumps\cloud-btp> .\krew install krew
Updated the local copy of plugin index.
Installing plugin: krew
W1020 13:18:19.177151   16480 install.go:164] failed to install plugin "krew": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": Get "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": dial tcp: lookup github.com: no such host
failed to install some plugins: [krew]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": Get "https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz": dial tcp: lookup github.com: no such host

Please give me any other manual configurations are available or any other steps to follow.

-Sathees

**Comment by ahmetb** [comment]
Please stop opening a new issue, you can continue on the old issue. Does "curl https://github.com/" work? If not, please close this issue.
