### ISSUE TITLE
Krew completion (for fish, likely others as well) only works if ln -s kubectl-krew krew, and even then not in kubectl krew

### ISSUE THREAD

**Issue by vorburger** [kubernetes-sigs/krew#810]
#769 similar issue

When installing krew as per https://krew.sigs.k8s.io/docs/user-guide/setup/install/, for Fish (but it's likely similar for other shells),

and then activating completion like this:

    $HOME/.krew/bin/kubectl-krew completion fish > $HOME/.config/fish/completions/kubectl-krew.fish

then `kubectl krew ...` still doesn't auto-complete. However if doing:

    ln -s $HOME/.krew/bin/kubectl-krew $HOME/.krew/bin/krew

then at least `krew ...` auto-completes.

**Comment by vorburger** [comment]
> and then activating completion like this:

as suggested to be added to the doc in #811, as at least a first step

**Comment by ahmetb** [comment]
Krew doesn't offer completion, because kubectl plugins don't support completion yet.

If it appears like krew does have completion scripts, it's a side effect of the library we use, not by design.

/close

**Comment by chriskim06** [comment]
also the next time we publish a new version the `completion` command won't be there https://github.com/kubernetes-sigs/krew/pull/771

**Comment by maelvls** [comment]
With the latest kubectl version (1.26), the kubectl plugins completion now works!

To enable completion for `kubectl krew`, run the following commands:

```bash
echo '#!/bin/sh\nkubectl krew __complete "$@"' >~/.krew/bin/kubectl_complete-krew
chmod u+x ~/.krew/bin/kubectl_complete-krew
```

**Comment by ahmetb** [comment]
@maelvls we should probably implement a native feature for this in the plugin manifest. Do you mind opening a separate issue so I don't forget?

**Comment by maelvls** [comment]
I think https://github.com/kubernetes-sigs/krew/issues/812#issue-1439452083 covers this 👍
