### ISSUE TITLE
kubectl krew install oidc-login

### ISSUE THREAD

**Issue by noedadon** [kubernetes-sigs/krew#813]
Just installed krew on Windows 10, tried to instal oidc-login, getting : 

failed to retrieve plugin indexes: failed to list the remote URL for index default: command execution failure, output="": exit status 1
Error: exit status 1

**Comment by noedadon** [comment]
had to open powershell as admin

**Comment by chaoscreater** [comment]
Works as admin but it's annoying having to run Powershell as admin (even though I have quick ways of doing so). Surely installing plugins doesn't require UAC elevation.
