### ISSUE TITLE
krew is getting uninstalled after restarting the linux server

### ISSUE THREAD

**Issue by teja-rafay** [kubernetes-sigs/krew#818]
After installing when I restart my linux machine the krew is getting uninstalled

**Comment by ahmetb** [comment]
Sorry that's not enough information for me to understand what is going on. Most likely it's a behavior with your set up. Krew is installed in `$HOME/.krew` and if it's disappearing on every restart, there's nothing much we can help with, since it sounds like it's specific to your set up.

/kind support

**Comment by teja-rafay** [comment]
Is there any way we can check this if it is the problem with my setup or something else?

**Comment by ahmetb** [comment]
You can `ls -al $HOME`, see if `.krew` is there, and see if it persists between reloads.

Another issue might be that you did not update your shell profile file with the `export PATH` command after installation, as instructed in the installation instructions.

You can try reinstalling and follow the post-installation instructions more closely.

/close

**Comment by teja-rafay** [comment]
I checked with `ls -al $HOME`, .krew is present. I also did export it a post installation steps and after that when I restart the system it is saying `ubuntu@teja-20230202-1-18-1-21:~$ kubectl krew
Error: unknown command "krew" for "kubectl"
Run 'kubectl --help' for usage.`

**Comment by ahmetb** [comment]
Sorry but I recommend seeking help at other forums to troubleshoot shell/PATH issues. :) If `kubectl-krew` binary is not in your PATH and you are unsure how to check, plenty of resources available on the web.

**Comment by teja-rafay** [comment]
the binary is present in my path
