### ISSUE TITLE
download failures are interpreted as checksum mismatch

### ISSUE THREAD

**Issue by daniel-garcia** [kubernetes-sigs/krew#819]
The krew client ignores the status code. This results in misleading errors that show a checksum mismatch when in fact the artifact was never downloaded. According to the go documentation:

```A non-2xx response doesn't cause an error```

**Comment by ahmetb** [comment]
Agreed. Feel free to send a PR. I think we can check for non-200 codes as we expect the client to follow redirects and eventually hit an HTTP 200 OK.

**Comment by daniel-garcia** [comment]
I have a pr here #820
