### ISSUE TITLE
Error:  Flag --kubeconfig is not supported

### ISSUE THREAD

**Issue by mashetty330** [kubernetes-sigs/krew#826]
I'm trying to understand why the krew plugins don't support --kubeconfig flag? Is there a particular reason for this design?
having support for the --kubeconfig flags would be really helpful

**Comment by ahmetb** [comment]
That's how kubectl plugin model is designed. Plugins don't inherit flags from kubectl global flags. This doesn't have anything to do with Krew. 

/close
/kind question
