### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by MartijnPDirekt** [kubernetes-sigs/krew#828]
Hi Krew maintainers, 

It has been a year since the latest release. Would be very nice to have the latest fixes and security patches included in our installation. Could you please create a release?!

Thanks in advance.

Kr,
Martijn

**Comment by ahmetb** [comment]
Which latest fixes and security patches are you referring to?
I am trying to understand if there's something that requires us to release at a particular cadence.

**Comment by MartijnPDirekt** [comment]
https://github.com/kubernetes-sigs/krew/pull/827 especially.

**Comment by MartijnPDirekt** [comment]
Please give me an update on this.

**Comment by ahmetb** [comment]
Thanks for reminding. Working on #829 to pick up latest dependencies and tag a release.
