### ISSUE TITLE
I have been struggling to install the OIDC-LOGIN plugin. I get Access is denied

### ISSUE THREAD

**Issue by ShantiSoft** [kubernetes-sigs/krew#831]
I have been struggling to install the OIDC-LOGIN using the following command:
`kubectl krew install oidc-login`

I get the following response:
```
PS C:\Users\xxxxxx> kubectl krew install oidc-login
Updated the local copy of plugin index.
Installing plugin: oidc-login
W0808 09:01:27.484292   35644 install.go:164] failed to install plugin "oidc-login": install failed: failed while moving files to the installation directory: could not rename/copy directory "C:\\Users\\xxxxxxx\\AppData\\Local\\Temp\\krew-temp-move1337463469" to "C:\\Users\\xxxxxxx0\\.krew\\store\\oidc-login\\v1.28.0": rename C:\Users\xxxxxxx\AppData\Local\Temp\krew-temp-move1337463469 C:\Users\xxxxxxx\.krew\store\oidc-login\v1.28.0: Access is denied.
failed to install some plugins: [oidc-login]: install failed: failed while moving files to the installation directory: could not rename/copy directory "C:\\Users\\xxxxxxx\\AppData\\Local\\Temp\\krew-temp-move1337463469" to "C:\\Users\\xxxxxxx\\.krew\\store\\oidc-login\\v1.28.0": rename C:\Users\xxxxxxx\AppData\Local\Temp\krew-temp-move1337463469 C:\Users\xxxxxxx\.krew\store\oidc-login\v1.28.0: Access is denied.
Error: exit status 1
```

I can happily install other krew plugins without a problem but i need to install this in order to authenticate to a remote K8s namespace.

Many thanks
Tom

**Comment by ahmetb** [comment]
This is a bit hard to reproduce on my end. Do you mind trying some other plugins and seeing which ones work and which ones don't?

`Access is denied.` error from Windows can mean a lot of things. This could be actually a file/directory permissions issue, or maybe you actually need to run the shell as Administrator to get it to work.

/kind support
/area platform/windows
