### ISSUE TITLE
stats.krew.dev is not updating

### ISSUE THREAD

**Issue by aro5000** [kubernetes-sigs/krew#845]
Hey @ahmetb ,

Apologies if this isn't the best place to bring this up, but it seems like the dashboard at `stats.krew.dev` is no longer updating or getting new data. I just figured I'd open up an issue here in case you weren't aware.

**Comment by ahmetb** [comment]
It was running on an internal GCP billing account. I don't think it will be possible to fix that at this point. Sorry.

**Comment by kwsorensen** [comment]
@ahmetb , any chance I could host this on a different internal GCP billing account? 
cc @kyle-google

**Comment by predatorray** [comment]
If you are still looking for a dashboard to display individual kew plugin stats, I implemented a simple version, which is hosted purely on GitHub (no GCP is needed). Hope this will help you.

- the project on GitHub: https://github.com/predatorray/krew-index-tracker
- the website hosted on Github Pages: https://predatorray.github.io/krew-index-tracker/

**Comment by ahmetb** [comment]
@predatorray I'd be happy to rewire the redirect to your site.

**Comment by predatorray** [comment]
Thanks, @ahmetb. It would be great if it can be used on Krew's website.

**Comment by kwsorensen** [comment]
Thanks @predatorray and @ahmetb.

**Comment by predatorray** [comment]
Hi @ahmetb , I just raised a [PR](https://github.com/kubernetes-sigs/krew/pull/872) according to what we discussed. I'd appreciate if you can help review it.

And also, I mentioned the redirection of "stats.krew.dev" in the PR. Please advise if there is anything I can do. Thanks!
