### ISSUE TITLE
Allow installing without sha256 when using --manifest-url

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/krew#846]
I want to distribute my plugin to a few colleagues at first before getting it into krew-index.
For that I want them to be able to just install from my manifest url which will point to the latest archive on github.
Atm this breaks because I always have to add a sha, so I have to tag a release and then come back and get the sha and re-push the  manifest.

I'd love either have:

Option A: no sha manifest, allow me toset `sha256: false` or `sha256: 'insecure'` to opt-out
Option B: No-sha install option: a `--no-sha` or `--ignore-sha` or `--insecure` flag that others can use to have a simple 1-line installer without me having to keep the sha up to date.

**Comment by ahmetb** [comment]
-manifest-url/-manifest-file is largely intended for testing manifests; not for distribution. You can still ship an executable to your colleagues and they can put it on their PATH?

We could change the scope and behavior here but I suspect it won't be a major UX improvement for a broad audience.

**Comment by grosser** [comment]
If it's intended for testing then allowing not using a Sha would make that
even easier ?

**Comment by ahmetb** [comment]
It's used for testing the correctness of the manifest locally without sending a PR, so sha256 validation is part of that.

**Comment by grosser** [comment]
yeah, but allowing it to be missing could be nice if I want to test
everything else except the sha
also allows pointing to a generic `latest.zip`
