### ISSUE TITLE
Allow selecting all platforms

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/krew#847]
Atm when using no selector I get
```
 is badly constructed: invalid platform selector: nil selector is not supported
```

It should say something like "If you want to target all platforms use X"

```
   selector:
      matchExpressions:
      - {key: "os", operator: "NotIn", values: ["true"]}
```

**Comment by ahmetb** [comment]
Can you give an executable that's valid on all platforms? If it's not a valid scenario, we don't need to support it.

**Comment by grosser** [comment]
With bash that should work. I'm doing Ruby which also works afaik.

**Comment by ahmetb** [comment]
Bash scripts are not executables on `windows`.

**Comment by grosser** [comment]
maybe it could print the link to docs for this field and the docs could explain how to do universal and bash etc gotchas

**Comment by ahmetb** [comment]
Project website has a fair amount of documentation on authoring manifests, so the code isn't a great place to link to this as it can also go out of date and break.

/close
