### ISSUE TITLE
support uninstall with --manifest-url

### ISSUE THREAD

**Issue by grosser** [kubernetes-sigs/krew#848]
I installed my new plugin with --manifest-url and now I want to remove it.

It's not intuitive

```
kubectl krew uninstall --manifest-url https://raw.githubusercontent.com/grosser/kubectl-patch-all/main/krew.yaml
unknown flag: --manifest-url
kubectl krew uninstall kubectl-patch-all
failed to uninstall plugin kubectl-patch-all: plugin is not installed
kubectl krew list
detached/patch-all  v0.0.1
kubectl krew uninstall detached/patch-all
uninstall command does not support INDEX/PLUGIN syntax; just specify PLUGIN
kubectl krew uninstall patch-all
... finally worked ...
```

cc @ahmetb  from https://github.com/kubernetes-sigs/krew/pull/429

**Comment by ahmetb** [comment]
I'm inclined to say it's largely intuitive to me and I haven't heard any complaints about this over the years. :) This might be a matter of taste, especially given the CLI interface is reasonably easy to scan and there is a user guide.

**Comment by grosser** [comment]
If it's easy to add it would be nice for completeness
