### ISSUE TITLE
Can we have krew plugin for x86 arch on prem ubuntu servers 

### ISSUE THREAD

**Issue by Naveen-LinuxAwsguy** [kubernetes-sigs/krew#855]
Can we have krew plugin for x86 arch on prem ubuntu servers, we tried, but since there is an architecture mismatch we are not able to install 

<img width="282" alt="image" src="https://github.com/kubernetes-sigs/krew/assets/66349740/42c6e764-d5b9-455a-a35c-ea78fc8c04d1">

**Comment by ahmetb** [comment]
It looks like you forgot to run chmod. 
/close
