### ISSUE TITLE
It complains 0.4.4 is not supported anymore on maiden install

### ISSUE THREAD

**Issue by boardtc** [kubernetes-sigs/krew#856]
I have been trying to install the latest v0.4.4 on windows today. trying in both cmd and Powershell I get:

This version of Krew is not supported anymore. Please manually migrate:
1. Uninstall Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/uninstall/
2. Install latest Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/
3. Install the plugins you used
krew home outdated

I have copied krew.exe to %USERPROFILE%\.krew\bin, updated path and restarted. Trying to install from my downloads directory with Krew present gets the same results. I never downloaded an older krew and v0.4.4 is current according to the page.

Apologies this reads like a total noob issue maybe it's the day that's in it but not getting past it currently.

**Comment by sighupper** [comment]
This is not limited to Windows. Is also happening on Mac:

```

test@test $ curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-darwin_arm64.tar.gz
+ curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/download/v0.4.4/krew-darwin_arm64.tar.gz
test@test $ tar zxvf krew-darwin_arm64.tar.gz
+ tar zxvf krew-darwin_arm64.tar.gz
x ./LICENSE
x ./krew-darwin_arm64
test@test $./krew-darwin_arm64
+ ./krew-darwin_arm64
krew is the kubectl plugin manager.
You can invoke krew through kubectl: "kubectl krew [command]..."

Usage:
  kubectl krew [command]

Available Commands:
  help        Help about any command
  index       Manage custom plugin indexes
  info        Show information about an available plugin
  install     Install kubectl plugins
  list        List installed kubectl plugins
  search      Discover kubectl plugins
  uninstall   Uninstall plugins
  update      Update the local copy of the plugin index
  upgrade     Upgrade installed plugins to newer versions
  version     Show krew version and diagnostics

Flags:
  -h, --help      help for krew
  -v, --v Level   number for the log level verbosity

Use "kubectl krew [command] --help" for more information about a command.
test@test $./krew-darwin_arm64 install
+ ./krew-darwin_arm64 install
This version of Krew is not supported anymore. Please manually migrate:
1. Uninstall Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/uninstall/
2. Install latest Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/
3. Install the plugins you used
krew home outdated

```

**Comment by ahmetb** [comment]
@sighupper you're manually invoking `./krew-darwin_arm64 install` –that's not what you think it does. The command at https://krew.sigs.k8s.io/docs/user-guide/setup/install/ specifically uses Krew to install Krew. So please stick to the command (which does `./"${KREW}" install krew`).

If it still fails even by copy pasting the exact command, please provide the full output (and ideally run the last command with `-v=7` flag).

Ideally we should remove this code path though so it stops causing issues.

**Comment by chriskim06** [comment]
to get this error you would need to have a plugin installed without any receipts https://github.com/kubernetes-sigs/krew/blob/master/internal/receiptsmigration/migration.go#L36-L39. on a fresh install though there would be no plugins installed yet (since this runs before the actual install of krew). since `!(hasInstalledPlugins && hasNoReceipts)` is false in your case you must have no receipts but an installed plugin somehow. could you show the output of ls for both  `/Users/mdavidson/.krew/bin` and `/Users/mdavidson/.krew/receipts`?

**Comment by sighupper** [comment]
So, I am using an ansible playbook for set up and it is throwing:
```
Install krew plugin manager for kubectl...  failed | msg: non-zero return code | stderr: This version of Krew is not supported anymore. Please manually migrate:
1. Uninstall Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/uninstall/
2. Install latest Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/
3. Install the plugins you used
krew home outdated
```
This even fails if `mv /Users/mdavidson/.krew/bin{,.bak}` and `mv /Users/mdavidson/.krew/receipts{,.bak}`.

That said, if I even mv those , then the set up guide steps work when doing them "manually". 

I will work on my playbook and circle back here if I have need any help. 

Thank you!

**Comment by boardtc** [comment]
@chriskim06 I have nothing installed other than in my OP. Have you tried an install on a clean virtual machine? It does not work :-(

**Comment by tony-sol** [comment]
Faced same issue while installing krew via [mise](https://mise.jdx.dev/)

Reason was i created $KREW_ROOT directory **before** installation. After i uninstalled krew, and deleted whole $KREW_ROOT, next installation was successfull
