### ISSUE TITLE
failed to retrieve plugin indexes

### ISSUE THREAD

**Issue by manuelcarriernunesatsap** [kubernetes-sigs/krew#859]
- I followed the following instructions (for Windows) to install Krew: https://krew.sigs.k8s.io/docs/user-guide/setup/install/#windows
- After installing, I ran (non-admin) `kubectl krew install oidc-login` in Windows Terminal hosting PowerShell (see screenshot below).
- After running the above command, I saw the following error message: `failed to retrieve plugin indexes: failed to list the remote URL for index default: command execution failure, output="": exit status 1`

![image](https://github.com/kubernetes-sigs/krew/assets/148589233/44f12e6f-5af1-47cf-99e6-f7fa06294a51)

Please help.

Best regards,
Manuel

**Comment by ahmetb** [comment]
/kind support 

does your git command work in that shell? Try running as Administrator maybe since Krew requires that.

**Comment by manuelcarriernunesatsap** [comment]
Yes, the git command works in that shell. I believe the screenshot below shows this.

![image](https://github.com/kubernetes-sigs/krew/assets/148589233/79308546-895d-4445-9ac3-d0f45bd3ca3e)

Running the `kubectl krew install oidc-login` command as an administrator installed the plugin.

I was under the impression that running as an administrator was only necessary during the installation of Krew (i.e., when I ran the `.\krew.exe install krew` command) because the installer creates a symbolic link, which requires administator access in Windows.

The error message could be improved, though. The error message says that Krew couldn't find the remote URL for index default. It's weird that Krew needs administrator access to get the URL. Might I suggest that the Krew development team add a note to the https://krew.sigs.k8s.io/docs/user-guide/installing-plugins/ page that says that Windows users must install plugins as administrators.

Thank you very much for providing a solution.

**Comment by ahmetb** [comment]
Do you mind rerunning the same command with -v=10 flag and pasting output. The output should be capturing permission issues.

**Comment by manuelcarriernunesatsap** [comment]
Not at all. Here is the output of running that command:
![image](https://github.com/kubernetes-sigs/krew/assets/148589233/2958b604-50be-4cbe-8f48-50daeaa044e2)

**Comment by ahmetb** [comment]
Can you run that “git config …” command listed manually in %home%\.krew\index\default please? It seems to be exiting with no output from this logs.

**Comment by manuelcarriernunesatsap** [comment]
When I run `git config --get remote.origin.url` as a non-administrator, I get the following:
![image](https://github.com/kubernetes-sigs/krew/assets/148589233/5a557715-60f4-4556-a0d0-d8d0474cd15c)

And when I run it as an administrator, I get the following:
![image](https://github.com/kubernetes-sigs/krew/assets/148589233/ce00451d-2d52-41e3-a96b-b54eec7dca3a)

**Comment by ahmetb** [comment]
I think this is something we can't easily help with. I believe our error message does its best already. I suspect this is a problem with your setup, something preventing execution of the command when not an Administrator and not letting git print anything maybe?

At any case, closing as wontfix now. I have not heard of another occurrence of this out in the wild. 

/close

**Comment by manuelcarriernunesatsap** [comment]
Wow!

**Comment by ahmetb** [comment]
@manuelcarriernunesatsap "Wow" what exactly?
The installation guide tells you that you to use "Administrator" user to install Krew.
Furthermore, Krew uses symlinks, so to be able to install plugins, you'll need to run as Administrator.

On top of all that, my Windows 11 installation runs "kubectl krew update" just fine without any failure. So, based on lack of any other reports I think this is not a widespread issue and it's just you.
