### ISSUE TITLE
Running into checksum issue for kubelogin_darwin_arm64.zip file.

### ISSUE THREAD

**Issue by AnkurSanghi2000** [kubernetes-sigs/krew#869]
The following is the error message:

failed to install plugin "oidc-login": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: 3f887eed9dcd87608df5caa2fb611a181716f516de5183c070aa83687a9c0c7a, got fc8e56d6d54f87dc18c4ce72f5ec1829144dd6d33077dcc72399845edb944732

**Comment by ahmetb** [comment]
/close

Please follow up with the repo distributing the plugin.
